function m(b,a,c,d){b.i.ca(b.V,a,c,d)}function n(b,a,c,d){b.i.s?m(b,a,c,d):b.i.Cb()._OnMessageFromDOM({type:"event",component:b.V,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function p(b,a,c){b.i.h(b.V,a,c)}function r(b,a){for(const [c,d]of a)p(b,c,d)}window.P=class{constructor(b,a){this.i=b;this.V=a}Ra(){}};window.ic=class{constructor(){}};"use strict";class aa{constructor(b){this.za=b;this.Da=!1;this.Ga=!0}}
function ba(b,a){const c=a.elementId,d=b.qa(c,a),e=new aa(d);b.W.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Ga=!!a.isVisible;d.addEventListener("focus",()=>{t(b,"elem-focused",c)});d.addEventListener("blur",()=>{t(b,"elem-blurred",c)});b.ha&&document.body.appendChild(d)}function u(b,a,c){p(b,a,d=>{const e=v(b,d.elementId);return c(e,d)})}function v(b,a){b=b.W.get(a);if(!b)throw Error(`no element with id ${a}`);return b.za}
function t(b,a,c,d){d||(d={});d.elementId=c;m(b,a,d)}function w(b,a,c,d){d||(d={});d.elementId=c;n(b,a,d)}
window.Ta=class extends self.P{constructor(b,a){super(b,a);this.W=new Map;this.ha=!0;r(this,[["create",c=>ba(this,c)],["destroy",c=>{c=c.elementId;const d=v(this,c);this.ha&&d.parentElement.removeChild(d);this.W.delete(c)}],["set-visible",c=>{if(this.ha){var d=this.W.get(c.elementId),e=d.za;d.Da?e.style.display=c.isVisible?"":"none":d.Ga=!!c.isVisible}}],["update-position",c=>{if(this.ha){var d=this.W.get(c.elementId),e=d.za;e.style.left=c.left+"px";e.style.top=c.top+"px";e.style.width=c.width+"px";
e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.Da||(d.Da=!0,d.Ga&&(e.style.display=""))}}],["update-state",c=>{const d=v(this,c.elementId);this.da(d,c)}],["focus",c=>{const d=v(this,c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=v(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{v(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{v(this,c.elementId).removeAttribute(c.name)}]]);
u(this,"get-element",c=>c)}qa(){throw Error("required override");}da(){throw Error("required override");}};"use strict";const ca=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent),da=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ea=0;
function y(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Yb?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.bc+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let fa=!1,ha=!1;function ia(){if(!fa){try{new Worker("blob://",{get type(){ha=!0}})}catch(b){}fa=!0}return ha}let z=new Audio;
const ja={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;async function ka(b){b=await la(b);return(new TextDecoder("utf-8")).decode(b)}
function la(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const A=[];let B=0;window.RealFile=window.File;const C=[],D=new Map,E=new Map;let ma=0;const na=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");na.push(b)};const oa=new Set(["cordova","playable-ad","instant-games"]);let pa=!1;
window.F=class b{constructor(a){this.s=a.dc;this.Z=null;this.o="";this.L=a.ac;this.ba={};this.Ja=this.N=null;this.ia=[];this.j=this.H=null;this.hb=!1;this.X=null;this.K=-1;this.Ub=()=>this.Kb();this.Ma=[];this.Pa=null;this.kb=[];this.g=a.lb;this.Fa="file"===location.protocol.substr(0,4);!this.s||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ia()||(this.s=!1);this.s&&da&&(this.s=!1);if("playable-ad"===this.g||"instant-games"===this.g)this.s=!1;if("cordova"===this.g&&this.s)if(x){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.s=!1)}else this.s=!1;this.S()?self.chrome.webview.addEventListener("message",c=>this.Za(c.data)):"macos-wkwebview"===this.g&&(self.C3WrapperOnMessage=c=>this.Za(c));this.ka=this.C=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.h("runtime",
"cordova-fetch-local-file",c=>this.Gb(c));this.h("runtime","create-job-worker",()=>this.Hb());this.h("runtime","send-wrapper-extension-message",c=>this.Nb(c));"cordova"===this.g?document.addEventListener("deviceready",()=>this.Xa(a)):this.Xa(a)}qb(){return ca&&"cordova"===this.g}sa(){const a=navigator.userAgent;return ca&&oa.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}ob(){return x}Ua(){return x&&oa.has(this.g)}S(){return"windows-webview2"===this.g||!!("preview"===this.g&&
window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}async Xa(a){"macos-wkwebview"===this.g?this.T({type:"ready"}):this.S()&&(this.Pb(),this.kb=(await this.Fb()).registeredComponentIds);if("playable-ad"===this.g){this.C=self.c3_base64files;this.ka={};await this.yb();for(let d=0,e=a.O.length;d<e;++d){var c=a.O[d];this.ka.hasOwnProperty(c)?a.O[d]={Yb:!0,bc:this.ka[c]}:this.C.hasOwnProperty(c)&&(a.O[d]=URL.createObjectURL(this.C[c]))}a.oa=[]}if("nwjs"===this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=
0;this.ub(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.$b?this.o=a.$b:(c=location.origin,this.o=("null"===c?"file:///":c)+location.pathname,c=this.o.lastIndexOf("/"),-1!==c&&(this.o=this.o.substr(0,c+1)));a.fc&&(this.ba=a.fc);c=new MessageChannel;this.Z=c.port1;this.Z.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Jb(d));this.X=new self.rb(this);await qa(this.X);"object"===typeof window.StatusBar&&window.StatusBar.hide();
if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.s?await this.Eb(a,c.port2):await this.Db(a,c.port2)}ua(a){a=this.ba.hasOwnProperty(a)?this.ba[a]:a.endsWith("/workermain.js")&&this.ba.hasOwnProperty("workermain.js")?this.ba["workermain.js"]:"playable-ad"===this.g&&this.C.hasOwnProperty(a)?this.C[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ra(a,
c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.g&&this.Fa)return a=await this.pa(d.Xb?a:this.L+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}B(){return Math.max(window.innerWidth,1)}v(){return Math.max(window.innerHeight,1)}Wa(a){var c=
this.o,d=location.href,e=this.B(),f=this.v(),h=window.devicePixelRatio,g=b.R(),k=a.lc,l=window.cr_previewImageBlobs||this.C,q=window.cr_previewProjectFileBlobs,Fa=window.cr_previewProjectFiles,Ga=window.cr_swClientId||"";a=a.lb;var Ha=(new URLSearchParams(self.location.search)).has("debug"),S=this.X;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:h,isFullscreen:g,projectData:k,previewImageBlobs:l,previewProjectFileBlobs:q,previewProjectFileSWUrls:Fa,swClientId:Ga,
exportType:a,isDebug:Ha,ife:!!self.kc,jobScheduler:{inputPort:S.Ea,outputPort:S.La,maxNumWorkers:S.Sb},supportedAudioFormats:ja,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.L+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.L+"opus.wasm.wasm",isFileProtocol:this.Fa,isiOSCordova:this.qb(),isiOSWebView:this.sa(),isWebView2Wrapper:this.S(),wrapperComponentIds:this.kb,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Eb(a,c){const d=this.ua(a.ec);"preview"===this.g?
(this.N=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((g,k)=>{const l=q=>{this.N.removeEventListener("message",l);q.data&&"ok"===q.data.type?g():k()};this.N.addEventListener("message",l);this.N.postMessage({type:"construct-worker-init","import":(new URL(d,this.o)).toString()})})):this.N=await this.ra(d,this.o,{type:"module",name:"Runtime",Xb:!0});this.j=document.createElement("canvas");this.j.style.display="none";const e=this.j.transferControlToOffscreen();document.body.appendChild(this.j);
window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.oa||[],h=a.O;f=await Promise.all(f.map(g=>this.J(g)));h=await Promise.all(h.map(g=>this.J(g)));if("cordova"===this.g)for(let g=0,k=a.na.length;g<k;++g){const l=a.na[g],q=l[0];if(q===a.Qa||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))l[1]=await this.J(q)}this.N.postMessage(Object.assign(this.Wa(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:h,
projectScripts:a.na,mainProjectScript:a.Qa,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...ra(this.X)]);this.ia=C.map(g=>new g(this));this.Va();sa(this.H);self.c3_callFunction=(g,k)=>{var l=this.H;return l.i.sb(l.V,{name:g,params:k})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.ca("runtime","go-to-last-error-script"))}async Db(a,c){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&
self.C3_InsertHTMLPlaceholders();this.ia=C.map(h=>new h(this));this.Va();var d=a.O.map(h=>"string"===typeof h?(new URL(h,this.o)).toString():h);if(Array.isArray(a.oa)){var e=[...a.oa].map(h=>h instanceof Blob?URL.createObjectURL(h):h);d.unshift(...e)}d=await Promise.all(d.map(h=>this.J(h)));await Promise.all(d.map(h=>y(h)));d=self.C3_ProjectScriptsStatus;e=a.Qa;const f=a.na;for(let [h,g]of f)if(g||(g=h),h===e)try{g=await this.J(g),await y(g),"preview"!==this.g||d[h]||this.$a(h,"main script did not run to completion")}catch(k){this.$a(h,
k)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))g=await this.J(g),await y(g);"preview"===this.g&&"object"!==typeof self.hc.jc?(this.fa(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Wa(a),{isInWorker:!1,messagePort:c,canvas:this.j,runOnStartupFunctions:na}),sa(this.H),
this.Ya(),this.Ja=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ja,a))}$a(a,c){this.fa();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ya(){this.fa()}fa(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Hb(){const a=await ta(this.X);return{outputPort:a,
transferables:[a]}}Cb(){if(this.s)throw Error("not available in worker mode");return this.Ja}ca(a,c,d,e){this.Z.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},void 0)}sb(a,c){const d=ma++,e=new Promise((f,h)=>{E.set(d,{resolve:f,reject:h})});this.Z.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:c,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Ib(a);if("result"===
c)this.Lb(a);else if("runtime-ready"===c)this.Mb();else if("alert-error"===c)this.fa(),alert(a.message);else if("creating-runtime"===c)this.Ya();else throw Error(`unknown message '${c}'`);}Ib(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=D.get(c))if(a=a.get(d)){var h=null;try{h=a(e)}catch(g){console.error(`Exception in '${c}' handler '${d}':`,g);null!==f&&this.ea(f,!1,""+g);return}if(null===f)return h;h&&h.then?h.then(g=>this.ea(f,!0,g)).catch(g=>{console.error(`Rejection from '${c}' handler '${d}':`,
g);this.ea(f,!1,""+g)}):this.ea(f,!0,h)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}ea(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.Z.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Lb(a){const c=a.responseId,d=a.isOk;a=a.result;const e=E.get(c);d?e.resolve(a):e.reject(a);E.delete(c)}h(a,c,d){let e=D.get(a);e||(e=new Map,D.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);
e.set(c,d)}static I(a){if(C.includes(a))throw Error("DOM handler already added");C.push(a)}Va(){for(const a of this.ia)if("runtime"===a.V){this.H=a;return}throw Error("cannot find runtime DOM handler");}Jb(a){this.ca("debugger","message",a)}Mb(){for(const a of this.ia)a.Ra()}static R(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||pa)}static ab(a){pa=!!a}ub(a){this.Ma.push(a);this.wa()}wa(){-1===this.K&&this.Ma.length&&(this.K=requestAnimationFrame(this.Ub))}wb(){-1!==
this.K&&(cancelAnimationFrame(this.K),this.K=-1)}Kb(){this.K=-1;for(const a of this.Ma)a();this.wa()}va(){this.H.va()}tb(){this.hb=!0}nb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}pb(a){return!this.nb(a)}async J(a){return"cordova"===this.g&&(a.startsWith("file:")||this.Fa&&this.pb(a))?(a.startsWith(this.o)&&(a=a.substr(this.o.length)),a=await this.pa(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Gb(a){const c=a.filename;
switch(a.as){case "text":return await this.mb(c);case "buffer":return await this.pa(c);default:throw Error("unsupported type");}}Sa(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async mb(a){a=await this.Sa(a);return await ka(a)}ta(){if(A.length&&!(8<=B)){B++;var a=A.shift();this.zb(a.filename,a.cc,a.Wb)}}pa(a){return new Promise((c,d)=>{A.push({filename:a,cc:e=>{B--;this.ta();c(e)},Wb:e=>{B--;this.ta();
d(e)}});this.ta()})}async zb(a,c,d){try{const e=await this.Sa(a),f=await la(e);c(f)}catch(e){d(e)}}Za(a){if("entered-fullscreen"===a)b.ab(!0),G(this.H);else if("exited-fullscreen"===a)b.ab(!1),G(this.H);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.Pa(a),this.Pa=null):"extension-message"===c?this.ca("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Nb(a){this.T({type:"extension-message",
componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}T(a){this.S()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.g&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Pb(){window.moveTo=(a,c)=>{this.T({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.T({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Fb(){return this.S()?new Promise(a=>
{this.Pa=a;this.T({type:"wrapper-init"})}):Promise.resolve()}async yb(){const a=[];for(const [c,d]of Object.entries(this.C))a.push(this.xb(c,d));await Promise.all(a)}async xb(a,c){if("object"===typeof c)this.C[a]=new Blob([c.str],{type:c.type}),this.ka[a]=c.str;else{let d=await this.Bb(c);d||(d=this.Ab(c));this.C[a]=d}}async Bb(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}Ab(a){a=this.Ob(a);return this.vb(a.data,a.Zb)}Ob(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Zb:a,data:d}}vb(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),h=new Uint32Array(f.buffer,0,e),g,k;for(k=g=0;g<e;++g)h[g]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const H=self.F;function ua(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const va=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},wa={dispatchUserScriptEvent:!0},J={dispatchRuntimeEvent:!0};
function xa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function ya(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function K(b){b=URL.createObjectURL(b);try{return await ya(b)}finally{URL.revokeObjectURL(b)}}
function za(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Aa(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await K(b);var d=await za(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),h=e.getAttribute("height");if(!f.includes("%")&&!h.includes("%"))return await K(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await K(b)}
function L(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ba=new Set(["input","textarea","datalist","select"]),Ca=new Set(["canvas","body","html"]);function M(b){b.target.tagName&&Ca.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Da(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await K(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Aa(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let N=!1;document.addEventListener("pause",()=>N=!0);document.addEventListener("resume",()=>N=!1);function sa(b){b.fb=!0;b.Ia=b.i.B();b.Y=b.i.v()}function G(b){if(!b.m){var a=H.R();a&&"any"!==b.Na&&Ea(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.B(),innerHeight:b.v()})}}async function Ia(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ja(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ka(b){return await self.C3_GetSvgImageSize(b.blob)}function La(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ma(b){self.setTimeout(()=>{b.eb=!0},1E3);"cordova"===b.i.g?(document.addEventListener("pause",()=>O(b,!0)),document.addEventListener("resume",()=>O(b,!1))):document.addEventListener("visibilitychange",()=>O(b,"hidden"===document.visibilityState));b.la=!("hidden"!==document.visibilityState&&!N);return{isSuspended:b.la}}
function Na(b){b.cb||(b.cb=!0,window.addEventListener("deviceorientation",a=>{b.m||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.m||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Oa(b){b.bb||(b.bb=!0,window.addEventListener("devicemotion",a=>{if(!b.m){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Pa(b){await xa(b.url)}
function Qa(b,a){b.gb=a.message;-1===b.Aa&&(b.Aa=setTimeout(()=>{b.Aa=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.gb)},250))}function Q(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:H.R(),innerWidth:b.B(),innerHeight:b.v()})}function O(b,a){b.la!==a&&((b.la=a)?b.i.wb():b.i.wa(),m(b,"visibilitychange",{hidden:a}))}
function Ra(b,a,c){"Backspace"===c.key&&M(c);if(!b.m){var d=va.get(c.code)||c.code;n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}function R(b,a,c,d){b.m||ua(c)||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.u,pageX:c.pageX,pageY:c.pageY+b.u,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function T(b){window!==window.top&&window.focus();Sa(b.target)&&document.activeElement&&!Sa(document.activeElement)&&document.activeElement.blur()}
function U(b,a,c){if(!b.m){var d=0;"mouse"===c.pointerType&&(d=b.$);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.u,pageX:c.pageX,pageY:c.pageY+b.u,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},I);"mouse"===c.pointerType&&(d="mousemove",
"pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),R(b,d,c,wa),b.$=c.buttons)}}
function Ua(b,a,c){if(!b.m&&!ua(c)){var d=b.$;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");n(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.u,pageX:c.pageX,pageY:c.pageY+b.u,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},I);b.$=c.buttons;R(b,c.type,c,wa)}}
function V(b,a,c){if(!b.m)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];n(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.u,pageX:f.pageX,pageY:f.pageY+b.u,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
I)}}function Va(b,a,c){document.body.style.transform="";b.u=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.u=a))}}function Wa(b,a,c,d){const e=b.B(),f=b.v();b.M=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.R()}):10>d&&Xa(b,e,f,d+1)}
function Xa(b,a,c,d){-1!==b.M&&clearTimeout(b.M);b.M=setTimeout(()=>Wa(b,a,c,d),48)}
function Ea(b){b=b.Na;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Sa(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.I(class extends self.P{constructor(b){super(b,"runtime");this.ib=!0;this.fb=!1;this.M=-1;this.Na="any";this.la=this.bb=this.cb=!1;this.ma=document.createElement("div");this.ma.className="c3-screen-reader-text";this.ma.setAttribute("aria-live","polite");document.body.appendChild(this.ma);this.G=null;this.m=!1;this.gb="";this.Aa=-1;this.eb=!1;this.Ia=b.B();this.Y=b.v();this.u=this.aa=0;b.h("canvas","update-size",d=>{var e=this.i;e.hb||(e=e.j,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.ib&&(e.style.display="",this.ib=!1))});b.h("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),h=document.body;f.textContent=d;f.href=e;f.download=d;h.appendChild(f);f.click();h.removeChild(f)});b.h("runtime","load-webfonts",d=>Ia(d));b.h("runtime","raster-svg-image",d=>Ja(d));b.h("runtime","get-svg-image-size",
d=>Ka(d));b.h("runtime","set-target-orientation",d=>{this.Na=d.targetOrientation});b.h("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.h("runtime","post-to-debugger",d=>La(d));b.h("runtime","go-to-script",d=>La(d));b.h("runtime","before-start-ticking",()=>Ma(this));b.h("runtime","debug-highlight",d=>{if(d.show){this.G||(this.G=document.createElement("div"),this.G.id="inspectOutline",document.body.appendChild(this.G));var e=this.G;e.style.display="";e.style.left=d.left-
1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.G&&(this.G.style.display="none")});b.h("runtime","enable-device-orientation",()=>Na(this));b.h("runtime","enable-device-motion",()=>Oa(this));b.h("runtime","add-stylesheet",d=>Pa(d));b.h("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.h("runtime","alert",d=>{alert(d.message)});b.h("runtime",
"screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.ma.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.h("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.h("runtime","set-exporting-to-video",d=>{this.m=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.tb()});b.h("runtime","export-to-video-progress",d=>Qa(this,d));b.h("runtime","exported-to-video",d=>{window.Vb({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.h("runtime","exported-to-image-sequence",d=>{window.Vb({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||L(e)||d.preventDefault()});const c=b.j;window.addEventListener("selectstart",M);window.addEventListener("gesturehold",M);c.addEventListener("selectstart",M);c.addEventListener("gesturehold",
M);window.addEventListener("touchstart",M,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",M,{passive:!1}),c.addEventListener("pointerdown",M)):c.addEventListener("touchstart",M);this.$=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Da,{passive:!1});window.addEventListener("wheel",Da,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.m&&this.fb){var d=this.B();var e=this.v();if(this.i.Ua()){if(this.eb){if(this.Ia===
d&&e<this.Y){this.aa=this.Y-e;Va(this,this.Y,this.aa);d=void 0;break a}0<this.aa&&(this.aa=0,Va(this,e,this.aa))}this.Ia=d;this.Y=e}m(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.R()});this.i.sa()&&(-1!==this.M&&clearTimeout(this.M),Wa(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>G(this));window.addEventListener("webkitfullscreenchange",()=>G(this));window.addEventListener("mozfullscreenchange",()=>G(this));
window.addEventListener("fullscreenerror",d=>Q(this,d));window.addEventListener("webkitfullscreenerror",d=>Q(this,d));window.addEventListener("mozfullscreenerror",d=>Q(this,d));if(b.sa())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):L(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});this.Ka=new Set;this.Tb=new WeakSet;this.Rb=!1}Ra(){window.addEventListener("focus",()=>{m(this,"window-focus",null,J)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}m(this,"window-blur",{parentHasFocus:a},J);this.$=0});window.addEventListener("focusin",a=>{a=a.target;(Ba.has(a.tagName.toLowerCase())||L(a))&&
m(this,"keyboard-blur",null,J)});window.addEventListener("keydown",a=>Ra(this,"keydown",a));window.addEventListener("keyup",a=>Ra(this,"keyup",a));window.addEventListener("dblclick",a=>R(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.m||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.u,pageX:a.pageX,pageY:a.pageY+this.u,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{T(a);U(this,"pointerdown",a)}),this.i.s&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{U(this,"pointermove",a)}):window.addEventListener("pointermove",a=>U(this,"pointermove",a)),window.addEventListener("pointerup",a=>U(this,"pointerup",a)),window.addEventListener("pointercancel",a=>U(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{T(a);Ua(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>Ua(this,
"pointermove",a)),window.addEventListener("mouseup",a=>Ua(this,"pointerup",a)),window.addEventListener("touchstart",a=>{T(a);V(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>V(this,"pointermove",a)),window.addEventListener("touchend",a=>V(this,"pointerup",a)),window.addEventListener("touchcancel",a=>V(this,"pointercancel",a)));const b=()=>this.va();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.i.ob()&&!this.i.Ua()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Va(this,this.v(),navigator.virtualKeyboard.boundingRect.height)}))}B(){return this.i.B()}v(){return this.i.v()}va(){var b=[...this.Ka];this.Ka.clear();if(!this.Rb)for(const a of b)(b=a.play())&&b.catch(()=>{this.Tb.has(a)||this.Ka.add(a)})}});"use strict";
async function qa(b){if(b.Qb)throw Error("already initialised");b.Qb=!0;var a=b.D.ua(("playable-ad"===b.D.g?b.D.L:"")+"dispatchworker.js");b.ya=await b.D.ra(a,b.U,{name:"DispatchWorker"});a=new MessageChannel;b.Ea=a.port1;b.ya.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.La=await ta(b)}function ra(b){return[b.Ea,b.La]}
async function ta(b){const a=b.jb.length;var c=b.D.ua(("playable-ad"===b.D.g?b.D.L:"")+"jobworker.js");c=await b.D.ra(c,b.U,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.ya.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.jb.push(c);return e.port1}
self.rb=class{constructor(b){this.D=b;this.U=b.o;this.U="preview"===b.g?this.U+"workers/":this.U+b.L;this.Sb=Math.min(navigator.hardwareConcurrency||2,16);this.ya=null;this.jb=[];this.La=this.Ea=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.F({dc:!0,ec:"workermain.js",O:["scripts/c3runtime.js"],na:[],Qa:"",ac:"scripts/",oa:[],lb:"html5"}));"use strict";
self.F.I(class extends self.P{constructor(b){super(b,"mouse");r(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.i.j.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function Ya(b,a){a=a.type;let c=!0;0===a?c=await Za():1===a&&(c=await $a());m(b,"permission-result",{type:a,result:c})}async function Za(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function $a(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.F.I(class extends self.P{constructor(b){super(b,"touch");p(this,"request-permission",a=>Ya(this,a))}});"use strict";function W(b){b.stopPropagation()}function ab(b){13!==b.which&&27!==b.which&&b.stopPropagation()}
self.F.I(class extends self.Ta{constructor(b){super(b,"text-input");u(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}qa(b,a){let c;const d=a.type;"textarea"===d?(c=document.createElement("textarea"),c.style.resize="none"):(c=document.createElement("input"),c.type=d);c.style.position="absolute";c.autocomplete="off";c.addEventListener("pointerdown",W);c.addEventListener("pointermove",W);c.addEventListener("pointerrawupdate",W);c.addEventListener("pointerup",W);c.addEventListener("mousedown",
W);c.addEventListener("mouseup",W);c.addEventListener("keydown",ab);c.addEventListener("keyup",ab);c.addEventListener("click",e=>{e.stopPropagation();w(this,"click",b)});c.addEventListener("dblclick",e=>{e.stopPropagation();w(this,"dblclick",b)});c.addEventListener("input",()=>t(this,"change",b,{text:c.value}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.da(c,a);return c}da(b,a){b.value=a.text;b.placeholder=a.placeholder;b.title=a.title;b.disabled=!a.isEnabled;b.readOnly=a.isReadOnly;
b.spellcheck=a.spellCheck;a=a.maxLength;0>a?b.removeAttribute("maxlength"):b.setAttribute("maxlength",a)}});"use strict";function bb(b){b.replaceChildren?b.replaceChildren():b.innerHTML=""}
function X(b){b=Array.from(b.querySelectorAll("script:not([c3-executed])"));for(const c of b){b=c.parentNode;var a=b.replaceChild;const d=document.createElement("script");d.text=c.text;const e=c.attributes;for(let f=0,h=e.length;f<h;++f){const g=e[f];d.setAttribute(g.name,g.value)}d.setAttribute("c3-executed","");a.call(b,d,c)}}function Y(b,a,c){return a?c?Array.from(b.querySelectorAll(a)):(b=b.querySelector(a))?[b]:[]:[b]}
function Z(b){return b?{isOk:!0,html:b.innerHTML,text:b.textContent}:{isOk:!1}}
self.F.I(class extends self.Ta{constructor(b){super(b,"html-element");u(this,"set-content",(a,c)=>{{const e=c.str,f=c.type,h=c.selector;c=c["is-all"];try{const g=Y(a,h,c);if(0===g.length)var d=Z(null);else{for(const k of g)"html"===f?(k.innerHTML=e,X(k)):k.textContent=e;d=Z(a)}}catch(g){console.warn("[HTML element] Failed to set content: ",g),d=Z(null)}}return d});u(this,"insert-content",(a,c)=>{{const e=c.str,f=c.type,h=c["at-end"]?"beforeend":"afterbegin",g=c.selector;c=c["is-all"];try{const k=
Y(a,g,c);if(0===k.length)var d=Z(null);else{for(const l of k)"html"===f?(l.insertAdjacentHTML(h,e),X(l)):l.insertAdjacentText(h,e);d=Z(a)}}catch(k){console.warn("[HTML element] Failed to insert content: ",k),d=Z(null)}}return d});u(this,"remove-content",(a,c)=>{{const e=c["is-clear"],f=c.selector;c=c["is-all"];if(f)try{const h=Y(a,f,c);if(0===h.length)var d=Z(null);else{for(const g of h)e?bb(g):g.remove();d=Z(a)}}catch(h){console.warn("[HTML element] Failed to remove content: ",h),d=Z(null)}else bb(a),
d=Z(a)}return d});u(this,"set-content-class",(a,c)=>{{const e=c.mode,f=c["class-array"],h=c.selector;c=c["is-all"];try{const g=Y(a,h,c);if(0===g.length)var d=Z(null);else{for(const k of g)for(const l of f)switch(e){case "add":k.classList.add(l);break;case "toggle":k.classList.toggle(l);break;case "remove":k.classList.remove(l)}d=Z(a)}}catch(g){console.warn("[HTML element] Failed to set class: ",g),d=Z(null)}}return d});u(this,"set-content-attribute",(a,c)=>{{const e=c.mode,f=c.attribute,h=c.value,
g=c.selector;c=c["is-all"];try{const k=Y(a,g,c);if(0===k.length)var d=Z(null);else{for(const l of k)switch(e){case "set":l.setAttribute(f,h);break;case "remove":l.removeAttribute(f)}d=Z(a)}}catch(k){console.warn("[HTML element] Failed to set attribute: ",k),d=Z(null)}}return d});u(this,"set-content-css-style",(a,c)=>{{const e=c.prop,f=c.value,h=c.selector;c=c["is-all"];try{const g=Y(a,h,c);if(0===g.length)var d=Z(null);else{for(const k of g)e.startsWith("--")?k.style.setProperty(e,f):k.style[e]=f;
d=Z(a)}}catch(g){console.warn("[HTML element] Failed to set style: ",g),d=Z(null)}}return d});u(this,"get-element-box",(a,c)=>{(a=(c=c.selector)?a.querySelector(c):a)?(a=a.getBoundingClientRect(),a={isOk:!0,left:a.left,top:a.top,right:a.right,bottom:a.bottom}):a={isOk:!1};return a});u(this,"insert-img-element",(a,c)=>{a:{const e=c.blobUrl;var d=c.width;const f=c.height,h=c.selector,g=c.insertAt;let k=a;if(h&&(k=a.querySelector(h),!k)){a={isOk:!1};break a}d=new Image(d,f);d.src=e;c.id&&(d.id=c.id);
c["class"]&&(d.className=c["class"]);0===g?k.prepend(d):1===g?k.append(d):k.replaceChildren?k.replaceChildren(d):(bb(k),k.append(d));a=Z(a)}return a});u(this,"set-scroll-position",(a,c)=>{a:{const d=c.selector,e=c.direction;c=c.position;if(d&&(a=a.querySelector(d),!a)){c=void 0;break a}"left"===e?a.scrollLeft=c:a.scrollTop=c;c=void 0}return c})}qa(b,a){const c=document.createElement(a.tag);a["style-attribute"]&&c.setAttribute("style",a["style-attribute"]);c.style.position="absolute";var d=a["stop-input-events-mode"];
if(0<d){let e=null;1===d?e=f=>{f.target!==c&&f.stopPropagation()}:2===d&&(e=f=>f.stopPropagation());c.addEventListener("pointerdown",e);c.addEventListener("pointermove",e);c.addEventListener("pointerrawupdate",e);c.addEventListener("pointerup",e);c.addEventListener("mousedown",e);c.addEventListener("mouseup",e);c.addEventListener("dblclick",e)}a["allow-context-menu"]&&c.addEventListener("contextmenu",e=>e.stopPropagation());c.addEventListener("click",e=>{e=e.target;const f=[];for(;e;){f.push({targetId:"string"===
typeof e.id?e.id:"",targetClass:"string"===typeof e.className?e.className:""});if(e===c)break;e=e.parentNode}w(this,"click",b,{chain:f})});c.addEventListener("animationend",e=>{const f=e.target;w(this,"animationend",b,{targetId:"string"===typeof f.id?f.id:"",targetClass:"string"===typeof f.className?f.className:"",animationName:e.animationName})});a.id&&(c.id=a.id);a.className&&(c.className=a.className);a["css-color"]&&(c.style.color=a["css-color"]);a["css-background-color"]&&(c.style.backgroundColor=
a["css-background-color"]);a["allow-text-selection"]||(c.style.userSelect="none",c.style.webkitUserSelect="none");d=a.str;"html"===a.type?(c.innerHTML=d,X(c)):c.textContent=d;w(this,"initial-content",b,{html:c.innerHTML,text:c.textContent});return c}da(b,a){b.innerHTML=a.html;X(b)}});"use strict";
function cb(b){b.l=window.FB;let a=location.pathname;"/"!==a.substr(a.length-1)&&(a=a.substr(0,a.lastIndexOf("/")+1));b.l.init({version:"v3.0",appId:b.ga,status:!0,cookie:!0,xfbml:!1});b.l.Event.subscribe("auth.login",c=>db(b,c));b.l.Event.subscribe("auth.logout",()=>{b.A=!1;b.xa="";b.Ca="";b.Ba="";b.Ha="";m(b,"logout")});b.l.getLoginStatus(c=>db(b,c));b.ja&&(b.ja(),b.ja=null)}
async function eb(b,a){b.ga=a.appId;if(!b.ga)return console.log("[Facebook] No App ID provided. Please enter an App ID before using the object."),!1;try{return await fb(b),!0}catch(c){return console.error("[Facebook] Error loading Facebook API: ",c),!1}}function gb(b,a){b.A||b.l.login(c=>db(b,c),{scope:a.permissions})}function hb(b){b.A&&b.l.logout(()=>{})}function ib(b){b.A&&b.l.ui({method:"feed"},a=>{a&&a.error&&console.error("[Facebook] Error prompting wall post: ",a.error)})}
function jb(b){b.A&&b.l.ui({method:"feed",link:"https://apps.facebook.com/"+b.ga+"/"},a=>{a&&a.error&&console.error("[Facebook] Error prompting to share app: ",a.error)})}function kb(b,a){b.A&&b.l.ui({method:"feed",link:a.url},c=>{c&&c.error&&console.error("[Facebook] Error prompting to share link: ",c.error)})}function lb(b,a){b.A&&b.l.api("/me/feed","POST",{method:"stream.publish",message:a.message},c=>{c&&c.error&&console.error("[Facebook] Error publishing to wall: ",c.error)})}
function mb(b,a){if(b.A){var c={method:"stream.publish",message:a.message,link:a.url,name:a.name,caption:a.caption,description:a.description};a.picture&&(c.picture=a.picture);b.l.api("/me/feed","POST",c,d=>{d&&d.error&&console.error("[Facebook] Error publishing link: ",d.error)})}}
function fb(b){return new Promise((a,c)=>{document.getElementById("facebook-jssdk")?a():(b.ja=a,a=document.createElement("script"),a.id="facebook-jssdk",a.onerror=c,a.async=!0,a.src="//connect.facebook.net/en_US/sdk.js",document.getElementsByTagName("head")[0].appendChild(a))})}
function db(b,a){a.authResponse&&!b.A&&(b.A=!0,b.Oa=a.authResponse.userID,console.log("[Facebook] Logged in as user ID: "+b.Oa),b.xa=a.authResponse.accessToken,m(b,"login",{userId:b.Oa,accessToken:b.xa}),b.l.api("/me?fields=name,first_name,last_name",c=>{b.Ca=c.name;b.Ba=c.first_name;b.Ha=c.last_name;m(b,"name-available",{fullName:b.Ca,firstName:b.Ba,lastName:b.Ha})}))}
self.F.I(class extends self.P{constructor(b){super(b,"facebook");this.l=null;this.ga="";this.A=!1;this.Ha=this.Ba=this.Ca=this.xa=this.Oa="";this.ja=null;window.fbAsyncInit=()=>cb(this);r(this,[["load",a=>eb(this,a)],["login",a=>gb(this,a)],["logout",()=>hb(this)],["prompt-wall-post",()=>ib(this)],["prompt-share-app",()=>jb(this)],["prompt-share-link",a=>kb(this,a)],["publish-to-wall",a=>lb(this,a)],["publish-link",a=>mb(this,a)],["on-cta-click",()=>{self.FbPlayableAd&&self.FbPlayableAd.onCTAClick?
(console.log("[Facebook] CTA clicked: calling FbPlayableAd.onCTAClick()"),self.FbPlayableAd.onCTAClick()):console.warn("[Facebook] CTA clicked: FbPlayableAd.onCTAClick() function not available - check running as a Playable Ad")}]])}});
