function l(b,a,c,d){b.v.mb(b.qb,a,c,d)}function n(b,a,c,d){b.v.da?l(b,a,c,d):b.v.Ke()._OnMessageFromDOM({type:"event",component:b.qb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function p(b,a,c){b.v.C(b.qb,a,c)}function r(b,a){for(const [c,d]of a)p(b,c,d)}function aa(b){b.Vb||(b.v.vd(b.ce),b.Vb=!0)}window.Na=class{constructor(b,a){this.v=b;this.qb=a;this.Vb=!1;this.ce=()=>this.Qa()}md(){}Qa(){}};
window.uf=class{constructor(){this.gd=-1}j(){-1!==this.gd&&(self.clearTimeout(this.gd),this.gd=-1)}};"use strict";class ba{constructor(b){this.Lc=b;this.Qc=!1;this.Xc=!0}}function ca(b,a){const c=a.elementId,d=b.pc(c,a),e=new ba(d);b.tb.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Xc=!!a.isVisible;d.addEventListener("focus",()=>{da(b,"elem-focused",c)});d.addEventListener("blur",()=>{da(b,"elem-blurred",c)});b.Rb&&document.body.appendChild(d)}
function u(b,a,c){p(b,a,d=>{const e=v(b,d.elementId);return c(e,d)})}function v(b,a){b=b.tb.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Lc}function da(b,a,c,d){d||(d={});d.elementId=c;l(b,a,d)}function w(b,a,c,d){d||(d={});d.elementId=c;n(b,a,d)}
window.qd=class extends self.Na{constructor(b,a){super(b,a);this.tb=new Map;this.Rb=!0;r(this,[["create",c=>ca(this,c)],["destroy",c=>{c=c.elementId;const d=v(this,c);this.Rb&&d.parentElement.removeChild(d);this.tb.delete(c)}],["set-visible",c=>{if(this.Rb){var d=this.tb.get(c.elementId),e=d.Lc;d.Qc?e.style.display=c.isVisible?"":"none":d.Xc=!!c.isVisible}}],["update-position",c=>{if(this.Rb){var d=this.tb.get(c.elementId),e=d.Lc;e.style.left=c.left+"px";e.style.top=c.top+"px";e.style.width=c.width+
"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.Qc||(d.Qc=!0,d.Xc&&(e.style.display=""))}}],["update-state",c=>{const d=v(this,c.elementId);this.Lb(d,c)}],["focus",c=>{const d=v(this,c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=v(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{v(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{v(this,c.elementId).removeAttribute(c.name)}]]);
u(this,"get-element",c=>c)}pc(){throw Error("required override");}Lb(){throw Error("required override");}};"use strict";const ea=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),fa=/android/i.test(navigator.userAgent),ha=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ia=0;
function ja(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.jf?new Promise(c=>{const d="c3_resolve_"+ia;++ia;self[d]=c;a.textContent=b.nf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ka=!1,la=!1;function ma(){if(!ka){try{new Worker("blob://",{get type(){la=!0}})}catch(b){}ka=!0}return la}let x=new Audio;
const na={"audio/webm; codecs=opus":!!x.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!x.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!x.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!x.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!x.canPlayType("audio/mp4"),"audio/mpeg":!!x.canPlayType("audio/mpeg")};x=null;async function oa(b){b=await pa(b);return(new TextDecoder("utf-8")).decode(b)}
function pa(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const qa=[];let y=0;window.RealFile=window.File;const A=[],ra=new Map,sa=new Map;let ta=0;const wa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");wa.push(b)};const xa=new Set(["cordova","playable-ad","instant-games"]);let za=!1;
window.ya=class b{constructor(a){this.da=a.qf;this.Aa=null;this.ca="";this.cb=a.mf;this.Gb={};this.Wa=this.xa=null;this.Tb=[];this.I=this.qa=null;this.Uc=!1;this.Kd=0;this.wb=null;this.bb=-1;this.ef=()=>this.Se();this.ab=[];this.jd=null;this.de=[];this.A=a.ee;this.Wb="file"===location.protocol.substr(0,4);!this.da||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ma()||(this.da=!1);this.da&&ha&&(this.da=!1);if("playable-ad"===this.A||"instant-games"===this.A)this.da=!1;if("cordova"===
this.A&&this.da)if(fa){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.da=!1)}else this.da=!1;this.kb()?self.chrome.webview.addEventListener("message",c=>this.Ad(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.Ad(c));this.Zb=this.ua=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");
this.C("runtime","cordova-fetch-local-file",c=>this.Oe(c));this.C("runtime","create-job-worker",()=>this.Pe());this.C("runtime","send-wrapper-extension-message",c=>this.Ve(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.yd(a)):this.yd(a)}j(){this.zc();this.Aa&&(this.Aa=this.Aa.onmessage=null);this.xa&&(this.xa.terminate(),this.xa=null);this.Wa&&(this.Wa.j(),this.Wa=null);this.I&&(this.I.parentElement.removeChild(this.I),this.I=null)}ze(){return ea&&"cordova"===this.A}vc(){const a=
navigator.userAgent;return ea&&xa.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}xe(){return fa}sd(){return fa&&xa.has(this.A)}kb(){return"windows-webview2"===this.A||!!("preview"===this.A&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}async yd(a){"macos-wkwebview"===this.A?this.nb({type:"ready"}):this.kb()&&(this.Ye(),this.de=(await this.Ne()).registeredComponentIds);if("playable-ad"===this.A){this.ua=self.c3_base64files;this.Zb={};await this.Ge();
for(let d=0,e=a.fb.length;d<e;++d){var c=a.fb[d];this.Zb.hasOwnProperty(c)?a.fb[d]={jf:!0,nf:this.Zb[c]}:this.ua.hasOwnProperty(c)&&(a.fb[d]=URL.createObjectURL(this.ua[c]))}a.nc=[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.vd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.lf?this.ca=a.lf:(c=location.origin,this.ca=("null"===c?"file:///":c)+location.pathname,c=this.ca.lastIndexOf("/"),-1!==c&&(this.ca=this.ca.substr(0,c+1)));a.sf&&(this.Gb=a.sf);
c=new MessageChannel;this.Aa=c.port1;this.Aa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Re(d));this.wb=new self.Ae(this);await Aa(this.wb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.da?await this.Me(a,c.port2):
await this.Le(a,c.port2)}Bc(a){a=this.Gb.hasOwnProperty(a)?this.Gb[a]:a.endsWith("/workermain.js")&&this.Gb.hasOwnProperty("workermain.js")?this.Gb["workermain.js"]:"playable-ad"===this.A&&this.ua.hasOwnProperty(a)?this.ua[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async qc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Wb)return a=await this.Hb(d.hf?a:this.cb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=
new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}sa(){return Math.max(window.innerWidth,1)}ja(){return Math.max(window.innerHeight,1)}xd(a){var c=this.ca,d=location.href,e=this.sa(),f=this.ja(),g=window.devicePixelRatio,h=b.jb(),k=a.xf,m=window.cr_previewImageBlobs||this.ua,q=window.cr_previewProjectFileBlobs,C=window.cr_previewProjectFiles,z=window.cr_swClientId||
"";a=a.ee;var t=(new URLSearchParams(self.location.search)).has("debug"),D=this.wb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:m,previewProjectFileBlobs:q,previewProjectFileSWUrls:C,swClientId:z,exportType:a,isDebug:t,ife:!!self.wf,jobScheduler:{inputPort:D.Tc,outputPort:D.bd,maxNumWorkers:D.bf},supportedAudioFormats:na,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.cb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.cb+"opus.wasm.wasm",isFileProtocol:this.Wb,isiOSCordova:this.ze(),isiOSWebView:this.vc(),isWebView2Wrapper:this.kb(),wrapperComponentIds:this.de,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Me(a,c){const d=this.Bc(a.rf);"preview"===this.A?(this.xa=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,k)=>{const m=q=>{this.xa.removeEventListener("message",m);q.data&&"ok"===q.data.type?h():k()};this.xa.addEventListener("message",m);this.xa.postMessage({type:"construct-worker-init",
"import":(new URL(d,this.ca)).toString()})})):this.xa=await this.qc(d,this.ca,{type:"module",name:"Runtime",hf:!0});this.I=document.createElement("canvas");this.I.style.display="none";const e=this.I.transferControlToOffscreen();document.body.appendChild(this.I);window.c3canvas=this.I;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.nc||[],g=a.fb;f=await Promise.all(f.map(h=>this.Ra(h)));g=await Promise.all(g.map(h=>this.Ra(h)));if("cordova"===this.A)for(let h=0,k=a.mc.length;h<
k;++h){const m=a.mc[h],q=m[0];if(q===a.kd||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))m[1]=await this.Ra(q)}this.xa.postMessage(Object.assign(this.xd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.mc,mainProjectScript:a.kd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...Ba(this.wb)]);this.Tb=A.map(h=>new h(this));this.wd();Ca(this.qa);self.c3_callFunction=(h,k)=>{var m=this.qa;return m.v.ud(m.qb,
"js-invoke-function",{name:h,params:k})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.mb("runtime","go-to-last-error-script"))}async Le(a,c){this.I=document.createElement("canvas");this.I.style.display="none";document.body.appendChild(this.I);window.c3canvas=this.I;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Tb=A.map(g=>new g(this));this.wd();var d=a.fb.map(g=>"string"===typeof g?(new URL(g,this.ca)).toString():g);if(Array.isArray(a.nc)){var e=[...a.nc].map(g=>
g instanceof Blob?URL.createObjectURL(g):g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.Ra(g)));await Promise.all(d.map(g=>ja(g)));d=self.C3_ProjectScriptsStatus;e=a.kd;const f=a.mc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Ra(h),await ja(h),"preview"!==this.A||d[g]||this.Bd(g,"main script did not run to completion")}catch(k){this.Bd(g,k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Ra(h),await ja(h);"preview"===this.A&&"object"!==typeof self.tf.vf?
(this.Nb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.xd(a),{isInWorker:!1,messagePort:c,canvas:this.I,runOnStartupFunctions:wa}),Ca(this.qa),this.zd(),this.Wa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Wa,a))}Bd(a,c){this.Nb();console.error(`[Preview] Failed to load project main script (${a}): `,
c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}zd(){this.Nb()}Nb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Pe(){const a=await Da(this.wb);return{outputPort:a,transferables:[a]}}Ke(){if(this.da)throw Error("not available in worker mode");return this.Wa}mb(a,c,d,e,f){this.Aa.postMessage({type:"event",component:a,handler:c,
dispatchOpts:e||null,data:d,responseId:null},f)}ud(a,c,d,e,f){const g=ta++,h=new Promise((k,m)=>{sa.set(g,{resolve:k,reject:m})});this.Aa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Qe(a);if("result"===c)this.Te(a);else if("runtime-ready"===c)this.Ue();else if("alert-error"===c)this.Nb(),alert(a.message);else if("creating-runtime"===c)this.zd();else throw Error(`unknown message '${c}'`);
}Qe(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=ra.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Mb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Mb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Mb(f,!1,""+h)}):this.Mb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Mb(a,
c,d){let e;d&&d.transferables&&(e=d.transferables);this.Aa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Te(a){const c=a.responseId,d=a.isOk;a=a.result;const e=sa.get(c);d?e.resolve(a):e.reject(a);sa.delete(c)}C(a,c,d){let e=ra.get(a);e||(e=new Map,ra.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Da(a){if(A.includes(a))throw Error("DOM handler already added");A.push(a)}wd(){for(const a of this.Tb)if("runtime"===a.qb){this.qa=
a;return}throw Error("cannot find runtime DOM handler");}Re(a){this.mb("debugger","message",a)}Ue(){for(const a of this.Tb)a.md()}static jb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||za)}static Cd(a){za=!!a}vd(a){this.ab.push(a);this.Gc()}Xe(a){a=this.ab.indexOf(a);if(-1===a)throw Error("invalid callback");this.ab.splice(a,1);this.ab.length||this.zc()}Gc(){-1===this.bb&&this.ab.length&&(this.bb=requestAnimationFrame(this.ef))}zc(){-1!==
this.bb&&(cancelAnimationFrame(this.bb),this.bb=-1)}Se(){this.bb=-1;for(const a of this.ab)a();this.Gc()}Ga(a){this.qa.Ga(a)}Pa(a){this.qa.Pa(a)}Fc(){this.qa.Fc()}Kb(a){this.qa.Kb(a)}ye(){return!!na["audio/webm; codecs=opus"]}async Ze(a){a=await this.ud("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Ce(a){this.Uc=!0;this.Kd=a}we(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}td(a){return!this.we(a)}async Ra(a){return"cordova"===
this.A&&(a.startsWith("file:")||this.Wb&&this.td(a))?(a.startsWith(this.ca)&&(a=a.substr(this.ca.length)),a=await this.Hb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Oe(a){const c=a.filename;switch(a.as){case "text":return await this.ve(c);case "buffer":return await this.Hb(c);default:throw Error("unsupported type");}}pd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ve(a){a=
await this.pd(a);return await oa(a)}Ac(){if(qa.length&&!(8<=y)){y++;var a=qa.shift();this.He(a.filename,a.pf,a.gf)}}Hb(a){return new Promise((c,d)=>{qa.push({filename:a,pf:e=>{y--;this.Ac();c(e)},gf:e=>{y--;this.Ac();d(e)}});this.Ac()})}async He(a,c,d){try{const e=await this.pd(a),f=await pa(e);c(f)}catch(e){d(e)}}Ad(a){if("entered-fullscreen"===a)b.Cd(!0),B(this.qa);else if("exited-fullscreen"===a)b.Cd(!1),B(this.qa);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.jd(a),
this.jd=null):"extension-message"===c?this.mb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Ve(a){this.nb({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}nb(a){this.kb()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Ye(){window.moveTo=(a,c)=>
{this.nb({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.nb({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Ne(){return this.kb()?new Promise(a=>{this.jd=a;this.nb({type:"wrapper-init"})}):Promise.resolve()}async Ge(){const a=[];for(const [c,d]of Object.entries(this.ua))a.push(this.Fe(c,d));await Promise.all(a)}async Fe(a,c){if("object"===typeof c)this.ua[a]=new Blob([c.str],{type:c.type}),this.Zb[a]=c.str;else{let d=
await this.Je(c);d||(d=this.Ie(c));this.ua[a]=d}}async Je(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Ie(a){a=this.We(a);return this.Ee(a.data,a.kf)}We(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,
c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{kf:a,data:d}}Ee(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const E=self.ya;
function Ea(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const Fa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),F={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ga={dispatchUserScriptEvent:!0},Ha={dispatchRuntimeEvent:!0};
function Ia(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ja(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function G(b){b=URL.createObjectURL(b);try{return await Ja(b)}finally{URL.revokeObjectURL(b)}}
function Ka(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function La(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await G(b);var d=await Ka(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await G(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await G(b)}
function Ma(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Oa=new Set(["input","textarea","datalist","select"]),Pa=new Set(["canvas","body","html"]);function I(b){b.target.tagName&&Pa.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Qa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await G(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await La(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ra=!1;document.addEventListener("pause",()=>Ra=!0);document.addEventListener("resume",()=>Ra=!1);function Ca(b){b.Jd=!0;b.Zc=b.v.sa();b.xb=b.v.ja()}function B(b){if(!b.aa){var a=E.jb();a&&"any"!==b.ed&&Sa(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.sa(),innerHeight:b.ja()})}}async function Ta(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ua(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Va(b){return await self.C3_GetSvgImageSize(b.blob)}function Wa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Xa(b){self.setTimeout(()=>{b.Id=!0},1E3);"cordova"===b.v.A?(document.addEventListener("pause",()=>Ya(b,!0)),document.addEventListener("resume",()=>Ya(b,!1))):document.addEventListener("visibilitychange",()=>Ya(b,"hidden"===document.visibilityState));b.cc=!("hidden"!==document.visibilityState&&!Ra);return{isSuspended:b.cc}}
function Za(b){b.Ed||(b.Ed=!0,window.addEventListener("deviceorientation",a=>{b.aa||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},F)}),window.addEventListener("deviceorientationabsolute",a=>{b.aa||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},F)}))}
function $a(b){b.Dd||(b.Dd=!0,window.addEventListener("devicemotion",a=>{if(!b.aa){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},F)}}))}async function ab(b){await Ia(b.url)}
function bb(b,a){b.Ld=a.message;-1===b.Mc&&(b.Mc=setTimeout(()=>{b.Mc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Ld)},250))}function cb(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:E.jb(),innerWidth:b.sa(),innerHeight:b.ja()})}function Ya(b,a){b.cc!==a&&((b.cc=a)?b.v.zc():b.v.Gc(),l(b,"visibilitychange",{hidden:a}))}
function db(b,a,c){"Backspace"===c.key&&I(c);if(!b.aa){var d=Fa.get(c.code)||c.code;n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},F)}}function eb(b,a,c,d){b.aa||Ea(c)||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.ea,pageX:c.pageX,pageY:c.pageY+b.ea,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function fb(b){window!==window.top&&window.focus();hb(b.target)&&document.activeElement&&!hb(document.activeElement)&&document.activeElement.blur()}
function J(b,a,c){if(!b.aa){var d=0;"mouse"===c.pointerType&&(d=b.Bb);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.ea,pageX:c.pageX,pageY:c.pageY+b.ea,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},F);"mouse"===c.pointerType&&
(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),eb(b,d,c,Ga),b.Bb=c.buttons)}}
function ib(b,a,c){if(!b.aa&&!Ea(c)){var d=b.Bb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");n(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.ea,pageX:c.pageX,pageY:c.pageY+b.ea,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},F);b.Bb=c.buttons;eb(b,c.type,c,Ga)}}
function K(b,a,c){if(!b.aa)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];n(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.ea,pageX:f.pageX,pageY:f.pageY+b.ea,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
F)}}function jb(b,a,c){document.body.style.transform="";b.ea=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.ea=a))}}function kb(b,a,c,d){const e=b.sa(),f=b.ja();b.eb=-1;e!=a||f!=c?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:E.jb()}):10>d&&lb(b,e,f,d+1)}
function lb(b,a,c,d){-1!==b.eb&&clearTimeout(b.eb);b.eb=setTimeout(()=>kb(b,a,c,d),48)}
function Sa(b){b=b.ed;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function hb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
E.Da(class extends self.Na{constructor(b){super(b,"runtime");this.Qd=!0;this.Jd=!1;this.eb=-1;this.ed="any";this.cc=this.Dd=this.Ed=!1;this.jc=document.createElement("div");this.jc.className="c3-screen-reader-text";this.jc.setAttribute("aria-live","polite");document.body.appendChild(this.jc);this.Ja=null;this.aa=!1;this.Ld="";this.Mc=-1;this.Id=!1;this.Zc=b.sa();this.xb=b.ja();this.ea=this.Fb=0;b.C("canvas","update-size",d=>{var e=this.v;e.Uc||(e=e.I,e.style.width=d.styleWidth+"px",e.style.height=
d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Qd&&(e.style.display="",this.Qd=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Ta(d));b.C("runtime","raster-svg-image",d=>Ua(d));b.C("runtime",
"get-svg-image-size",d=>Va(d));b.C("runtime","set-target-orientation",d=>{this.ed=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Wa(d));b.C("runtime","go-to-script",d=>Wa(d));b.C("runtime","before-start-ticking",()=>Xa(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ja||(this.Ja=document.createElement("div"),this.Ja.id="inspectOutline",document.body.appendChild(this.Ja));var e=this.Ja;e.style.display=
"";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ja&&(this.Ja.style.display="none")});b.C("runtime","enable-device-orientation",()=>Za(this));b.C("runtime","enable-device-motion",()=>$a(this));b.C("runtime","add-stylesheet",d=>ab(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>{alert(d.message)});
b.C("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.jc.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.aa=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.I.style.display="";this.v.Ce(d.duration)});b.C("runtime","export-to-video-progress",d=>bb(this,d));b.C("runtime","exported-to-video",d=>{window.ff({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.ff({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ma(e)||d.preventDefault()});const c=b.I;window.addEventListener("selectstart",I);window.addEventListener("gesturehold",I);c.addEventListener("selectstart",I);c.addEventListener("gesturehold",
I);window.addEventListener("touchstart",I,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",I,{passive:!1}),c.addEventListener("pointerdown",I)):c.addEventListener("touchstart",I);this.Bb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Qa,{passive:!1});window.addEventListener("wheel",Qa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.aa&&this.Jd){var d=this.sa();var e=this.ja();if(this.v.sd()){if(this.Id){if(this.Zc===
d&&e<this.xb){this.Fb=this.xb-e;jb(this,this.xb,this.Fb);d=void 0;break a}0<this.Fb&&(this.Fb=0,jb(this,e,this.Fb))}this.Zc=d;this.xb=e}l(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:E.jb()});this.v.vc()&&(-1!==this.eb&&clearTimeout(this.eb),kb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>B(this));window.addEventListener("webkitfullscreenchange",()=>B(this));window.addEventListener("mozfullscreenchange",()=>
B(this));window.addEventListener("fullscreenerror",d=>cb(this,d));window.addEventListener("webkitfullscreenerror",d=>cb(this,d));window.addEventListener("mozfullscreenerror",d=>cb(this,d));if(b.vc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ma(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});this.Xa=new Set;this.ac=new WeakSet;this.za=!1}md(){window.addEventListener("focus",()=>{l(this,"window-focus",null,Ha)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}l(this,"window-blur",{parentHasFocus:a},Ha);this.Bb=0});window.addEventListener("focusin",a=>{a=a.target;(Oa.has(a.tagName.toLowerCase())||Ma(a))&&
l(this,"keyboard-blur",null,Ha)});window.addEventListener("keydown",a=>db(this,"keydown",a));window.addEventListener("keyup",a=>db(this,"keyup",a));window.addEventListener("dblclick",a=>eb(this,"dblclick",a,F));window.addEventListener("wheel",a=>{this.aa||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.ea,pageX:a.pageX,pageY:a.pageY+this.ea,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},F)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{fb(a);J(this,"pointerdown",a)}),this.v.da&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{J(this,"pointermove",a)}):window.addEventListener("pointermove",a=>J(this,"pointermove",a)),window.addEventListener("pointerup",a=>J(this,"pointerup",a)),window.addEventListener("pointercancel",a=>J(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{fb(a);ib(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>ib(this,
"pointermove",a)),window.addEventListener("mouseup",a=>ib(this,"pointerup",a)),window.addEventListener("touchstart",a=>{fb(a);K(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>K(this,"pointermove",a)),window.addEventListener("touchend",a=>K(this,"pointerup",a)),window.addEventListener("touchcancel",a=>K(this,"pointercancel",a)));const b=()=>this.Fc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.xe()&&!this.v.sd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{jb(this,this.ja(),navigator.virtualKeyboard.boundingRect.height)}))}sa(){return this.v.sa()}ja(){return this.v.ja()}Fc(){var b=[...this.Xa];this.Xa.clear();if(!this.za)for(const a of b)(b=a.play())&&b.catch(()=>{this.ac.has(a)||this.Xa.add(a)})}Ga(b){if("function"!==typeof b.play)throw Error("missing play function");
this.ac.delete(b);let a;try{a=b.play()}catch(c){this.Xa.add(b);return}a&&a.catch(()=>{this.ac.has(b)||this.Xa.add(b)})}Pa(b){this.Xa.delete(b);this.ac.add(b)}Kb(b){this.za=!!b}});"use strict";async function Aa(b){if(b.$e)throw Error("already initialised");b.$e=!0;var a=b.Ba.Bc(("playable-ad"===b.Ba.A?b.Ba.cb:"")+"dispatchworker.js");b.Kc=await b.Ba.qc(a,b.pb,{name:"DispatchWorker"});a=new MessageChannel;b.Tc=a.port1;b.Kc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.bd=await Da(b)}
function Ba(b){return[b.Tc,b.bd]}async function Da(b){const a=b.Rd.length;var c=b.Ba.Bc(("playable-ad"===b.Ba.A?b.Ba.cb:"")+"jobworker.js");c=await b.Ba.qc(c,b.pb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Kc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Rd.push(c);return e.port1}
self.Ae=class{constructor(b){this.Ba=b;this.pb=b.ca;this.pb="preview"===b.A?this.pb+"workers/":this.pb+b.cb;this.bf=Math.min(navigator.hardwareConcurrency||2,16);this.Kc=null;this.Rd=[];this.bd=this.Tc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ya({qf:!0,rf:"workermain.js",fb:["scripts/c3runtime.js"],mc:[],kd:"",mf:"scripts/",nc:[],ee:"html5"}));"use strict";
self.ya.Da(class extends self.Na{constructor(b){super(b,"mouse");r(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.v.I.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{l(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{l(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function mb(b,a){a=a.type;let c=!0;0===a?c=await nb():1===a&&(c=await ob());l(b,"permission-result",{type:a,result:c})}async function nb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function ob(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.ya.Da(class extends self.Na{constructor(b){super(b,"touch");p(this,"request-permission",a=>mb(this,a))}});"use strict";function L(b){b.stopPropagation()}function pb(b){13!==b.which&&27!==b.which&&b.stopPropagation()}
self.ya.Da(class extends self.qd{constructor(b){super(b,"text-input");u(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}pc(b,a){let c;const d=a.type;"textarea"===d?(c=document.createElement("textarea"),c.style.resize="none"):(c=document.createElement("input"),c.type=d);c.style.position="absolute";c.autocomplete="off";c.addEventListener("pointerdown",L);c.addEventListener("pointermove",L);c.addEventListener("pointerrawupdate",L);c.addEventListener("pointerup",L);c.addEventListener("mousedown",
L);c.addEventListener("mouseup",L);c.addEventListener("keydown",pb);c.addEventListener("keyup",pb);c.addEventListener("click",e=>{e.stopPropagation();w(this,"click",b)});c.addEventListener("dblclick",e=>{e.stopPropagation();w(this,"dblclick",b)});c.addEventListener("input",()=>da(this,"change",b,{text:c.value}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.Lb(c,a);return c}Lb(b,a){b.value=a.text;b.placeholder=a.placeholder;b.title=a.title;b.disabled=!a.isEnabled;b.readOnly=a.isReadOnly;
b.spellcheck=a.spellCheck;a=a.maxLength;0>a?b.removeAttribute("maxlength"):b.setAttribute("maxlength",a)}});"use strict";function qb(b){b.replaceChildren?b.replaceChildren():b.innerHTML=""}
function M(b){b=Array.from(b.querySelectorAll("script:not([c3-executed])"));for(const c of b){b=c.parentNode;var a=b.replaceChild;const d=document.createElement("script");d.text=c.text;const e=c.attributes;for(let f=0,g=e.length;f<g;++f){const h=e[f];d.setAttribute(h.name,h.value)}d.setAttribute("c3-executed","");a.call(b,d,c)}}function N(b,a,c){return a?c?Array.from(b.querySelectorAll(a)):(b=b.querySelector(a))?[b]:[]:[b]}
function O(b){return b?{isOk:!0,html:b.innerHTML,text:b.textContent}:{isOk:!1}}
self.ya.Da(class extends self.qd{constructor(b){super(b,"html-element");u(this,"set-content",(a,c)=>{{const e=c.str,f=c.type,g=c.selector;c=c["is-all"];try{const h=N(a,g,c);if(0===h.length)var d=O(null);else{for(const k of h)"html"===f?(k.innerHTML=e,M(k)):k.textContent=e;d=O(a)}}catch(h){console.warn("[HTML element] Failed to set content: ",h),d=O(null)}}return d});u(this,"insert-content",(a,c)=>{{const e=c.str,f=c.type,g=c["at-end"]?"beforeend":"afterbegin",h=c.selector;c=c["is-all"];try{const k=
N(a,h,c);if(0===k.length)var d=O(null);else{for(const m of k)"html"===f?(m.insertAdjacentHTML(g,e),M(m)):m.insertAdjacentText(g,e);d=O(a)}}catch(k){console.warn("[HTML element] Failed to insert content: ",k),d=O(null)}}return d});u(this,"remove-content",(a,c)=>{{const e=c["is-clear"],f=c.selector;c=c["is-all"];if(f)try{const g=N(a,f,c);if(0===g.length)var d=O(null);else{for(const h of g)e?qb(h):h.remove();d=O(a)}}catch(g){console.warn("[HTML element] Failed to remove content: ",g),d=O(null)}else qb(a),
d=O(a)}return d});u(this,"set-content-class",(a,c)=>{{const e=c.mode,f=c["class-array"],g=c.selector;c=c["is-all"];try{const h=N(a,g,c);if(0===h.length)var d=O(null);else{for(const k of h)for(const m of f)switch(e){case "add":k.classList.add(m);break;case "toggle":k.classList.toggle(m);break;case "remove":k.classList.remove(m)}d=O(a)}}catch(h){console.warn("[HTML element] Failed to set class: ",h),d=O(null)}}return d});u(this,"set-content-attribute",(a,c)=>{{const e=c.mode,f=c.attribute,g=c.value,
h=c.selector;c=c["is-all"];try{const k=N(a,h,c);if(0===k.length)var d=O(null);else{for(const m of k)switch(e){case "set":m.setAttribute(f,g);break;case "remove":m.removeAttribute(f)}d=O(a)}}catch(k){console.warn("[HTML element] Failed to set attribute: ",k),d=O(null)}}return d});u(this,"set-content-css-style",(a,c)=>{{const e=c.prop,f=c.value,g=c.selector;c=c["is-all"];try{const h=N(a,g,c);if(0===h.length)var d=O(null);else{for(const k of h)e.startsWith("--")?k.style.setProperty(e,f):k.style[e]=f;
d=O(a)}}catch(h){console.warn("[HTML element] Failed to set style: ",h),d=O(null)}}return d});u(this,"get-element-box",(a,c)=>{(a=(c=c.selector)?a.querySelector(c):a)?(a=a.getBoundingClientRect(),a={isOk:!0,left:a.left,top:a.top,right:a.right,bottom:a.bottom}):a={isOk:!1};return a});u(this,"insert-img-element",(a,c)=>{a:{const e=c.blobUrl;var d=c.width;const f=c.height,g=c.selector,h=c.insertAt;let k=a;if(g&&(k=a.querySelector(g),!k)){a={isOk:!1};break a}d=new Image(d,f);d.src=e;c.id&&(d.id=c.id);
c["class"]&&(d.className=c["class"]);0===h?k.prepend(d):1===h?k.append(d):k.replaceChildren?k.replaceChildren(d):(qb(k),k.append(d));a=O(a)}return a});u(this,"set-scroll-position",(a,c)=>{a:{const d=c.selector,e=c.direction;c=c.position;if(d&&(a=a.querySelector(d),!a)){c=void 0;break a}"left"===e?a.scrollLeft=c:a.scrollTop=c;c=void 0}return c})}pc(b,a){const c=document.createElement(a.tag);a["style-attribute"]&&c.setAttribute("style",a["style-attribute"]);c.style.position="absolute";var d=a["stop-input-events-mode"];
if(0<d){let e=null;1===d?e=f=>{f.target!==c&&f.stopPropagation()}:2===d&&(e=f=>f.stopPropagation());c.addEventListener("pointerdown",e);c.addEventListener("pointermove",e);c.addEventListener("pointerrawupdate",e);c.addEventListener("pointerup",e);c.addEventListener("mousedown",e);c.addEventListener("mouseup",e);c.addEventListener("dblclick",e)}a["allow-context-menu"]&&c.addEventListener("contextmenu",e=>e.stopPropagation());c.addEventListener("click",e=>{e=e.target;const f=[];for(;e;){f.push({targetId:"string"===
typeof e.id?e.id:"",targetClass:"string"===typeof e.className?e.className:""});if(e===c)break;e=e.parentNode}w(this,"click",b,{chain:f})});c.addEventListener("animationend",e=>{const f=e.target;w(this,"animationend",b,{targetId:"string"===typeof f.id?f.id:"",targetClass:"string"===typeof f.className?f.className:"",animationName:e.animationName})});a.id&&(c.id=a.id);a.className&&(c.className=a.className);a["css-color"]&&(c.style.color=a["css-color"]);a["css-background-color"]&&(c.style.backgroundColor=
a["css-background-color"]);a["allow-text-selection"]||(c.style.userSelect="none",c.style.webkitUserSelect="none");d=a.str;"html"===a.type?(c.innerHTML=d,M(c)):c.textContent=d;w(this,"initial-content",b,{html:c.innerHTML,text:c.textContent});return c}Lb(b,a){b.innerHTML=a.html;M(b)}});"use strict";
function rb(b){b.X=window.FB;let a=location.pathname;"/"!==a.substr(a.length-1)&&(a=a.substr(0,a.lastIndexOf("/")+1));b.X.init({version:"v3.0",appId:b.Qb,status:!0,cookie:!0,xfbml:!1});b.X.Event.subscribe("auth.login",c=>sb(b,c));b.X.Event.subscribe("auth.logout",()=>{b.na=!1;b.Hc="";b.Oc="";b.Nc="";b.Yc="";l(b,"logout")});b.X.getLoginStatus(c=>sb(b,c));b.oa&&(b.oa(),b.oa=null)}
async function tb(b,a){b.Qb=a.appId;if(!b.Qb)return console.log("[Facebook] No App ID provided. Please enter an App ID before using the object."),!1;try{return await ub(b),!0}catch(c){return console.error("[Facebook] Error loading Facebook API: ",c),!1}}function vb(b,a){b.na||b.X.login(c=>sb(b,c),{scope:a.permissions})}function wb(b){b.na&&b.X.logout(()=>{})}function xb(b){b.na&&b.X.ui({method:"feed"},a=>{a&&a.error&&console.error("[Facebook] Error prompting wall post: ",a.error)})}
function yb(b){b.na&&b.X.ui({method:"feed",link:"https://apps.facebook.com/"+b.Qb+"/"},a=>{a&&a.error&&console.error("[Facebook] Error prompting to share app: ",a.error)})}function zb(b,a){b.na&&b.X.ui({method:"feed",link:a.url},c=>{c&&c.error&&console.error("[Facebook] Error prompting to share link: ",c.error)})}function Ab(b,a){b.na&&b.X.api("/me/feed","POST",{method:"stream.publish",message:a.message},c=>{c&&c.error&&console.error("[Facebook] Error publishing to wall: ",c.error)})}
function Bb(b,a){if(b.na){var c={method:"stream.publish",message:a.message,link:a.url,name:a.name,caption:a.caption,description:a.description};a.picture&&(c.picture=a.picture);b.X.api("/me/feed","POST",c,d=>{d&&d.error&&console.error("[Facebook] Error publishing link: ",d.error)})}}
function ub(b){return new Promise((a,c)=>{document.getElementById("facebook-jssdk")?a():(b.oa=a,a=document.createElement("script"),a.id="facebook-jssdk",a.onerror=c,a.async=!0,a.src="//connect.facebook.net/en_US/sdk.js",document.getElementsByTagName("head")[0].appendChild(a))})}
function sb(b,a){a.authResponse&&!b.na&&(b.na=!0,b.hd=a.authResponse.userID,console.log("[Facebook] Logged in as user ID: "+b.hd),b.Hc=a.authResponse.accessToken,l(b,"login",{userId:b.hd,accessToken:b.Hc}),b.X.api("/me?fields=name,first_name,last_name",c=>{b.Oc=c.name;b.Nc=c.first_name;b.Yc=c.last_name;l(b,"name-available",{fullName:b.Oc,firstName:b.Nc,lastName:b.Yc})}))}
self.ya.Da(class extends self.Na{constructor(b){super(b,"facebook");this.X=null;this.Qb="";this.na=!1;this.Yc=this.Nc=this.Oc=this.Hc=this.hd="";this.oa=null;window.fbAsyncInit=()=>rb(this);r(this,[["load",a=>tb(this,a)],["login",a=>vb(this,a)],["logout",()=>wb(this)],["prompt-wall-post",()=>xb(this)],["prompt-share-app",()=>yb(this)],["prompt-share-link",a=>zb(this,a)],["publish-to-wall",a=>Ab(this,a)],["publish-link",a=>Bb(this,a)],["on-cta-click",()=>{self.FbPlayableAd&&self.FbPlayableAd.onCTAClick?
(console.log("[Facebook] CTA clicked: calling FbPlayableAd.onCTAClick()"),self.FbPlayableAd.onCTAClick()):console.warn("[Facebook] CTA clicked: FbPlayableAd.onCTAClick() function not available - check running as a Playable Ad")}]])}});"use strict";const Cb=180/Math.PI;
async function Db(b,a){if(a.isiOSCordova||a.isSafari)b.ec=!0;b.fd=a.timeScaleMode;b.Wd=["equalpower","HRTF","soundfield"][a.panningModel];b.Hd=["linear","inverse","exponential"][a.distanceModel];b.Xd=a.refDistance;b.Vd=a.maxDistance;b.Zd=a.rolloffFactor;if(b.v.Uc)b.ec=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.Kd)});else{var c={latencyHint:a.latencyHint};b.be||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");Eb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&Eb(b);l(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ta=b.g.createGain();b.Ta.connect(b.g.destination);c=a.listenerPos;b.ba[0]=c[0];b.ba[1]=c[1];b.ba[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.fa);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function Fb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,m=a.pos,q=a.panning,C=a.stereoPan;let z=a.off;0<z&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),z=z-a.performanceTime/1E3+a.contextTime):z=z-performance.now()/1E3+b.g.currentTime);b.Sd=g.slice(0);Gb(b,g);try{b.R=await Hb(b,c,d,e,g,f);if(q){Q(b.R,!0);var t=b.R,D=q.innerAngle,ua=q.outerAngle,va=q.outerGain;if(t.vb){Ib(t,q.x,q.y,q.z,q.angle);var H=self.gb.De;t.va[0]!==H(D)&&
(t.va[0]=H(D),t.F.coneInnerAngle=H(D));t.va[1]!==H(ua)&&(t.va[1]=H(ua),t.F.coneOuterAngle=H(ua));t.va[2]!==va&&(t.va[2]=va,t.F.coneOuterGain=va)}q.hasOwnProperty("uid")&&(b.R.ta=q.uid)}else"number"===typeof C&&0!==C?(R(b.R,!0),Jb(b.R,C)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,k,m,z)}catch(Vb){console.error("[Construct] Audio: error starting playback: ",Vb);return}finally{c=g.join(" ");d=b.Db.get(c);if(!d)throw Error("expected pending tag");d.ld--;0===d.ld&&(d.resolve(),b.Db.delete(c))}aa(b)}
async function Kb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await Lb(b,c);for(const h of S(b,c))if(!h.Va){c=h.G.gain;c.cancelScheduledValues(0);var f=h.s.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ma=d;h.Ua=g;h.ae=a}T(b)}async function Mb(b,a){const c=a.tags;a=a.rate;await Lb(b,c);for(const d of S(b,c))d.pa!==a&&(d.pa=a,d.Ha())}async function Nb(b,a){const c=a.tags;a=a.pos;await Lb(b,c);for(const d of S(b,c))d.wc(a)}
async function Ob(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await Hb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function Pb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.la.indexOf(a),-1!==a&&b.la.splice(a,1)}
async function Qb(b,a){const c=a.type;var d=a.tags;const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.ke(b,...e);else if("delay"===c)d=new self.ie(b,...e);else if("convolution"===c){var g=d=new self.he(b,f.ka,...e),h=a.bufferType;g.Fd=a.bufferOriginalUrl;g.Gd=h}else if("flanger"===c)d=new self.le(b,...e);else if("phaser"===
c)d=new self.ne(b,...e);else if("gain"===c)d=new self.me(b,...e);else if("stereopan"===c)d=new self.pe(b,...e);else if("tremolo"===c)d=new self.qe(b,...e);else if("ringmod"===c)d=new self.oe(b,...e);else if("distortion"===c)d=new self.je(b,...e);else if("compressor"===c)d=new self.ge(b,...e);else if("analyser"===c)d=new self.fe(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let m=g.ma.get(h);m||(m=[],g.ma.set(h,m));d.Pd=m.length;d.dd=h;m.push(d);Rb(g,h)}Sb(b)}
async function Tb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ea()&&1===c||!e.Ea()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ma.values())for(const g of f)g.j();b.ma.clear();b.kc=a.timeScale;b.Pc=a.gameTime;d=a.listenerPos;b.ba[0]=d[0];b.ba[1]=d[1];b.ba[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.fa[e]=d[e];b.g.listener.setOrientation(...b.fa)}b.za=a.isSilent;b.v.Kb(b.za);b.$b=a.masterVolume;b.Ta.gain.value=
b.$b;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>Qb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Ub(b,f,c)));T(b)}
async function Wb(b,a){try{const c=b.g.suspend(a.time);b.Od?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.mb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Xb(d)),b.Od=!0);await c}catch(c){Xb(c)}}
function Eb(b){b.Ub||(b.Sc=!1,window.addEventListener("pointerup",b.Ca,!0),window.addEventListener("touchend",b.Ca,!0),window.addEventListener("click",b.Ca,!0),window.addEventListener("keydown",b.Ca,!0),b.Ub=!0)}
async function P(b,a,c,d,e,f){for(var g of b.la)if(g.ib()===c)return await Yb(g),g;if(f)return null;if(e&&(b.ec||b.Nd)){f=0;for(let h=0,k=b.la.length;h<k;++h)g=b.la[h],b.la[f]=g,g.Ea()?g.j():++f;b.la.length=f}f="audio/webm; codecs=opus"===d&&!b.be;e&&f&&(b.Nd=!0);c=!e||b.ec||f?new self.te(b,a,c,d,e,f):new self.re(b,a,c,d,e);b.la.push(c);await Yb(c);b.Ud.has(a)||(l(b,"buffer-metadata",{originalUrl:a,duration:c.ia()}),b.Ud.add(a));return c}
function Zb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function $b(b,a){return(a=b.ma.get(a.toLowerCase()))?a[0].N():b.ha()}function Rb(b,a){a=a.toLowerCase();let c=b.ha();var d=b.ma.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ha()):e.U(d[f+1].N())}}for(const f of ac(b,a))d=c,e=f.ga||f.F||f.G,e.disconnect(),e.connect(d);b.Ka&&b.$c===a&&(b.Ka.disconnect(),b.Ka.connect(c))}
function*ac(b,a){if(a)for(const c of b.H)Zb(0<c.ra.length?c.ra[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function bc(b,a,c){return c?b.v.Ze(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function cc(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.ra;var c=a;for(const e of c){c=!1;for(const f of b)if(Zb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function Hb(b,a,c,d,e,f){for(const g of b.H)if(g.ib()===c&&(g.oc()||f))return g.ra=e,g;a=await P(b,a,c,d,f);e="html5"===a.Ic?new self.se(a.s,a,e):new self.ue(a.s,a,e);b.H.push(e);return e}
function Gb(b,a){a=a.join(" ");let c=b.Db.get(a);if(!c){let d=null;c={ld:0,promise:new Promise(e=>d=e),resolve:d};b.Db.set(a,c)}c.ld++}function Lb(b,a){return(b=b.Db.get((0===a.length?b.Sd:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Sa.size)aa(b);else for(const a of b.H)if(!a.J&&!a.O()){aa(b);break}}function dc(b,a,c,d){l(b,"trigger",{type:a,tags:c,aiid:d})}function Sb(b){b.Vc||(b.Vc=!0,Promise.resolve().then(()=>ec(b)))}
function ec(b){const a={};for(const [c,d]of b.ma)a[c]=d.map(e=>e.hb());l(b,"fxstate",{fxstate:a});b.Vc=!1}
async function Ub(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,m=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await Hb(b,d,e,f,h,g)}catch(C){console.error("[Construct] Audio: error loading audio state: ",C);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Za[0]=f[0],b.Za[1]=f[1],b.Za[2]=f[2],f=d.orient,b.Ya[0]=f[0],b.Ya[1]=f[1],b.Ya[2]=f[2],e.setPosition(...b.Za),e.setOrientation(...b.Ya),b.va[0]=d.cia,b.va[1]=d.coa,b.va[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.ta=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),Jb(b,d));c.Play(k,m,q,0);a.isPlaying||c.lb();c.Dc(a)}}}function Xb(b){console.error("[Audio] Offline rendering error: ",b)}
self.gb=class extends self.Na{constructor(b){super(b,"audio");this.Ta=this.g=null;this.Ub=this.Sc=!1;this.Ca=()=>{if(!this.Sc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Ub&&(this.Sc=!0,window.removeEventListener("pointerup",this.Ca,!0),window.removeEventListener("touchend",this.Ca,!0),window.removeEventListener("click",this.Ca,!0),window.removeEventListener("keydown",
this.Ca,!0),this.Ub=!1)}};this.la=[];this.H=[];this.R=null;this.Sd=[];this.Ud=new Set;this.Td=-1;this.Db=new Map;this.$b=1;this.za=!1;this.fd=0;this.kc=1;this.Pc=0;this.Wd="HRTF";this.Hd="inverse";this.Xd=600;this.Vd=1E4;this.Zd=1;this.ba=[0,0,0];this.fa=[0,0,-1,0,1,0];this.Nd=this.ec=!1;this.be=this.v.ye();this.ma=new Map;this.Sa=new Set;this.Od=this.Vc=!1;this.$c="";this.Ka=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ka&&this.Ka.disconnect();this.$c=c.toLowerCase();this.Ka=this.g.createMediaStreamSource(a);
this.Ka.connect($b(this,this.$c))};this.Sb=null;self.C3Audio_GetOutputStream=()=>{this.Sb||(this.Sb=this.g.createMediaStreamDestination(),this.Ta.connect(this.Sb));return this.Sb.stream};self.C3Audio_DOMInterface=this;r(this,[["create-audio-context",a=>Db(this,a)],["play",a=>Fb(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Fa()}],["stop-all",()=>{for(const a of this.H)a.Fa()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.lb():d.Jb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>Kb(this,a)],["set-master-volume",a=>{this.$b=a.vol;this.Ta.gain.value=this.$b}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))fc(d,a)}],["set-silent",a=>{this.za=a.isSilent;this.v.Kb(this.za);for(const c of this.H)c.Ob()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.xc(a)}],["set-playback-rate",a=>Mb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),Jb(d,a)}],["seek",a=>Nb(this,a)],["preload",a=>Ob(this,a)],["unload",a=>Pb(this,a)],["unload-all",()=>{for(const a of this.la)a.j();this.la.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.yc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>Qb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ma.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].$(e,
f,g,a);Sb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ma.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ma.delete(a);Rb(this,a)}}],["tick",a=>{this.kc=a.timeScale;this.Pc=a.gameTime;this.Td=a.tickCount;if(0!==this.fd)for(var c of this.H)c.Ha();!(c=a.listenerPos)||this.ba[0]===c[0]&&this.ba[1]===c[1]&&this.ba[2]===c[2]||(this.ba[0]=c[0],this.ba[1]=c[1],this.ba[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.fa[0]!==
c[0]||this.fa[1]!==c[1]||this.fa[2]!==c[2]||this.fa[3]!==c[3]||this.fa[4]!==c[4]||this.fa[5]!==c[5])){for(let d=0;6>d;++d)this.fa[d]=c[d];this.g.listener.setOrientation(...this.fa)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.ta===a&&Ib(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Tb(this,a)],["offline-render-audio",a=>Wb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ha(){return this.Ta}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ha()}Ib(){return this.za}Ga(b){this.v.Ga(b)}Pa(b){this.v.Pa(b)}Qa(){for(var b of this.Sa)b.Qa();
b=this.g.currentTime;for(var a of this.H)a.Qa(b);a=this.H.filter(c=>!c.J&&!c.O()).map(c=>c.hb());l(this,"state",{tickCount:this.Td,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Sa].map(c=>({tag:c.dd,index:c.Pd,peak:c.$a,rms:c.Yd,binCount:c.l.frequencyBinCount,freqBins:c.Md}))});0===a.length&&0===this.Sa.size&&this.Vb&&(this.v.Xe(this.ce),this.Vb=!1)}static De(b){return b*Cb}static rd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Be(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.ya.Da(self.gb);"use strict";function Yb(b){b.Yb||(b.Yb=b.Cc());return b.Yb}self.nd=class{constructor(b,a,c,d,e){this.s=b;this.df=a;this.La=c;this.T=d;this.af=e;this.Ic="";this.Yb=null}j(){this.Yb=this.s=null}Cc(){}V(){return this.s.V()}sc(){return this.df}ib(){return this.La}rc(){return this.T}Ea(){return this.af}ia(){}};"use strict";
self.re=class extends self.nd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Ic="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.yb=this.oa=null;this.M.addEventListener("canplaythrough",()=>!0);this.Cb=this.V().createGain();this.Ab=null;this.M.addEventListener("canplay",()=>{this.oa&&(this.oa(),this.yb=this.oa=null);!this.Ab&&this.M&&(this.Ab=this.V().createMediaElementSource(this.M),this.Ab.connect(this.Cb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.La}' error: `,f);this.yb&&(this.yb(f),this.yb=this.oa=null)})}j(){cc(this.s,this);this.Cb.disconnect();this.Cb=null;this.Ab.disconnect();this.Ab=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}Cc(){return new Promise((b,a)=>{this.oa=b;this.yb=a;this.M.src=this.La})}W(){return this.M}ia(){return this.M.duration}};"use strict";
async function gc(b){if(b.Ia)return b.Ia;var a=b.s.v;if("cordova"===a.A&&a.td(b.La)&&a.Wb)b.Ia=await a.Hb(b.La);else{a=await fetch(b.La);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ia=await a.arrayBuffer()}}async function hc(b){if(b.ka)return b.ka;b.ka=await bc(b.s,b.Ia,b.cf);b.Ia=null}
self.te=class extends self.nd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Ic="webaudio";this.ka=this.Ia=null;this.cf=!!f}j(){cc(this.s,this);this.ka=this.Ia=null;super.j()}async Cc(){try{await gc(this),await hc(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.La}': `,b)}}ia(){return this.ka?this.ka.duration:0}};"use strict";let ic=0;
function Q(b,a){a=!!a;b.vb!==a&&(b.vb=a,b.vb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.s.Wd,b.F.distanceModel=b.s.Hd,b.F.refDistance=b.s.Xd,b.F.maxDistance=b.s.Vd,b.F.rolloffFactor=b.s.Zd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ha())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ha())))}
function R(b,a){a=!!a;b.Xb!==a&&(b.Xb=a,b.Xb?(Q(b,!1),b.ga=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ga),b.ga.connect(b.ha())):(b.ga.disconnect(),b.ga=null,b.G.disconnect(),b.G.connect(b.ha())))}function Jb(b,a){b.Xb&&b.cd!==a&&(b.ga.pan.value=a,b.cd=a)}function U(b,a){b.Ma=a;b.G.gain.cancelScheduledValues(0);b.Ua=-1;b.G.gain.value=b.tc()}function fc(b,a){a=!!a;b.Va!==a&&(b.Va=a,b.Ob())}
function Ib(b,a,c,d,e){if(b.vb){var f=b.Za,g=b.Ya,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Wc?b.s.Pc:performance.now()/1E3}
self.od=class{constructor(b,a,c){this.s=b;this.P=a;this.ra=c;this.Pb=ic++;this.G=this.V().createGain();this.G.connect(this.ha());this.F=null;this.vb=!1;this.Za=[0,0,0];this.Ya=[0,0,0];this.va=[0,0,0];this.ga=null;this.Xb=!1;this.cd=0;this.J=!0;this.Z=this.wa=this.K=!1;this.Ma=1;this.Va=!1;this.pa=1;b=this.s.fd;this.Wc=1===b&&!this.Ea()||2===b;this.Ua=this.ta=-1;this.ae=!1}j(){this.P=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.ga&&(this.ga.disconnect(),this.ga=null);this.G.disconnect();
this.G=null}V(){return this.s.V()}ha(){return $b(this.s,0<this.ra.length?this.ra[0]:"")}sc(){return this.P.sc()}ib(){return this.P.ib()}rc(){return this.P.rc()}Ea(){return this.P.Ea()}O(){}oc(){}IsPlaying(){return!this.J&&!this.K&&!this.O()}Oa(){}ia(){return this.P.ia()}Play(){}Fa(){}lb(){}Jb(){}Qa(b){-1!==this.Ua&&b>=this.Ua&&(this.Ua=-1,this.ae&&this.Fa(),dc(this.s,"fade-ended",this.ra,this.Pb))}tc(){const b=this.Ma;return isFinite(b)?b:0}Ib(){return this.s.Ib()}Ob(){}xc(){}Ha(){}wc(){}yc(){}uc(){}hb(){var b=
this.Pb,a=this.ra,c=this.ia(),d=-1===this.Ua?this.Ma:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Za,orient:this.Ya,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ta}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Oa(),playbackRate:this.pa,uid:this.ta,bufferOriginalUrl:this.sc(),bufferUrl:"",bufferType:this.rc(),isMusic:this.Ea(),isLooping:this.Z,isMuted:this.Va,resumePosition:this.uc(),pan:f,stereoPan:this.ga?
this.cd:null}}Dc(b){var a=b.playbackRate;this.pa!==a&&(this.pa=a,this.Ha());fc(this,b.isMuted)}};"use strict";
self.se=class extends self.od{constructor(b,a,c){super(b,a,c);this.P.Cb.connect(this.G);this.P.onended=()=>this.Ec()}j(){this.Fa();this.P.Cb.disconnect();super.j()}W(){return this.P.W()}Ec(){this.J=!0;this.ta=-1;dc(this.s,"ended",this.ra,this.Pb)}O(){return this.W().ended}oc(){return this.J?!0:this.O()}Oa(){let b=this.W().currentTime;this.Z||(b=Math.min(b,this.ia()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.ib()}' to position '${c}': `,e)}this.s.Ga(d);this.K=this.J=!1;this.Z=b;this.pa=1}Fa(){const b=this.W();b.paused||b.pause();this.s.Pa(b);this.J=!0;this.K=!1;this.ta=-1}lb(){if(!(this.K||this.J||this.O())){var b=this.W();b.paused||b.pause();this.s.Pa(b);this.K=!0}}Jb(){!this.K||this.J||this.O()||(this.s.Ga(this.W()),this.K=!1)}Ob(){this.W().muted=this.Va||this.Ib()}xc(b){b=!!b;this.Z!==b&&(this.Z=
b,this.W().loop=b)}Ha(){let b=this.pa;this.Wc&&(b*=this.s.kc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}wc(b){if(!this.J&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}uc(){return this.Oa()}yc(b){b?this.IsPlaying()?(this.W().pause(),this.wa=!0):this.wa=!1:this.wa&&(this.s.Ga(this.W()),this.wa=!1)}};"use strict";
function W(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.ob=null}
self.ue=class extends self.od{constructor(b,a,c){super(b,a,c);this.o=null;this.bc=d=>this.Ec(d);this.Rc=!0;this.ob=null;this.S=this.dc=this.fc=0;this.ad=1}j(){this.Fa();W(this);this.bc=null;super.j()}Ec(b){this.K||this.wa||b.target!==this.ob||(this.J=this.Rc=!0,this.ta=-1,W(this),dc(this.s,"ended",this.ra,this.Pb))}O(){return!this.J&&this.o&&this.o.loop||this.K?!1:this.Rc}oc(){return!this.o||this.J?!0:this.O()}Oa(){let b;b=this.K?this.S:this.dc+(V(this)-this.fc)*this.pa;this.Z||(b=Math.min(b,this.ia()));
return b}Play(b,a,c,d){this.ad=1;U(this,a);W(this);this.o=this.V().createBufferSource();this.o.buffer=this.P.ka;this.o.connect(this.G);this.ob=this.o;this.o.onended=this.bc;this.o.loop=b;this.o.start(d,c);this.K=this.J=this.Rc=!1;this.Z=b;this.pa=1;this.fc=V(this);this.dc=c}Fa(){if(this.o)try{this.o.stop(0)}catch(b){}this.J=!0;this.K=!1;this.ta=-1}lb(){this.K||this.J||this.O()||(this.S=this.Oa(),this.Z&&(this.S%=this.ia()),this.K=!0,this.o.stop(0))}Jb(){!this.K||this.J||this.O()||(W(this),this.o=
this.V().createBufferSource(),this.o.buffer=this.P.ka,this.o.connect(this.G),this.ob=this.o,this.o.onended=this.bc,this.o.loop=this.Z,U(this,this.Ma),this.Ha(),this.o.start(0,this.S),this.fc=V(this),this.dc=this.S,this.K=!1)}tc(){return super.tc()*this.ad}Ob(){this.ad=this.Va||this.Ib()?0:1;U(this,this.Ma)}xc(b){b=!!b;this.Z!==b&&(this.Z=b,this.o&&(this.o.loop=b))}Ha(){let b=this.pa;this.Wc&&(b*=this.s.kc);this.o&&(this.o.playbackRate.value=b)}wc(b){this.J||this.O()||(this.K?this.S=b:(this.lb(),this.S=
b,this.Jb()))}uc(){return this.S}yc(b){b?this.IsPlaying()?(this.wa=!0,this.S=this.Oa(),this.Z&&(this.S%=this.ia()),this.o.stop(0)):this.wa=!1:this.wa&&(W(this),this.o=this.V().createBufferSource(),this.o.buffer=this.P.ka,this.o.connect(this.G),this.ob=this.o,this.o.onended=this.bc,this.o.loop=this.Z,U(this,this.Ma),this.Ha(),this.o.start(0,this.S),this.fc=V(this),this.dc=this.S,this.wa=!1)}Dc(b){super.Dc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.s=b;this.g=b.V();this.Pd=-1;this.T=this.dd="";this.m=null}j(){this.g=null}N(){}U(){}hb(){return{type:this.T,tag:this.dd,params:this.m}}}
self.ke=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.u=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i)}j(){this.u.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.ie=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.zb=X(this);this.Y=this.g.createDelay(a);this.Y.delayTime.value=a;this.sb=X(this);this.sb.gain.value=c;this.u.connect(this.zb);this.u.connect(this.h);this.zb.connect(this.i);this.zb.connect(this.Y);this.Y.connect(this.sb);this.sb.connect(this.zb)}j(){this.u.disconnect();this.i.disconnect();this.h.disconnect();this.zb.disconnect();
this.Y.disconnect();this.sb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}$(b,a,c,d){const e=self.gb.rd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.sb.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.Y.delayTime,a,c,d)}}};
self.he=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.Gd=this.Fd="";this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.rb=this.g.createConvolver();this.rb.normalize=c;this.rb.buffer=a;this.u.connect(this.rb);this.u.connect(this.h);this.rb.connect(this.i)}j(){this.u.disconnect();this.rb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}$(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}hb(){const b=super.hb();b.bufferOriginalUrl=this.Fd;b.bufferUrl="";b.bufferType=this.Gd;return b}};
self.le=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.u=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.ub=X(this);this.ub.gain.value=e;this.Y=this.g.createDelay(a+c);this.Y.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.L=X(this);this.L.gain.value=c;this.u.connect(this.Y);this.u.connect(this.h);this.Y.connect(this.i);this.Y.connect(this.ub);this.ub.connect(this.Y);this.B.connect(this.L);
this.L.connect(this.Y.delayTime);this.B.start(0)}j(){this.B.stop(0);this.u.disconnect();this.Y.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.ub.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.B.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.ub.gain,a/100,c,d)}}};
self.ne=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.u=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=X(this);this.L.gain.value=e;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i);this.B.connect(this.L);this.L.connect(this.D.frequency);
this.B.start(0)}j(){this.B.stop(0);this.u.disconnect();this.D.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.B.frequency,a,c,d)}}};self.me=class extends Z{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}$(b,a,c,d){const e=self.gb.rd;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.pe=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}$(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.qe=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=X(this);this.L.gain.value=c/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.oe=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.u=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Eb=X(this);this.Eb.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.Eb.gain);this.B.start(0);this.u.connect(this.Eb);this.u.connect(this.h);this.Eb.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.Eb.disconnect();this.u.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.je=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.u=X(this);this.ic=X(this);this.hc=X(this);b=d;.01>b&&(b=.01);this.ic.gain.value=b;this.hc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.lc=this.g.createWaveShaper();this.Jc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Jc[32768+e]=f,this.Jc[32768-
e-1]=-f;this.lc.curve=this.Jc;this.u.connect(this.ic);this.u.connect(this.h);this.ic.connect(this.lc);this.lc.connect(this.hc);this.hc.connect(this.i)}j(){this.u.disconnect();this.ic.disconnect();this.lc.disconnect();this.hc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.ge=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}$(){}};
self.fe=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Md=new Float32Array(this.l.frequencyBinCount);this.$d=new Uint8Array(a);this.Yd=this.$a=0;b=this.s;b.Sa.add(this);T(b)}j(){this.s.Sa.delete(this);this.l.disconnect();super.j()}Qa(){this.l.getFloatFrequencyData(this.Md);this.l.getByteTimeDomainData(this.$d);const b=this.l.fftSize;let a=this.$a=0;for(var c=0;c<b;++c){let d=(this.$d[c]-
128)/128;0>d&&(d=-d);this.$a<d&&(this.$a=d);a+=d*d}c=self.gb.Be;this.$a=c(this.$a);this.Yd=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}$(){}};
