function m(c,a,b,d){c.i.aa(c.S,a,b,d)}function n(c,a,b,d){c.i.o?m(c,a,b,d):c.i.tb()._OnMessageFromDOM({type:"event",component:c.S,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function p(c,a,b){c.i.h(c.S,a,b)}function aa(c,a){for(const [b,d]of a)p(c,b,d)}window.$=class{constructor(c,a){this.i=c;this.S=a}Ia(){}};window.Zb=class{constructor(){}};"use strict";class ba{constructor(c){this.ua=c;this.wa=!1;this.za=!0}}
function ca(c,a){const b=a.elementId,d=c.ma(b,a),e=new ba(d);c.T.set(b,e);d.style.boxSizing="border-box";d.style.display="none";e.za=!!a.isVisible;d.addEventListener("focus",()=>{r(c,"elem-focused",b)});d.addEventListener("blur",()=>{r(c,"elem-blurred",b)});c.ea&&document.body.appendChild(d)}function t(c,a,b){p(c,a,d=>{const e=u(c,d.elementId);return b(e,d)})}function u(c,a){c=c.T.get(a);if(!c)throw Error(`no element with id ${a}`);return c.ua}
function r(c,a,b,d){d||(d={});d.elementId=b;m(c,a,d)}function v(c,a,b,d){d||(d={});d.elementId=b;n(c,a,d)}
window.Ka=class extends self.${constructor(c,a){super(c,a);this.T=new Map;this.ea=!0;aa(this,[["create",b=>ca(this,b)],["destroy",b=>{b=b.elementId;const d=u(this,b);this.ea&&d.parentElement.removeChild(d);this.T.delete(b)}],["set-visible",b=>{if(this.ea){var d=this.T.get(b.elementId),e=d.ua;d.wa?e.style.display=b.isVisible?"":"none":d.za=!!b.isVisible}}],["update-position",b=>{if(this.ea){var d=this.T.get(b.elementId),e=d.ua;e.style.left=b.left+"px";e.style.top=b.top+"px";e.style.width=b.width+"px";
e.style.height=b.height+"px";b=b.fontSize;null!==b&&(e.style.fontSize=b+"em");d.wa||(d.wa=!0,d.za&&(e.style.display=""))}}],["update-state",b=>{const d=u(this,b.elementId);this.ba(d,b)}],["focus",b=>{const d=u(this,b.elementId);b.focus?d.focus():d.blur()}],["set-css-style",b=>{const d=u(this,b.elementId),e=b.prop;b=b.val;e.startsWith("--")?d.style.setProperty(e,b):d.style[e]=b}],["set-attribute",b=>{u(this,b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{u(this,b.elementId).removeAttribute(b.name)}]]);
t(this,"get-element",b=>b)}ma(){throw Error("required override");}ba(){throw Error("required override");}};"use strict";const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),w=/android/i.test(navigator.userAgent),ea=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let fa=0;
function x(c){const a=document.createElement("script");a.async=!1;a.type="module";return c.Pb?new Promise(b=>{const d="c3_resolve_"+fa;++fa;self[d]=b;a.textContent=c.Tb+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((b,d)=>{a.onload=b;a.onerror=d;a.src=c;document.head.appendChild(a)})}let ha=!1,ia=!1;function ja(){if(!ha){try{new Worker("blob://",{get type(){ia=!0}})}catch(c){}ha=!0}return ia}let y=new Audio;
const ka={"audio/webm; codecs=opus":!!y.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!y.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!y.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!y.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!y.canPlayType("audio/mp4"),"audio/mpeg":!!y.canPlayType("audio/mpeg")};y=null;async function la(c){c=await ma(c);return(new TextDecoder("utf-8")).decode(c)}
function ma(c){return new Promise((a,b)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>b(e);d.readAsArrayBuffer(c)})}const z=[];let A=0;window.RealFile=window.File;const B=[],C=new Map,D=new Map;let na=0;const oa=[];self.runOnStartup=function(c){if("function"!==typeof c)throw Error("runOnStartup called without a function");oa.push(c)};const pa=new Set(["cordova","playable-ad","instant-games"]);let qa=!1;
window.F=class c{constructor(a){this.o=a.Vb;this.W=null;this.m="";this.I=a.Sb;this.Z={};this.Ba=this.K=null;this.fa=[];this.j=this.D=null;this.Ya=!1;this.U=null;this.H=-1;this.Lb=()=>this.Bb();this.Ea=[];this.Ga=null;this.ab=[];this.g=a.bb;this.ya="file"===location.protocol.substr(0,4);!this.o||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ja()||(this.o=!1);this.o&&ea&&(this.o=!1);if("playable-ad"===this.g||"instant-games"===this.g)this.o=!1;if("cordova"===this.g&&this.o)if(w){const b=
/Chrome\/(\d+)/i.exec(navigator.userAgent);b&&90<=parseInt(b[1],10)||(this.o=!1)}else this.o=!1;this.O()?self.chrome.webview.addEventListener("message",b=>this.Qa(b.data)):"macos-wkwebview"===this.g&&(self.C3WrapperOnMessage=b=>this.Qa(b));this.ga=this.A=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.h("runtime",
"cordova-fetch-local-file",b=>this.xb(b));this.h("runtime","create-job-worker",()=>this.yb());this.h("runtime","send-wrapper-extension-message",b=>this.Eb(b));"cordova"===this.g?document.addEventListener("deviceready",()=>this.Oa(a)):this.Oa(a)}hb(){return da&&"cordova"===this.g}oa(){const a=navigator.userAgent;return da&&pa.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}fb(){return w}La(){return w&&pa.has(this.g)}O(){return"windows-webview2"===this.g||!!("preview"===this.g&&
window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}async Oa(a){"macos-wkwebview"===this.g?this.P({type:"ready"}):this.O()&&(this.Gb(),this.ab=(await this.wb()).registeredComponentIds);if("playable-ad"===this.g){this.A=self.c3_base64files;this.ga={};await this.pb();for(let d=0,e=a.L.length;d<e;++d){var b=a.L[d];this.ga.hasOwnProperty(b)?a.L[d]={Pb:!0,Tb:this.ga[b]}:this.A.hasOwnProperty(b)&&(a.L[d]=URL.createObjectURL(this.A[b]))}a.ka=[]}if("nwjs"===this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=
0;this.lb(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Rb?this.m=a.Rb:(b=location.origin,this.m=("null"===b?"file:///":b)+location.pathname,b=this.m.lastIndexOf("/"),-1!==b&&(this.m=this.m.substr(0,b+1)));a.Xb&&(this.Z=a.Xb);b=new MessageChannel;this.W=b.port1;this.W.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Ab(d));this.U=new self.ib(this);await ra(this.U);"object"===typeof window.StatusBar&&window.StatusBar.hide();
if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.o?await this.vb(a,b.port2):await this.ub(a,b.port2)}qa(a){a=this.Z.hasOwnProperty(a)?this.Z[a]:a.endsWith("/workermain.js")&&this.Z.hasOwnProperty("workermain.js")?this.Z["workermain.js"]:"playable-ad"===this.g&&this.A.hasOwnProperty(a)?this.A[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async na(a,
b,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.g&&this.ya)return a=await this.la(d.Ob?a:this.I+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,b);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}v(){return Math.max(window.innerWidth,1)}u(){return Math.max(window.innerHeight,1)}Na(a){var b=
this.m,d=location.href,e=this.v(),f=this.u(),h=window.devicePixelRatio,g=c.N(),k=a.bc,l=window.cr_previewImageBlobs||this.A,q=window.cr_previewProjectFileBlobs,Da=window.cr_previewProjectFiles,Ea=window.cr_swClientId||"";a=a.bb;var Fa=(new URLSearchParams(self.location.search)).has("debug"),Q=this.U;return{runtimeBaseUrl:b,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:h,isFullscreen:g,projectData:k,previewImageBlobs:l,previewProjectFileBlobs:q,previewProjectFileSWUrls:Da,swClientId:Ea,
exportType:a,isDebug:Fa,ife:!!self.ac,jobScheduler:{inputPort:Q.xa,outputPort:Q.Da,maxNumWorkers:Q.Jb},supportedAudioFormats:ka,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.I+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.I+"opus.wasm.wasm",isFileProtocol:this.ya,isiOSCordova:this.hb(),isiOSWebView:this.oa(),isWebView2Wrapper:this.O(),wrapperComponentIds:this.ab,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async vb(a,b){const d=this.qa(a.Wb);"preview"===this.g?
(this.K=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((g,k)=>{const l=q=>{this.K.removeEventListener("message",l);q.data&&"ok"===q.data.type?g():k()};this.K.addEventListener("message",l);this.K.postMessage({type:"construct-worker-init","import":(new URL(d,this.m)).toString()})})):this.K=await this.na(d,this.m,{type:"module",name:"Runtime",Ob:!0});this.j=document.createElement("canvas");this.j.style.display="none";const e=this.j.transferControlToOffscreen();document.body.appendChild(this.j);
window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.ka||[],h=a.L;f=await Promise.all(f.map(g=>this.G(g)));h=await Promise.all(h.map(g=>this.G(g)));if("cordova"===this.g)for(let g=0,k=a.ja.length;g<k;++g){const l=a.ja[g],q=l[0];if(q===a.Ha||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))l[1]=await this.G(q)}this.K.postMessage(Object.assign(this.Na(a),{type:"init-runtime",isInWorker:!0,messagePort:b,canvas:e,workerDependencyScripts:f,engineScripts:h,
projectScripts:a.ja,mainProjectScript:a.Ha,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[b,e,...sa(this.U)]);this.fa=B.map(g=>new g(this));this.Ma();ta(this.D);self.c3_callFunction=(g,k)=>{var l=this.D;return l.i.jb(l.S,{name:g,params:k})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.aa("runtime","go-to-last-error-script"))}async ub(a,b){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&
self.C3_InsertHTMLPlaceholders();this.fa=B.map(h=>new h(this));this.Ma();var d=a.L.map(h=>"string"===typeof h?(new URL(h,this.m)).toString():h);if(Array.isArray(a.ka)){var e=[...a.ka].map(h=>h instanceof Blob?URL.createObjectURL(h):h);d.unshift(...e)}d=await Promise.all(d.map(h=>this.G(h)));await Promise.all(d.map(h=>x(h)));d=self.C3_ProjectScriptsStatus;e=a.Ha;const f=a.ja;for(let [h,g]of f)if(g||(g=h),h===e)try{g=await this.G(g),await x(g),"preview"!==this.g||d[h]||this.Ra(h,"main script did not run to completion")}catch(k){this.Ra(h,
k)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))g=await this.G(g),await x(g);"preview"===this.g&&"object"!==typeof self.Yb.$b?(this.da(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Na(a),{isInWorker:!1,messagePort:b,canvas:this.j,runOnStartupFunctions:oa}),ta(this.D),
this.Pa(),this.Ba=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ba,a))}Ra(a,b){this.da();console.error(`[Preview] Failed to load project main script (${a}): `,b);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Pa(){this.da()}da(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async yb(){const a=await ua(this.U);return{outputPort:a,
transferables:[a]}}tb(){if(this.o)throw Error("not available in worker mode");return this.Ba}aa(a,b,d,e){this.W.postMessage({type:"event",component:a,handler:b,dispatchOpts:e||null,data:d,responseId:null},void 0)}jb(a,b){const d=na++,e=new Promise((f,h)=>{D.set(d,{resolve:f,reject:h})});this.W.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:b,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const b=a.type;if("event"===b)return this.zb(a);if("result"===
b)this.Cb(a);else if("runtime-ready"===b)this.Db();else if("alert-error"===b)this.da(),alert(a.message);else if("creating-runtime"===b)this.Pa();else throw Error(`unknown message '${b}'`);}zb(a){const b=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=C.get(b))if(a=a.get(d)){var h=null;try{h=a(e)}catch(g){console.error(`Exception in '${b}' handler '${d}':`,g);null!==f&&this.ca(f,!1,""+g);return}if(null===f)return h;h&&h.then?h.then(g=>this.ca(f,!0,g)).catch(g=>{console.error(`Rejection from '${b}' handler '${d}':`,
g);this.ca(f,!1,""+g)}):this.ca(f,!0,h)}else console.warn(`[DOM] No handler '${d}' for component '${b}'`);else console.warn(`[DOM] No event handlers for component '${b}'`)}ca(a,b,d){let e;d&&d.transferables&&(e=d.transferables);this.W.postMessage({type:"result",responseId:a,isOk:b,result:d},e)}Cb(a){const b=a.responseId,d=a.isOk;a=a.result;const e=D.get(b);d?e.resolve(a):e.reject(a);D.delete(b)}h(a,b,d){let e=C.get(a);e||(e=new Map,C.set(a,e));if(e.has(b))throw Error(`[DOM] Component '${a}' already has handler '${b}'`);
e.set(b,d)}static M(a){if(B.includes(a))throw Error("DOM handler already added");B.push(a)}Ma(){for(const a of this.fa)if("runtime"===a.S){this.D=a;return}throw Error("cannot find runtime DOM handler");}Ab(a){this.aa("debugger","message",a)}Db(){for(const a of this.fa)a.Ia()}static N(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||qa)}static Sa(a){qa=!!a}lb(a){this.Ea.push(a);this.sa()}sa(){-1===this.H&&this.Ea.length&&(this.H=requestAnimationFrame(this.Lb))}nb(){-1!==
this.H&&(cancelAnimationFrame(this.H),this.H=-1)}Bb(){this.H=-1;for(const a of this.Ea)a();this.sa()}ra(){this.D.ra()}kb(){this.Ya=!0}eb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}gb(a){return!this.eb(a)}async G(a){return"cordova"===this.g&&(a.startsWith("file:")||this.ya&&this.gb(a))?(a.startsWith(this.m)&&(a=a.substr(this.m.length)),a=await this.la(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async xb(a){const b=a.filename;
switch(a.as){case "text":return await this.cb(b);case "buffer":return await this.la(b);default:throw Error("unsupported type");}}Ja(a){const b=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(b,f=>{f.file(d,e)},e)})}async cb(a){a=await this.Ja(a);return await la(a)}pa(){if(z.length&&!(8<=A)){A++;var a=z.shift();this.qb(a.filename,a.Ub,a.Nb)}}la(a){return new Promise((b,d)=>{z.push({filename:a,Ub:e=>{A--;this.pa();b(e)},Nb:e=>{A--;this.pa();
d(e)}});this.pa()})}async qb(a,b,d){try{const e=await this.Ja(a),f=await ma(e);b(f)}catch(e){d(e)}}Qa(a){if("entered-fullscreen"===a)c.Sa(!0),E(this.D);else if("exited-fullscreen"===a)c.Sa(!1),E(this.D);else if("object"===typeof a){const b=a.type;"wrapper-init-response"===b?(this.Ga(a),this.Ga=null):"extension-message"===b?this.aa("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Eb(a){this.P({type:"extension-message",
componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}P(a){this.O()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.g&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Gb(){window.moveTo=(a,b)=>{this.P({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(b)})};window.resizeTo=(a,b)=>{this.P({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(b)})}}wb(){return this.O()?new Promise(a=>
{this.Ga=a;this.P({type:"wrapper-init"})}):Promise.resolve()}async pb(){const a=[];for(const [b,d]of Object.entries(this.A))a.push(this.ob(b,d));await Promise.all(a)}async ob(a,b){if("object"===typeof b)this.A[a]=new Blob([b.str],{type:b.type}),this.ga[a]=b.str;else{let d=await this.sb(b);d||(d=this.rb(b));this.A[a]=d}}async sb(a){try{return await (await fetch(a)).blob()}catch(b){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
b),null}}rb(a){a=this.Fb(a);return this.mb(a.data,a.Qb)}Fb(a){var b=a.indexOf(",");if(0>b)throw new URIError("expected comma in data: uri");var d=a.substring(b+1);b=a.substring(5,b).split(";");a=b[0]||"";const e=b[2];d="base64"===b[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Qb:a,data:d}}mb(a,b){var d=a.length;let e=d>>2,f=new Uint8Array(d),h=new Uint32Array(f.buffer,0,e),g,k;for(k=g=0;g<e;++g)h[g]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:b})}};"use strict";const G=self.F;function va(c){return c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents}const wa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),H={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},xa={dispatchUserScriptEvent:!0},I={dispatchRuntimeEvent:!0};
function ya(c){return new Promise((a,b)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>b(e);d.rel="stylesheet";d.href=c;document.head.appendChild(d)})}function za(c){return new Promise((a,b)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>b(e);d.src=c})}async function J(c){c=URL.createObjectURL(c);try{return await za(c)}finally{URL.revokeObjectURL(c)}}
function Aa(c){return new Promise((a,b)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>b(e);d.readAsText(c)})}
async function Ba(c,a,b){if(!/firefox/i.test(navigator.userAgent))return await J(c);var d=await Aa(c);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),h=e.getAttribute("height");if(!f.includes("%")&&!h.includes("%"))return await J(c)}e.setAttribute("width",a+"px");e.setAttribute("height",b+"px");d=(new XMLSerializer).serializeToString(d);c=new Blob([d],{type:"image/svg+xml"});return await J(c)}
function K(c){do{if(c.parentNode&&c.hasAttribute("contenteditable"))return!0;c=c.parentNode}while(c);return!1}const Ca=new Set(["input","textarea","datalist","select"]),Ga=new Set(["canvas","body","html"]);function L(c){c.target.tagName&&Ga.has(c.target.tagName.toLowerCase())&&c.preventDefault()}function Ha(c){(c.metaKey||c.ctrlKey)&&c.preventDefault()}
self.C3_GetSvgImageSize=async function(c){c=await J(c);if(0<c.width&&0<c.height)return[c.width,c.height];c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.visibility="hidden";document.body.appendChild(c);const a=c.getBoundingClientRect();document.body.removeChild(c);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(c,a,b,d,e){c=await Ba(c,a,b);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(c,0,0,a,b);return f};
let M=!1;document.addEventListener("pause",()=>M=!0);document.addEventListener("resume",()=>M=!1);function ta(c){c.Wa=!0;c.Aa=c.i.v();c.V=c.i.u()}function E(c){if(!c.l){var a=G.N();a&&"any"!==c.Fa&&Ia(c);m(c,"fullscreenchange",{isFullscreen:a,innerWidth:c.v(),innerHeight:c.u()})}}async function Ja(c){await Promise.all(c.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function La(c){var a=c.imageBitmapOpts;c=await self.C3_RasterSvgImageBlob(c.blob,c.imageWidth,c.imageHeight,c.surfaceWidth,c.surfaceHeight);a=a?await createImageBitmap(c,a):await createImageBitmap(c);return{imageBitmap:a,transferables:[a]}}async function Ma(c){return await self.C3_GetSvgImageSize(c.blob)}function Na(c){window.c3_postToMessagePort&&(c.from="runtime",window.c3_postToMessagePort(c))}
function Oa(c){self.setTimeout(()=>{c.Va=!0},1E3);"cordova"===c.i.g?(document.addEventListener("pause",()=>N(c,!0)),document.addEventListener("resume",()=>N(c,!1))):document.addEventListener("visibilitychange",()=>N(c,"hidden"===document.visibilityState));c.ha=!("hidden"!==document.visibilityState&&!M);return{isSuspended:c.ha}}
function Pa(c){c.Ua||(c.Ua=!0,window.addEventListener("deviceorientation",a=>{c.l||m(c,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},H)}),window.addEventListener("deviceorientationabsolute",a=>{c.l||m(c,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},H)}))}
function Qa(c){c.Ta||(c.Ta=!0,window.addEventListener("devicemotion",a=>{if(!c.l){var b=null,d=a.acceleration;d&&(b={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(c,"devicemotion",{acceleration:b,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},H)}}))}async function Ra(c){await ya(c.url)}
function Sa(c,a){c.Xa=a.message;-1===c.va&&(c.va=setTimeout(()=>{c.va=-1;const b=document.getElementById("exportToVideoMessage");b&&(b.textContent=c.Xa)},250))}function O(c,a){console.warn("[Construct] Fullscreen request failed: ",a);m(c,"fullscreenerror",{isFullscreen:G.N(),innerWidth:c.v(),innerHeight:c.u()})}function N(c,a){c.ha!==a&&((c.ha=a)?c.i.nb():c.i.sa(),m(c,"visibilitychange",{hidden:a}))}
function Ta(c,a,b){"Backspace"===b.key&&L(b);if(!c.l){var d=wa.get(b.code)||b.code;n(c,a,{code:d,key:b.key,which:b.which,repeat:b.repeat,altKey:b.altKey,ctrlKey:b.ctrlKey,metaKey:b.metaKey,shiftKey:b.shiftKey,timeStamp:b.timeStamp},H)}}function P(c,a,b,d){c.l||va(b)||n(c,a,{button:b.button,buttons:b.buttons,clientX:b.clientX,clientY:b.clientY+c.s,pageX:b.pageX,pageY:b.pageY+c.s,movementX:b.movementX||0,movementY:b.movementY||0,timeStamp:b.timeStamp},d)}
function R(c){window!==window.top&&window.focus();Ua(c.target)&&document.activeElement&&!Ua(document.activeElement)&&document.activeElement.blur()}
function S(c,a,b){if(!c.l){var d=0;"mouse"===b.pointerType&&(d=c.X);n(c,a,{pointerId:b.pointerId,pointerType:b.pointerType,button:b.button,buttons:b.buttons,lastButtons:d,clientX:b.clientX,clientY:b.clientY+c.s,pageX:b.pageX,pageY:b.pageY+c.s,movementX:b.movementX||0,movementY:b.movementY||0,width:b.width||0,height:b.height||0,pressure:b.pressure||0,tangentialPressure:b.tangentialPressure||0,tiltX:b.tiltX||0,tiltY:b.tiltY||0,twist:b.twist||0,timeStamp:b.timeStamp},H);"mouse"===b.pointerType&&(d="mousemove",
"pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),P(c,d,b,xa),c.X=b.buttons)}}
function T(c,a,b){if(!c.l&&!va(b)){var d=c.X;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==b.buttons&&(a="pointermove");n(c,a,{pointerId:1,pointerType:"mouse",button:b.button,buttons:b.buttons,lastButtons:d,clientX:b.clientX,clientY:b.clientY+c.s,pageX:b.pageX,pageY:b.pageY+c.s,movementX:b.movementX||0,movementY:b.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:b.timeStamp},H);c.X=b.buttons;P(c,b.type,b,xa)}}
function U(c,a,b){if(!c.l)for(let d=0,e=b.changedTouches.length;d<e;++d){const f=b.changedTouches[d];n(c,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+c.s,pageX:f.pageX,pageY:f.pageY+c.s,movementX:b.movementX||0,movementY:b.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:b.timeStamp},
H)}}function V(c,a,b){document.body.style.transform="";c.s=0;if(0<b){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-b)/2,a>b&&(a=b),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,c.s=a))}}function Va(c,a,b,d){const e=c.v(),f=c.u();c.J=-1;e!=a||f!=b?m(c,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.N()}):10>d&&Wa(c,e,f,d+1)}
function Wa(c,a,b,d){-1!==c.J&&clearTimeout(c.J);c.J=setTimeout(()=>Va(c,a,b,d),48)}
function Ia(c){c=c.Fa;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(c):screen.webkitLockOrientation?a=screen.webkitLockOrientation(c):screen.mozLockOrientation?a=screen.mozLockOrientation(c):screen.msLockOrientation&&(a=screen.msLockOrientation(c));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Ua(c){return!c||c===document||c===window||c===document.body||"canvas"===c.tagName.toLowerCase()}
G.M(class extends self.${constructor(c){super(c,"runtime");this.Za=!0;this.Wa=!1;this.J=-1;this.Fa="any";this.ha=this.Ta=this.Ua=!1;this.ia=document.createElement("div");this.ia.className="c3-screen-reader-text";this.ia.setAttribute("aria-live","polite");document.body.appendChild(this.ia);this.C=null;this.l=!1;this.Xa="";this.va=-1;this.Va=!1;this.Aa=c.v();this.V=c.u();this.s=this.Y=0;c.h("canvas","update-size",d=>{var e=this.i;e.Ya||(e=e.j,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Za&&(e.style.display="",this.Za=!1))});c.h("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),h=document.body;f.textContent=d;f.href=e;f.download=d;h.appendChild(f);f.click();h.removeChild(f)});c.h("runtime","load-webfonts",d=>Ja(d));c.h("runtime","raster-svg-image",d=>La(d));c.h("runtime","get-svg-image-size",
d=>Ma(d));c.h("runtime","set-target-orientation",d=>{this.Fa=d.targetOrientation});c.h("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});c.h("runtime","post-to-debugger",d=>Na(d));c.h("runtime","go-to-script",d=>Na(d));c.h("runtime","before-start-ticking",()=>Oa(this));c.h("runtime","debug-highlight",d=>{if(d.show){this.C||(this.C=document.createElement("div"),this.C.id="inspectOutline",document.body.appendChild(this.C));var e=this.C;e.style.display="";e.style.left=d.left-
1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.C&&(this.C.style.display="none")});c.h("runtime","enable-device-orientation",()=>Pa(this));c.h("runtime","enable-device-motion",()=>Qa(this));c.h("runtime","add-stylesheet",d=>Ra(d));c.h("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});c.h("runtime","alert",d=>{alert(d.message)});c.h("runtime",
"screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.ia.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
c.h("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});c.h("runtime","set-exporting-to-video",d=>{this.l=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.kb()});c.h("runtime","export-to-video-progress",d=>Sa(this,d));c.h("runtime","exported-to-video",d=>{window.Mb({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});c.h("runtime","exported-to-image-sequence",d=>{window.Mb({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||K(e)||d.preventDefault()});const b=c.j;window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);b.addEventListener("selectstart",L);b.addEventListener("gesturehold",
L);window.addEventListener("touchstart",L,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",L,{passive:!1}),b.addEventListener("pointerdown",L)):b.addEventListener("touchstart",L);this.X=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ha,{passive:!1});window.addEventListener("wheel",Ha,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.l&&this.Wa){var d=this.v();var e=this.u();if(this.i.La()){if(this.Va){if(this.Aa===
d&&e<this.V){this.Y=this.V-e;V(this,this.V,this.Y);d=void 0;break a}0<this.Y&&(this.Y=0,V(this,e,this.Y))}this.Aa=d;this.V=e}m(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.N()});this.i.oa()&&(-1!==this.J&&clearTimeout(this.J),Va(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>E(this));window.addEventListener("webkitfullscreenchange",()=>E(this));window.addEventListener("mozfullscreenchange",()=>E(this));window.addEventListener("fullscreenerror",
d=>O(this,d));window.addEventListener("webkitfullscreenerror",d=>O(this,d));window.addEventListener("mozfullscreenerror",d=>O(this,d));if(c.oa())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):K(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});this.Ca=new Set;this.Kb=new WeakSet;this.Ib=!1}Ia(){window.addEventListener("focus",()=>{m(this,"window-focus",null,I)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(b){a=!1}m(this,"window-blur",{parentHasFocus:a},I);this.X=0});window.addEventListener("focusin",a=>{a=a.target;(Ca.has(a.tagName.toLowerCase())||K(a))&&
m(this,"keyboard-blur",null,I)});window.addEventListener("keydown",a=>Ta(this,"keydown",a));window.addEventListener("keyup",a=>Ta(this,"keyup",a));window.addEventListener("dblclick",a=>P(this,"dblclick",a,H));window.addEventListener("wheel",a=>{this.l||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.s,pageX:a.pageX,pageY:a.pageY+this.s,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},H)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{R(a);S(this,"pointerdown",a)}),this.i.o&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{S(this,"pointermove",a)}):window.addEventListener("pointermove",a=>S(this,"pointermove",a)),window.addEventListener("pointerup",a=>S(this,"pointerup",a)),window.addEventListener("pointercancel",a=>S(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{R(a);T(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>T(this,"pointermove",
a)),window.addEventListener("mouseup",a=>T(this,"pointerup",a)),window.addEventListener("touchstart",a=>{R(a);U(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>U(this,"pointermove",a)),window.addEventListener("touchend",a=>U(this,"pointerup",a)),window.addEventListener("touchcancel",a=>U(this,"pointercancel",a)));const c=()=>this.ra();window.addEventListener("pointerup",c,!0);window.addEventListener("touchend",c,!0);window.addEventListener("click",c,!0);window.addEventListener("keydown",
c,!0);window.addEventListener("gamepadconnected",c,!0);this.i.fb()&&!this.i.La()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{V(this,this.u(),navigator.virtualKeyboard.boundingRect.height)}))}v(){return this.i.v()}u(){return this.i.u()}ra(){var c=[...this.Ca];this.Ca.clear();if(!this.Ib)for(const a of c)(c=a.play())&&c.catch(()=>{this.Kb.has(a)||this.Ca.add(a)})}});"use strict";
async function ra(c){if(c.Hb)throw Error("already initialised");c.Hb=!0;var a=c.B.qa(("playable-ad"===c.B.g?c.B.I:"")+"dispatchworker.js");c.ta=await c.B.na(a,c.R,{name:"DispatchWorker"});a=new MessageChannel;c.xa=a.port1;c.ta.postMessage({type:"_init","in-port":a.port2},[a.port2]);c.Da=await ua(c)}function sa(c){return[c.xa,c.Da]}
async function ua(c){const a=c.$a.length;var b=c.B.qa(("playable-ad"===c.B.g?c.B.I:"")+"jobworker.js");b=await c.B.na(b,c.R,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;c.ta.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);c.$a.push(b);return e.port1}
self.ib=class{constructor(c){this.B=c;this.R=c.m;this.R="preview"===c.g?this.R+"workers/":this.R+c.I;this.Jb=Math.min(navigator.hardwareConcurrency||2,16);this.ta=null;this.$a=[];this.Da=this.xa=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.F({Vb:!0,Wb:"workermain.js",L:["scripts/c3runtime.js"],ja:[],Ha:"",Sb:"scripts/",ka:[],bb:"html5"}));"use strict";
self.F.M(class extends self.${constructor(c){super(c,"mouse");aa(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.i.j.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function Xa(c,a){a=a.type;let b=!0;0===a?b=await Ya():1===a&&(b=await Za());m(c,"permission-result",{type:a,result:b})}async function Ya(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request orientation permission: ",c),!1}}
async function Za(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request motion permission: ",c),!1}}self.F.M(class extends self.${constructor(c){super(c,"touch");p(this,"request-permission",a=>Xa(this,a))}});"use strict";function W(c){c.stopPropagation()}function $a(c){13!==c.which&&27!==c.which&&c.stopPropagation()}
self.F.M(class extends self.Ka{constructor(c){super(c,"text-input");t(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}ma(c,a){let b;const d=a.type;"textarea"===d?(b=document.createElement("textarea"),b.style.resize="none"):(b=document.createElement("input"),b.type=d);b.style.position="absolute";b.autocomplete="off";b.addEventListener("pointerdown",W);b.addEventListener("pointermove",W);b.addEventListener("pointerrawupdate",W);b.addEventListener("pointerup",W);b.addEventListener("mousedown",
W);b.addEventListener("mouseup",W);b.addEventListener("keydown",$a);b.addEventListener("keyup",$a);b.addEventListener("click",e=>{e.stopPropagation();v(this,"click",c)});b.addEventListener("dblclick",e=>{e.stopPropagation();v(this,"dblclick",c)});b.addEventListener("input",()=>r(this,"change",c,{text:b.value}));a.id&&(b.id=a.id);a.className&&(b.className=a.className);this.ba(b,a);return b}ba(c,a){c.value=a.text;c.placeholder=a.placeholder;c.title=a.title;c.disabled=!a.isEnabled;c.readOnly=a.isReadOnly;
c.spellcheck=a.spellCheck;a=a.maxLength;0>a?c.removeAttribute("maxlength"):c.setAttribute("maxlength",a)}});"use strict";function ab(c){c.replaceChildren?c.replaceChildren():c.innerHTML=""}
function X(c){c=Array.from(c.querySelectorAll("script:not([c3-executed])"));for(const b of c){c=b.parentNode;var a=c.replaceChild;const d=document.createElement("script");d.text=b.text;const e=b.attributes;for(let f=0,h=e.length;f<h;++f){const g=e[f];d.setAttribute(g.name,g.value)}d.setAttribute("c3-executed","");a.call(c,d,b)}}function Y(c,a,b){return a?b?Array.from(c.querySelectorAll(a)):(c=c.querySelector(a))?[c]:[]:[c]}
function Z(c){return c?{isOk:!0,html:c.innerHTML,text:c.textContent}:{isOk:!1}}
self.F.M(class extends self.Ka{constructor(c){super(c,"html-element");t(this,"set-content",(a,b)=>{{const e=b.str,f=b.type,h=b.selector;b=b["is-all"];try{const g=Y(a,h,b);if(0===g.length)var d=Z(null);else{for(const k of g)"html"===f?(k.innerHTML=e,X(k)):k.textContent=e;d=Z(a)}}catch(g){console.warn("[HTML element] Failed to set content: ",g),d=Z(null)}}return d});t(this,"insert-content",(a,b)=>{{const e=b.str,f=b.type,h=b["at-end"]?"beforeend":"afterbegin",g=b.selector;b=b["is-all"];try{const k=
Y(a,g,b);if(0===k.length)var d=Z(null);else{for(const l of k)"html"===f?(l.insertAdjacentHTML(h,e),X(l)):l.insertAdjacentText(h,e);d=Z(a)}}catch(k){console.warn("[HTML element] Failed to insert content: ",k),d=Z(null)}}return d});t(this,"remove-content",(a,b)=>{{const e=b["is-clear"],f=b.selector;b=b["is-all"];if(f)try{const h=Y(a,f,b);if(0===h.length)var d=Z(null);else{for(const g of h)e?ab(g):g.remove();d=Z(a)}}catch(h){console.warn("[HTML element] Failed to remove content: ",h),d=Z(null)}else ab(a),
d=Z(a)}return d});t(this,"set-content-class",(a,b)=>{{const e=b.mode,f=b["class-array"],h=b.selector;b=b["is-all"];try{const g=Y(a,h,b);if(0===g.length)var d=Z(null);else{for(const k of g)for(const l of f)switch(e){case "add":k.classList.add(l);break;case "toggle":k.classList.toggle(l);break;case "remove":k.classList.remove(l)}d=Z(a)}}catch(g){console.warn("[HTML element] Failed to set class: ",g),d=Z(null)}}return d});t(this,"set-content-attribute",(a,b)=>{{const e=b.mode,f=b.attribute,h=b.value,
g=b.selector;b=b["is-all"];try{const k=Y(a,g,b);if(0===k.length)var d=Z(null);else{for(const l of k)switch(e){case "set":l.setAttribute(f,h);break;case "remove":l.removeAttribute(f)}d=Z(a)}}catch(k){console.warn("[HTML element] Failed to set attribute: ",k),d=Z(null)}}return d});t(this,"set-content-css-style",(a,b)=>{{const e=b.prop,f=b.value,h=b.selector;b=b["is-all"];try{const g=Y(a,h,b);if(0===g.length)var d=Z(null);else{for(const k of g)e.startsWith("--")?k.style.setProperty(e,f):k.style[e]=f;
d=Z(a)}}catch(g){console.warn("[HTML element] Failed to set style: ",g),d=Z(null)}}return d});t(this,"get-element-box",(a,b)=>{(a=(b=b.selector)?a.querySelector(b):a)?(a=a.getBoundingClientRect(),a={isOk:!0,left:a.left,top:a.top,right:a.right,bottom:a.bottom}):a={isOk:!1};return a});t(this,"insert-img-element",(a,b)=>{a:{const e=b.blobUrl;var d=b.width;const f=b.height,h=b.selector,g=b.insertAt;let k=a;if(h&&(k=a.querySelector(h),!k)){a={isOk:!1};break a}d=new Image(d,f);d.src=e;b.id&&(d.id=b.id);
b["class"]&&(d.className=b["class"]);0===g?k.prepend(d):1===g?k.append(d):k.replaceChildren?k.replaceChildren(d):(ab(k),k.append(d));a=Z(a)}return a});t(this,"set-scroll-position",(a,b)=>{a:{const d=b.selector,e=b.direction;b=b.position;if(d&&(a=a.querySelector(d),!a)){b=void 0;break a}"left"===e?a.scrollLeft=b:a.scrollTop=b;b=void 0}return b})}ma(c,a){const b=document.createElement(a.tag);a["style-attribute"]&&b.setAttribute("style",a["style-attribute"]);b.style.position="absolute";var d=a["stop-input-events-mode"];
if(0<d){let e=null;1===d?e=f=>{f.target!==b&&f.stopPropagation()}:2===d&&(e=f=>f.stopPropagation());b.addEventListener("pointerdown",e);b.addEventListener("pointermove",e);b.addEventListener("pointerrawupdate",e);b.addEventListener("pointerup",e);b.addEventListener("mousedown",e);b.addEventListener("mouseup",e);b.addEventListener("dblclick",e)}a["allow-context-menu"]&&b.addEventListener("contextmenu",e=>e.stopPropagation());b.addEventListener("click",e=>{e=e.target;const f=[];for(;e;){f.push({targetId:"string"===
typeof e.id?e.id:"",targetClass:"string"===typeof e.className?e.className:""});if(e===b)break;e=e.parentNode}v(this,"click",c,{chain:f})});b.addEventListener("animationend",e=>{const f=e.target;v(this,"animationend",c,{targetId:"string"===typeof f.id?f.id:"",targetClass:"string"===typeof f.className?f.className:"",animationName:e.animationName})});a.id&&(b.id=a.id);a.className&&(b.className=a.className);a["css-color"]&&(b.style.color=a["css-color"]);a["css-background-color"]&&(b.style.backgroundColor=
a["css-background-color"]);a["allow-text-selection"]||(b.style.userSelect="none",b.style.webkitUserSelect="none");d=a.str;"html"===a.type?(b.innerHTML=d,X(b)):b.textContent=d;v(this,"initial-content",c,{html:b.innerHTML,text:b.textContent});return b}ba(c,a){c.innerHTML=a.html;X(c)}});
