function l(b,a,c,d,e){b.i.ca(b.V,a,c,d,e)}function m(b,a,c,d){b.i.l?l(b,a,c,d):b.i.Bb()._OnMessageFromDOM({type:"event",component:b.V,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.i.h(b.V,a,c)}function r(b,a){for(const [c,d]of a)q(b,c,d)}window.ba=class{constructor(b,a){this.i=b;this.V=a;this.gb=!1;this.Yb=()=>this.Qa()}Ka(){}Qa(){}};window.mc=class{constructor(){}};"use strict";class aa{constructor(b){this.ha=b;this.ya=!1;this.Ba=!0}}
function ca(b,a){const c=a.elementId,d=b.oa(c,a),e=new aa(d);b.I.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Ba=!!a.isVisible;d.addEventListener("focus",()=>{t(b,"elem-focused",c)});d.addEventListener("blur",()=>{t(b,"elem-blurred",c)});b.T&&document.body.appendChild(d)}function u(b,a,c){q(b,a,d=>{const e=v(b,d.elementId);return c(e,d)})}function v(b,a){b=b.I.get(a);if(!b)throw Error(`no element with id ${a}`);return b.ha}function t(b,a,c,d){d||(d={});d.elementId=c;l(b,a,d)}
window.Ma=class extends self.ba{constructor(b,a){super(b,a);this.I=new Map;this.T=!0;r(this,[["create",c=>ca(this,c)],["destroy",c=>{c=c.elementId;const d=v(this,c);this.Na(d);this.T&&d.parentElement.removeChild(d);this.I.delete(c)}],["set-visible",c=>{if(this.T){var d=this.I.get(c.elementId),e=d.ha;d.ya?e.style.display=c.isVisible?"":"none":d.Ba=!!c.isVisible}}],["update-position",c=>{if(this.T){var d=this.I.get(c.elementId),e=d.ha;e.style.left=c.left+"px";e.style.top=c.top+"px";e.style.width=c.width+
"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.ya||(d.ya=!0,d.Ba&&(e.style.display=""))}}],["update-state",c=>{const d=v(this,c.elementId);this.da(d,c)}],["focus",c=>{const d=v(this,c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=v(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{v(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{v(this,c.elementId).removeAttribute(c.name)}]]);
u(this,"get-element",c=>c)}oa(){throw Error("required override");}Na(){}da(){throw Error("required override");}};"use strict";const w=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent),da=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ea=0;
function y(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.bc?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.fc+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let fa=!1,ha=!1;function ia(){if(!fa){try{new Worker("blob://",{get type(){ha=!0}})}catch(b){}fa=!0}return ha}let z=new Audio;
const ja={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;async function ka(b){b=await la(b);return(new TextDecoder("utf-8")).decode(b)}
function la(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const A=[];let B=0;window.RealFile=window.File;const C=[],D=new Map,E=new Map;let ma=0;const na=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");na.push(b)};const oa=new Set(["cordova","playable-ad","instant-games"]);let pa=!1;
window.G=class b{constructor(a){this.l=a.ic;this.Y=null;this.o="";this.K=a.ec;this.aa={};this.Da=this.M=null;this.ga=[];this.j=this.F=null;this.hb=!1;this.W=null;this.J=-1;this.Wb=()=>this.Kb();this.Ga=[];this.Ia=null;this.kb=[];this.g=a.lb;this.Aa="file"===location.protocol.substr(0,4);!this.l||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ia()||(this.l=!1);this.l&&da&&(this.l=!1);if("playable-ad"===this.g||"instant-games"===this.g)this.l=!1;if("cordova"===this.g&&this.l)if(x){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.l=!1)}else this.l=!1;this.R()?self.chrome.webview.addEventListener("message",c=>this.Ya(c.data)):"macos-wkwebview"===this.g&&(self.C3WrapperOnMessage=c=>this.Ya(c));this.ia=this.A=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.h("runtime",
"cordova-fetch-local-file",c=>this.Gb(c));this.h("runtime","create-job-worker",()=>this.Hb());this.h("runtime","send-wrapper-extension-message",c=>this.Nb(c));"cordova"===this.g?document.addEventListener("deviceready",()=>this.Va(a)):this.Va(a)}Pa(){return w&&"cordova"===this.g}qa(){const a=navigator.userAgent;return w&&oa.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}ob(){return x}Oa(){return x&&oa.has(this.g)}R(){return"windows-webview2"===this.g||!!("preview"===this.g&&
window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}async Va(a){"macos-wkwebview"===this.g?this.S({type:"ready"}):this.R()&&(this.Qb(),this.kb=(await this.Fb()).registeredComponentIds);if("playable-ad"===this.g){this.A=self.c3_base64files;this.ia={};await this.xb();for(let d=0,e=a.N.length;d<e;++d){var c=a.N[d];this.ia.hasOwnProperty(c)?a.N[d]={bc:!0,fc:this.ia[c]}:this.A.hasOwnProperty(c)&&(a.N[d]=URL.createObjectURL(this.A[c]))}a.ma=[]}if("nwjs"===this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=
0;this.Ra(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.dc?this.o=a.dc:(c=location.origin,this.o=("null"===c?"file:///":c)+location.pathname,c=this.o.lastIndexOf("/"),-1!==c&&(this.o=this.o.substr(0,c+1)));a.kc&&(this.aa=a.kc);c=new MessageChannel;this.Y=c.port1;this.Y.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Jb(d));this.W=new self.qb(this);await qa(this.W);"object"===typeof window.StatusBar&&window.StatusBar.hide();
if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.l?await this.Eb(a,c.port2):await this.Db(a,c.port2)}ta(a){a=this.aa.hasOwnProperty(a)?this.aa[a]:a.endsWith("/workermain.js")&&this.aa.hasOwnProperty("workermain.js")?this.aa["workermain.js"]:"playable-ad"===this.g&&this.A.hasOwnProperty(a)?this.A[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async pa(a,
c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.g&&this.Aa)return a=await this.na(d.ac?a:this.K+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}v(){return Math.max(window.innerWidth,1)}u(){return Math.max(window.innerHeight,1)}Ta(a){var c=
this.o,d=location.href,e=this.v(),f=this.u(),g=window.devicePixelRatio,h=b.P(),k=a.pc,n=window.cr_previewImageBlobs||this.A,p=window.cr_previewProjectFileBlobs,Ca=window.cr_previewProjectFiles,Da=window.cr_swClientId||"";a=a.lb;var Ea=(new URLSearchParams(self.location.search)).has("debug"),M=this.W;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:n,previewProjectFileBlobs:p,previewProjectFileSWUrls:Ca,swClientId:Da,
exportType:a,isDebug:Ea,ife:!!self.oc,jobScheduler:{inputPort:M.za,outputPort:M.Fa,maxNumWorkers:M.Ub},supportedAudioFormats:ja,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.K+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.K+"opus.wasm.wasm",isFileProtocol:this.Aa,isiOSCordova:this.Pa(),isiOSWebView:this.qa(),isWebView2Wrapper:this.R(),wrapperComponentIds:this.kb,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Eb(a,c){const d=this.ta(a.jc);"preview"===this.g?
(this.M=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,k)=>{const n=p=>{this.M.removeEventListener("message",n);p.data&&"ok"===p.data.type?h():k()};this.M.addEventListener("message",n);this.M.postMessage({type:"construct-worker-init","import":(new URL(d,this.o)).toString()})})):this.M=await this.pa(d,this.o,{type:"module",name:"Runtime",ac:!0});this.j=document.createElement("canvas");this.j.style.display="none";const e=this.j.transferControlToOffscreen();document.body.appendChild(this.j);
window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.ma||[],g=a.N;f=await Promise.all(f.map(h=>this.H(h)));g=await Promise.all(g.map(h=>this.H(h)));if("cordova"===this.g)for(let h=0,k=a.la.length;h<k;++h){const n=a.la[h],p=n[0];if(p===a.Ja||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))n[1]=await this.H(p)}this.M.postMessage(Object.assign(this.Ta(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,
projectScripts:a.la,mainProjectScript:a.Ja,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...ra(this.W)]);this.ga=C.map(h=>new h(this));this.Sa();sa(this.F);self.c3_callFunction=(h,k)=>{var n=this.F;return n.i.rb(n.V,{name:h,params:k})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.ca("runtime","go-to-last-error-script"))}async Db(a,c){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&
self.C3_InsertHTMLPlaceholders();this.ga=C.map(g=>new g(this));this.Sa();var d=a.N.map(g=>"string"===typeof g?(new URL(g,this.o)).toString():g);if(Array.isArray(a.ma)){var e=[...a.ma].map(g=>g instanceof Blob?URL.createObjectURL(g):g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.H(g)));await Promise.all(d.map(g=>y(g)));d=self.C3_ProjectScriptsStatus;e=a.Ja;const f=a.la;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.H(h),await y(h),"preview"!==this.g||d[g]||this.Za(g,"main script did not run to completion")}catch(k){this.Za(g,
k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.H(h),await y(h);"preview"===this.g&&"object"!==typeof self.lc.nc?(this.fa(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Ta(a),{isInWorker:!1,messagePort:c,canvas:this.j,runOnStartupFunctions:na}),sa(this.F),
this.Xa(),this.Da=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Da,a))}Za(a,c){this.fa();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Xa(){this.fa()}fa(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Hb(){const a=await ta(this.W);return{outputPort:a,
transferables:[a]}}Bb(){if(this.l)throw Error("not available in worker mode");return this.Da}ca(a,c,d,e,f){this.Y.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}rb(a,c){const d=ma++,e=new Promise((f,g)=>{E.set(d,{resolve:f,reject:g})});this.Y.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:c,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Ib(a);if("result"===
c)this.Lb(a);else if("runtime-ready"===c)this.Mb();else if("alert-error"===c)this.fa(),alert(a.message);else if("creating-runtime"===c)this.Xa();else throw Error(`unknown message '${c}'`);}Ib(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=D.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.ea(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.ea(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,
h);this.ea(f,!1,""+h)}):this.ea(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}ea(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.Y.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Lb(a){const c=a.responseId,d=a.isOk;a=a.result;const e=E.get(c);d?e.resolve(a):e.reject(a);E.delete(c)}h(a,c,d){let e=D.get(a);e||(e=new Map,D.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);
e.set(c,d)}static O(a){if(C.includes(a))throw Error("DOM handler already added");C.push(a)}Sa(){for(const a of this.ga)if("runtime"===a.V){this.F=a;return}throw Error("cannot find runtime DOM handler");}Jb(a){this.ca("debugger","message",a)}Mb(){for(const a of this.ga)a.Ka()}static P(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||pa)}static $a(a){pa=!!a}Ra(a){this.Ga.push(a);this.va()}va(){-1===this.J&&this.Ga.length&&(this.J=requestAnimationFrame(this.Wb))}vb(){-1!==
this.J&&(cancelAnimationFrame(this.J),this.J=-1)}Kb(){this.J=-1;for(const a of this.Ga)a();this.va()}ua(){this.F.ua()}tb(){this.hb=!0}nb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}pb(a){return!this.nb(a)}async H(a){return"cordova"===this.g&&(a.startsWith("file:")||this.Aa&&this.pb(a))?(a.startsWith(this.o)&&(a=a.substr(this.o.length)),a=await this.na(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Gb(a){const c=a.filename;
switch(a.as){case "text":return await this.mb(c);case "buffer":return await this.na(c);default:throw Error("unsupported type");}}Ua(){const a=window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof a)throw Error("Permission API is not loaded");return a}Wa(a,c){a=a[c];if("string"!==typeof a)throw Error("Invalid permission name");return a}Cb(a){const c=this.Ua();return new Promise((d,e)=>c.checkPermission(this.Wa(c,a),f=>d(!!f.hasPermission),e))}Pb(a){const c=
this.Ua();return new Promise((d,e)=>c.requestPermission(this.Wa(c,a),f=>d(!!f.hasPermission),e))}async sb(a){if("cordova"!==this.g||this.Pa())return!0;for(const c of a)if(!await this.Cb(c)&&!1===await this.Pb(c))return!1;return!0}async ra(...a){if(!1===await this.sb(a))throw Error("Permission not granted");}La(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async mb(a){a=await this.La(a);return await ka(a)}sa(){if(A.length&&
!(8<=B)){B++;var a=A.shift();this.yb(a.filename,a.hc,a.$b)}}na(a){return new Promise((c,d)=>{A.push({filename:a,hc:e=>{B--;this.sa();c(e)},$b:e=>{B--;this.sa();d(e)}});this.sa()})}async yb(a,c,d){try{const e=await this.La(a),f=await la(e);c(f)}catch(e){d(e)}}Ya(a){if("entered-fullscreen"===a)b.$a(!0),F(this.F);else if("exited-fullscreen"===a)b.$a(!1),F(this.F);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.Ia(a),this.Ia=null):"extension-message"===c?this.ca("runtime",
"wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Nb(a){this.S({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}S(a){this.R()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.g&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Qb(){window.moveTo=(a,c)=>{this.S({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};
window.resizeTo=(a,c)=>{this.S({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Fb(){return this.R()?new Promise(a=>{this.Ia=a;this.S({type:"wrapper-init"})}):Promise.resolve()}async xb(){const a=[];for(const [c,d]of Object.entries(this.A))a.push(this.wb(c,d));await Promise.all(a)}async wb(a,c){if("object"===typeof c)this.A[a]=new Blob([c.str],{type:c.type}),this.ia[a]=c.str;else{let d=await this.Ab(c);d||(d=this.zb(c));this.A[a]=d}}async Ab(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}zb(a){a=this.Ob(a);return this.ub(a.data,a.cc)}Ob(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{cc:a,data:d}}ub(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const H=self.G;function ua(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const va=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},wa={dispatchUserScriptEvent:!0},J={dispatchRuntimeEvent:!0};
function xa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function ya(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function K(b){b=URL.createObjectURL(b);try{return await ya(b)}finally{URL.revokeObjectURL(b)}}
function za(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Aa(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await K(b);var d=await za(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await K(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await K(b)}
function L(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ba=new Set(["input","textarea","datalist","select"]),Fa=new Set(["canvas","body","html"]);function N(b){b.target.tagName&&Fa.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ga(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await K(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Aa(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let O=!1;document.addEventListener("pause",()=>O=!0);document.addEventListener("resume",()=>O=!1);function sa(b){b.eb=!0;b.Ca=b.i.v();b.X=b.i.u()}function F(b){if(!b.m){var a=H.P();a&&"any"!==b.Ha&&Ha(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.v(),innerHeight:b.u()})}}async function Ia(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ja(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ka(b){return await self.C3_GetSvgImageSize(b.blob)}function La(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Na(b){self.setTimeout(()=>{b.cb=!0},1E3);"cordova"===b.i.g?(document.addEventListener("pause",()=>P(b,!0)),document.addEventListener("resume",()=>P(b,!1))):document.addEventListener("visibilitychange",()=>P(b,"hidden"===document.visibilityState));b.ja=!("hidden"!==document.visibilityState&&!O);return{isSuspended:b.ja}}
function Oa(b){b.bb||(b.bb=!0,window.addEventListener("deviceorientation",a=>{b.m||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.m||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Pa(b){b.ab||(b.ab=!0,window.addEventListener("devicemotion",a=>{if(!b.m){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Qa(b){await xa(b.url)}
function Ra(b,a){b.fb=a.message;-1===b.xa&&(b.xa=setTimeout(()=>{b.xa=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.fb)},250))}function Q(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:H.P(),innerWidth:b.v(),innerHeight:b.u()})}function P(b,a){b.ja!==a&&((b.ja=a)?b.i.vb():b.i.va(),l(b,"visibilitychange",{hidden:a}))}
function Sa(b,a,c){"Backspace"===c.key&&N(c);if(!b.m){var d=va.get(c.code)||c.code;m(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}function R(b,a,c,d){b.m||ua(c)||m(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function S(b){window!==window.top&&window.focus();Ta(b.target)&&document.activeElement&&!Ta(document.activeElement)&&document.activeElement.blur()}
function T(b,a,c){if(!b.m){var d=0;"mouse"===c.pointerType&&(d=b.Z);m(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},I);"mouse"===c.pointerType&&(d="mousemove",
"pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),R(b,d,c,wa),b.Z=c.buttons)}}
function U(b,a,c){if(!b.m&&!ua(c)){var d=b.Z;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");m(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},I);b.Z=c.buttons;R(b,c.type,c,wa)}}
function V(b,a,c){if(!b.m)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];m(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.s,pageX:f.pageX,pageY:f.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
I)}}function W(b,a,c){document.body.style.transform="";b.s=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.s=a))}}function Ua(b,a,c,d){const e=b.v(),f=b.u();b.L=-1;e!=a||f!=c?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.P()}):10>d&&Va(b,e,f,d+1)}
function Va(b,a,c,d){-1!==b.L&&clearTimeout(b.L);b.L=setTimeout(()=>Ua(b,a,c,d),48)}
function Ha(b){b=b.Ha;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Ta(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.O(class extends self.ba{constructor(b){super(b,"runtime");this.ib=!0;this.eb=!1;this.L=-1;this.Ha="any";this.ja=this.ab=this.bb=!1;this.ka=document.createElement("div");this.ka.className="c3-screen-reader-text";this.ka.setAttribute("aria-live","polite");document.body.appendChild(this.ka);this.D=null;this.m=!1;this.fb="";this.xa=-1;this.cb=!1;this.Ca=b.v();this.X=b.u();this.s=this.$=0;b.h("canvas","update-size",d=>{var e=this.i;e.hb||(e=e.j,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.ib&&(e.style.display="",this.ib=!1))});b.h("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.h("runtime","load-webfonts",d=>Ia(d));b.h("runtime","raster-svg-image",d=>Ja(d));b.h("runtime","get-svg-image-size",
d=>Ka(d));b.h("runtime","set-target-orientation",d=>{this.Ha=d.targetOrientation});b.h("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.h("runtime","post-to-debugger",d=>La(d));b.h("runtime","go-to-script",d=>La(d));b.h("runtime","before-start-ticking",()=>Na(this));b.h("runtime","debug-highlight",d=>{if(d.show){this.D||(this.D=document.createElement("div"),this.D.id="inspectOutline",document.body.appendChild(this.D));var e=this.D;e.style.display="";e.style.left=d.left-
1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.D&&(this.D.style.display="none")});b.h("runtime","enable-device-orientation",()=>Oa(this));b.h("runtime","enable-device-motion",()=>Pa(this));b.h("runtime","add-stylesheet",d=>Qa(d));b.h("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.h("runtime","alert",d=>{alert(d.message)});b.h("runtime",
"screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.ka.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.h("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.h("runtime","set-exporting-to-video",d=>{this.m=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.tb()});b.h("runtime","export-to-video-progress",d=>Ra(this,d));b.h("runtime","exported-to-video",d=>{window.Zb({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.h("runtime","exported-to-image-sequence",d=>{window.Zb({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||L(e)||d.preventDefault()});const c=b.j;window.addEventListener("selectstart",N);window.addEventListener("gesturehold",N);c.addEventListener("selectstart",N);c.addEventListener("gesturehold",
N);window.addEventListener("touchstart",N,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",N,{passive:!1}),c.addEventListener("pointerdown",N)):c.addEventListener("touchstart",N);this.Z=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ga,{passive:!1});window.addEventListener("wheel",Ga,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.m&&this.eb){var d=this.v();var e=this.u();if(this.i.Oa()){if(this.cb){if(this.Ca===
d&&e<this.X){this.$=this.X-e;W(this,this.X,this.$);d=void 0;break a}0<this.$&&(this.$=0,W(this,e,this.$))}this.Ca=d;this.X=e}l(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.P()});this.i.qa()&&(-1!==this.L&&clearTimeout(this.L),Ua(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>F(this));window.addEventListener("webkitfullscreenchange",()=>F(this));window.addEventListener("mozfullscreenchange",()=>F(this));window.addEventListener("fullscreenerror",
d=>Q(this,d));window.addEventListener("webkitfullscreenerror",d=>Q(this,d));window.addEventListener("mozfullscreenerror",d=>Q(this,d));if(b.qa())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):L(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});this.Ea=new Set;this.Vb=new WeakSet;this.Tb=!1}Ka(){window.addEventListener("focus",()=>{l(this,"window-focus",null,J)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}l(this,"window-blur",{parentHasFocus:a},J);this.Z=0});window.addEventListener("focusin",a=>{a=a.target;(Ba.has(a.tagName.toLowerCase())||L(a))&&
l(this,"keyboard-blur",null,J)});window.addEventListener("keydown",a=>Sa(this,"keydown",a));window.addEventListener("keyup",a=>Sa(this,"keyup",a));window.addEventListener("dblclick",a=>R(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.m||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.s,pageX:a.pageX,pageY:a.pageY+this.s,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{S(a);T(this,"pointerdown",a)}),this.i.l&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{T(this,"pointermove",a)}):window.addEventListener("pointermove",a=>T(this,"pointermove",a)),window.addEventListener("pointerup",a=>T(this,"pointerup",a)),window.addEventListener("pointercancel",a=>T(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{S(a);U(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>U(this,"pointermove",
a)),window.addEventListener("mouseup",a=>U(this,"pointerup",a)),window.addEventListener("touchstart",a=>{S(a);V(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>V(this,"pointermove",a)),window.addEventListener("touchend",a=>V(this,"pointerup",a)),window.addEventListener("touchcancel",a=>V(this,"pointercancel",a)));const b=()=>this.ua();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.i.ob()&&!this.i.Oa()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{W(this,this.u(),navigator.virtualKeyboard.boundingRect.height)}))}v(){return this.i.v()}u(){return this.i.u()}ua(){var b=[...this.Ea];this.Ea.clear();if(!this.Tb)for(const a of b)(b=a.play())&&b.catch(()=>{this.Vb.has(a)||this.Ea.add(a)})}});"use strict";
async function qa(b){if(b.Rb)throw Error("already initialised");b.Rb=!0;var a=b.C.ta(("playable-ad"===b.C.g?b.C.K:"")+"dispatchworker.js");b.wa=await b.C.pa(a,b.U,{name:"DispatchWorker"});a=new MessageChannel;b.za=a.port1;b.wa.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Fa=await ta(b)}function ra(b){return[b.za,b.Fa]}
async function ta(b){const a=b.jb.length;var c=b.C.ta(("playable-ad"===b.C.g?b.C.K:"")+"jobworker.js");c=await b.C.pa(c,b.U,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.wa.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.jb.push(c);return e.port1}
self.qb=class{constructor(b){this.C=b;this.U=b.o;this.U="preview"===b.g?this.U+"workers/":this.U+b.K;this.Ub=Math.min(navigator.hardwareConcurrency||2,16);this.wa=null;this.jb=[];this.Fa=this.za=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.G({ic:!0,jc:"workermain.js",N:["scripts/c3runtime.js"],la:[],Ja:"",ec:"scripts/",ma:[],lb:"html5"}));"use strict";
self.G.O(class extends self.ba{constructor(b){super(b,"mouse");r(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.i.j.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{l(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{l(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function Wa(){const b=[],a=[];if(navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices){var c=await navigator.mediaDevices.enumerateDevices();for(const d of c){c=d.kind;const e={deviceId:d.deviceId,label:d.label,facing:d.facing||d.facingMode||""};"video"===c||"videoinput"===c?b.push(e):("audio"===c||"audioinput"===c)&&a.push(e)}}return{videoSources:b,audioSources:a}}
async function Xa(b,a,c){try{const d=b.i;"object"===typeof c.constraints.audio?await d.ra("CAMERA","RECORD_AUDIO","MODIFY_AUDIO_SETTINGS"):await d.ra("CAMERA");b.B=await navigator.mediaDevices.getUserMedia(c.constraints);a.srcObject=b.B;a.play();b.gb||(b.i.Ra(b.Yb),b.gb=!0);return{ok:!0}}catch(d){return console.warn("Error requesting camera: ",d),{ok:!1}}}
async function Ya(b,a,c){try{return await b.i.ra("RECORD_AUDIO","MODIFY_AUDIO_SETTINGS"),b.B=await navigator.mediaDevices.getUserMedia(c.constraints),a.c3_mic_stream=b.B,self.C3Audio_OnMicrophoneStream&&self.C3Audio_OnMicrophoneStream(b.B,c.tag),{ok:!0}}catch(d){return console.warn("Error requesting microphone: ",d),{ok:!1}}}
async function Za(b,a){const c=document.createElement("canvas");c.width=b.videoWidth;c.height=b.videoHeight;c.getContext("2d").drawImage(b,0,0,b.videoWidth,b.videoHeight);return{snapshotUrl:await $a(c,a.format,a.quality)}}function ab(b,a){a.srcObject&&(bb(b,a.srcObject),a.srcObject=null);a.c3_mic_stream&&(bb(b,a.c3_mic_stream),a.c3_mic_stream=null)}function bb(b,a){b.B===a&&(b.B=null);b=a.getTracks();for(let c=0,d=b.length;c<d;++c)b[c].stop()}
function $a(b,a,c){return new Promise(d=>{b.toBlob?b.toBlob(e=>d(URL.createObjectURL(e)),a,c):d(b.toDataURL(a,c))})}
self.G.O(class extends self.Ma{constructor(b){super(b,"user-media");this.T=!1;this.Sb=this.i.l;this.Xb=0;this.B=null;q(this,"get-media-sources",()=>Wa());u(this,"request-camera",(a,c)=>Xa(this,a,c));u(this,"request-microphone",(a,c)=>Ya(this,a,c));u(this,"snapshot",(a,c)=>Za(a,c));u(this,"stop",a=>ab(this,a));self.C3UserMedia_GetVideoElement=a=>v(this,a);self.C3UserMedia_GetLastMediaStream=()=>this.B}oa(b){const a=document.createElement("video");a.crossOrigin="anonymous";a.autoplay=!0;a.muted=!0;
a.playsInline=!0;a.addEventListener("canplaythrough",()=>{t(this,"video-ready",b,{width:a.videoWidth,height:a.videoHeight})});return a}da(){}Na(b){ab(this,b)}Qa(){const b={},a={sequenceNumber:this.Xb++,videoData:b},c=[],d=[];for(const [e,f]of this.I.entries()){const g=f.ha;if(!g.srcObject)continue;const h={width:g.videoWidth,height:g.videoHeight};this.Sb&&d.push(createImageBitmap(g).then(k=>{h.imageBitmap=k;c.push(k)}).catch(()=>{h.imageBitmap=null}));b[e.toString()]=h}Promise.all(d).then(()=>l(this,
"state",a,!1,c))}});"use strict";function X(b){b.stopPropagation()}function Y(b){const a=document.createElement("option");a.text=b;return a}function Z(b){const a=b.selectedIndex,c=[];for(let d=0,e=b.length;d<e;++d)b.options[d].selected&&c.push(d);return{selectedIndex:a,selectedIndices:c}}
self.G.O(class extends self.Ma{constructor(b){super(b,"list");u(this,"set-selected-index",(a,c)=>{a.selectedIndex=c.selectedIndex});u(this,"add-item",(a,c)=>{const d=c.index;c=Y(c.text);0>d?a.add(c):a.add(c,d)});u(this,"remove-item",(a,c)=>{a.remove(c.index)});u(this,"set-item",(a,c)=>{a.options[c.index].text=c.text});u(this,"clear",a=>{a.innerHTML=""});u(this,"load-state",(a,c)=>{a.innerHTML="";for(const d of c.items)a.add(Y(d));a.selectedIndex=c.selectedIndex;for(const d of c.selectedIndices)if(c=
a.options[d])c.selected=!0})}oa(b,a){const c=a.isDropdown,d=a.isMultiSelect,e=a.items,f=document.createElement("select");f.style.position="absolute";f.style.userSelect="none";f.style.webkitUserSelect="none";f.multiple=d;c||(f.size=2);for(const g of e)f.add(Y(g));f.addEventListener("pointerdown",X);f.addEventListener("pointermove",X);f.addEventListener("pointerrawupdate",X);f.addEventListener("pointerup",X);f.addEventListener("mousedown",X);f.addEventListener("mouseup",X);f.addEventListener("click",
g=>{g.stopPropagation();(g=Z(f))||(g={});g.elementId=b;m(this,"click",g)});f.addEventListener("dblclick",g=>{g.stopPropagation();(g=Z(f))||(g={});g.elementId=b;m(this,"dblclick",g)});f.addEventListener("change",()=>t(this,"change",b,Z(f)));a.id&&(f.id=a.id);a.className&&(f.className=a.className);this.da(f,a);return f}da(b,a){b.title=a.title;b.disabled=!a.isEnabled;b.multiple=!!a.isMultiSelect}});"use strict";
async function cb(b,a){a=a.type;let c=!0;0===a?c=await db():1===a&&(c=await eb());l(b,"permission-result",{type:a,result:c})}async function db(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function eb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.G.O(class extends self.ba{constructor(b){super(b,"touch");q(this,"request-permission",a=>cb(this,a))}});
