function l(b,a,c,d){b.o.kb(b.nb,a,c,d)}function n(b,a,c,d){b.o.ca?l(b,a,c,d):b.o.Ee()._OnMessageFromDOM({type:"event",component:b.nb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function p(b,a,c){b.o.C(b.nb,a,c)}function r(b,a){for(const [c,d]of a)p(b,c,d)}function aa(b){b.Tb||(b.o.qd(b.Xd),b.Tb=!0)}window.Ma=class{constructor(b,a){this.o=b;this.nb=a;this.Tb=!1;this.Xd=()=>this.Pa()}gd(){}Pa(){}};
window.nf=class{constructor(){this.cd=-1}j(){-1!==this.cd&&(self.clearTimeout(this.cd),this.cd=-1)}};"use strict";class ba{constructor(b){this.Kc=b;this.Nc=!1;this.Uc=!0}}function ca(b,a){const c=a.elementId,d=b.nc(c,a),e=new ba(d);b.qb.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Uc=!!a.isVisible;d.addEventListener("focus",()=>{da(b,"elem-focused",c)});d.addEventListener("blur",()=>{da(b,"elem-blurred",c)});b.Pb&&document.body.appendChild(d)}
function u(b,a,c){p(b,a,d=>{const e=v(b,d.elementId);return c(e,d)})}function v(b,a){b=b.qb.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Kc}function da(b,a,c,d){d||(d={});d.elementId=c;l(b,a,d)}function w(b,a,c,d){d||(d={});d.elementId=c;n(b,a,d)}
window.ld=class extends self.Ma{constructor(b,a){super(b,a);this.qb=new Map;this.Pb=!0;r(this,[["create",c=>ca(this,c)],["destroy",c=>{c=c.elementId;const d=v(this,c);this.Pb&&d.parentElement.removeChild(d);this.qb.delete(c)}],["set-visible",c=>{if(this.Pb){var d=this.qb.get(c.elementId),e=d.Kc;d.Nc?e.style.display=c.isVisible?"":"none":d.Uc=!!c.isVisible}}],["update-position",c=>{if(this.Pb){var d=this.qb.get(c.elementId),e=d.Kc;e.style.left=c.left+"px";e.style.top=c.top+"px";e.style.width=c.width+
"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.Nc||(d.Nc=!0,d.Uc&&(e.style.display=""))}}],["update-state",c=>{const d=v(this,c.elementId);this.Jb(d,c)}],["focus",c=>this.Ec(c)],["set-css-style",c=>{const d=v(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{v(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{v(this,c.elementId).removeAttribute(c.name)}]]);u(this,"get-element",
c=>c)}nc(){throw Error("required override");}Jb(){throw Error("required override");}Ec(b){var a=v(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const ea=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),fa=/android/i.test(navigator.userAgent),ha=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ja=0;
function ka(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.cf?new Promise(c=>{const d="c3_resolve_"+ja;++ja;self[d]=c;a.textContent=b.gf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let la=!1,ma=!1;function na(){if(!la){try{new Worker("blob://",{get type(){ma=!0}})}catch(b){}la=!0}return ma}let x=new Audio;
const oa={"audio/webm; codecs=opus":!!x.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!x.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!x.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!x.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!x.canPlayType("audio/mp4"),"audio/mpeg":!!x.canPlayType("audio/mpeg")};x=null;async function pa(b){b=await qa(b);return(new TextDecoder("utf-8")).decode(b)}
function qa(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const ra=[];let y=0;window.RealFile=window.File;const A=[],sa=new Map,ta=new Map;let wa=0;const xa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");xa.push(b)};const ya=new Set(["cordova","playable-ad","instant-games"]);let za=!1;
window.ia=class b{constructor(a){this.ca=a.jf;this.ya=null;this.ba="";this.bb=a.ff;this.Eb={};this.Va=this.va=null;this.Rb=[];this.I=this.oa=null;this.Rc=!1;this.Ed=0;this.tb=null;this.ab=-1;this.Ze=()=>this.Me();this.$a=[];this.dd=null;this.Yd=[];this.v=a.Zd;this.Ub="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&na()||(this.ca=!1);this.ca&&ha&&(this.ca=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.ca=!1;if("cordova"===
this.v&&this.ca)if(fa){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.wa()?self.chrome.webview.addEventListener("message",c=>this.vd(c.data)):"macos-wkwebview"===this.v&&(self.C3WrapperOnMessage=c=>this.vd(c));this.Xb=this.sa=null;"html5"!==this.v||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");
this.C("runtime","cordova-fetch-local-file",c=>this.Ie(c));this.C("runtime","create-job-worker",()=>this.Je());this.C("runtime","send-wrapper-extension-message",c=>this.Pe(c));"cordova"===this.v?document.addEventListener("deviceready",()=>this.td(a)):this.td(a)}j(){this.xc();this.ya&&(this.ya=this.ya.onmessage=null);this.va&&(this.va.terminate(),this.va=null);this.Va&&(this.Va.j(),this.Va=null);this.I&&(this.I.parentElement.removeChild(this.I),this.I=null)}te(){return ea&&"cordova"===this.v}tc(){const a=
navigator.userAgent;return ea&&ya.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}re(){return fa}nd(){return fa&&ya.has(this.v)}wa(){return"windows-webview2"===this.v||!!("preview"===this.v&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}async td(a){"macos-wkwebview"===this.v?this.Fa({type:"ready"}):this.wa()&&(this.Se(),this.Yd=(await this.He()).registeredComponentIds);if("playable-ad"===this.v){this.sa=self.c3_base64files;this.Xb={};await this.Ae();
for(let d=0,e=a.eb.length;d<e;++d){var c=a.eb[d];this.Xb.hasOwnProperty(c)?a.eb[d]={cf:!0,gf:this.Xb[c]}:this.sa.hasOwnProperty(c)&&(a.eb[d]=URL.createObjectURL(this.sa[c]))}a.lc=[]}if("nwjs"===this.v&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.qd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.ef?this.ba=a.ef:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.lf&&(this.Eb=a.lf);
c=new MessageChannel;this.ya=c.port1;this.ya.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Le(d));this.tb=new self.ue(this);await Aa(this.tb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ca?await this.Ge(a,c.port2):
await this.Fe(a,c.port2)}zc(a){a=this.Eb.hasOwnProperty(a)?this.Eb[a]:a.endsWith("/workermain.js")&&this.Eb.hasOwnProperty("workermain.js")?this.Eb["workermain.js"]:"playable-ad"===this.v&&this.sa.hasOwnProperty(a)?this.sa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async oc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.v&&this.Ub)return a=await this.Fb(d.bf?a:this.bb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=
new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}qa(){return Math.max(window.innerWidth,1)}ja(){return Math.max(window.innerHeight,1)}sd(a){var c=this.ba,d=location.href,e=this.qa(),f=this.ja(),g=window.devicePixelRatio,h=b.ib(),k=a.sf,m=window.cr_previewImageBlobs||this.sa,q=window.cr_previewProjectFileBlobs,C=window.cr_previewProjectFiles,z=window.cr_swClientId||
"";a=a.Zd;var t=(new URLSearchParams(self.location.search)).has("debug"),D=this.tb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:m,previewProjectFileBlobs:q,previewProjectFileSWUrls:C,swClientId:z,exportType:a,isDebug:t,ife:!!self.rf,jobScheduler:{inputPort:D.Qc,outputPort:D.Yc,maxNumWorkers:D.We},supportedAudioFormats:oa,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.bb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.bb+"opus.wasm.wasm",isFileProtocol:this.Ub,isiOSCordova:this.te(),isiOSWebView:this.tc(),isWebView2Wrapper:this.wa(),wrapperComponentIds:this.Yd,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ge(a,c){const d=this.zc(a.kf);"preview"===this.v?(this.va=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,k)=>{const m=q=>{this.va.removeEventListener("message",m);q.data&&"ok"===q.data.type?h():k()};this.va.addEventListener("message",m);this.va.postMessage({type:"construct-worker-init",
"import":(new URL(d,this.ba)).toString()})})):this.va=await this.oc(d,this.ba,{type:"module",name:"Runtime",bf:!0});this.I=document.createElement("canvas");this.I.style.display="none";const e=this.I.transferControlToOffscreen();document.body.appendChild(this.I);window.c3canvas=this.I;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.lc||[],g=a.eb;f=await Promise.all(f.map(h=>this.Qa(h)));g=await Promise.all(g.map(h=>this.Qa(h)));if("cordova"===this.v)for(let h=0,k=a.kc.length;h<
k;++h){const m=a.kc[h],q=m[0];if(q===a.ed||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))m[1]=await this.Qa(q)}this.va.postMessage(Object.assign(this.sd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.kc,mainProjectScript:a.ed,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...Ba(this.tb)]);this.Rb=A.map(h=>new h(this));this.rd();Ca(this.oa);self.c3_callFunction=(h,k)=>{var m=this.oa;return m.o.pd(m.nb,
"js-invoke-function",{name:h,params:k})};"preview"===this.v&&(self.goToLastErrorScript=()=>this.kb("runtime","go-to-last-error-script"))}async Fe(a,c){this.I=document.createElement("canvas");this.I.style.display="none";document.body.appendChild(this.I);window.c3canvas=this.I;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Rb=A.map(g=>new g(this));this.rd();var d=a.eb.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);if(Array.isArray(a.lc)){var e=[...a.lc].map(g=>
g instanceof Blob?URL.createObjectURL(g):g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.Qa(g)));await Promise.all(d.map(g=>ka(g)));d=self.C3_ProjectScriptsStatus;e=a.ed;const f=a.kc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Qa(h),await ka(h),"preview"!==this.v||d[g]||this.wd(g,"main script did not run to completion")}catch(k){this.wd(g,k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Qa(h),await ka(h);"preview"===this.v&&"object"!==typeof self.mf.pf?
(this.Lb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.sd(a),{isInWorker:!1,messagePort:c,canvas:this.I,runOnStartupFunctions:xa}),Ca(this.oa),this.ud(),this.Va=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Va,a))}wd(a,c){this.Lb();console.error(`[Preview] Failed to load project main script (${a}): `,
c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}ud(){this.Lb()}Lb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Je(){const a=await Da(this.tb);return{outputPort:a,transferables:[a]}}Ee(){if(this.ca)throw Error("not available in worker mode");return this.Va}kb(a,c,d,e,f){this.ya.postMessage({type:"event",component:a,handler:c,
dispatchOpts:e||null,data:d,responseId:null},f)}pd(a,c,d,e,f){const g=wa++,h=new Promise((k,m)=>{ta.set(g,{resolve:k,reject:m})});this.ya.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Ke(a);if("result"===c)this.Ne(a);else if("runtime-ready"===c)this.Oe();else if("alert-error"===c)this.Lb(),alert(a.message);else if("creating-runtime"===c)this.ud();else throw Error(`unknown message '${c}'`);
}Ke(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=sa.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Kb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Kb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Kb(f,!1,""+h)}):this.Kb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Kb(a,
c,d){let e;d&&d.transferables&&(e=d.transferables);this.ya.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ne(a){const c=a.responseId,d=a.isOk;a=a.result;const e=ta.get(c);d?e.resolve(a):e.reject(a);ta.delete(c)}C(a,c,d){let e=sa.get(a);e||(e=new Map,sa.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Ba(a){if(A.includes(a))throw Error("DOM handler already added");A.push(a)}rd(){for(const a of this.Rb)if("runtime"===a.nb){this.oa=
a;return}throw Error("cannot find runtime DOM handler");}Le(a){this.kb("debugger","message",a)}Oe(){for(const a of this.Rb)a.gd()}static ib(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||za)}static Mb(a){za=!!a}qd(a){this.$a.push(a);this.Gc()}Re(a){a=this.$a.indexOf(a);if(-1===a)throw Error("invalid callback");this.$a.splice(a,1);this.$a.length||this.xc()}Gc(){-1===this.ab&&this.$a.length&&(this.ab=requestAnimationFrame(this.Ze))}xc(){-1!==
this.ab&&(cancelAnimationFrame(this.ab),this.ab=-1)}Me(){this.ab=-1;for(const a of this.$a)a();this.Gc()}Ea(a){this.oa.Ea(a)}Oa(a){this.oa.Oa(a)}Fc(){this.oa.Fc()}Ib(a){this.oa.Ib(a)}se(){return!!oa["audio/webm; codecs=opus"]}async Te(a){a=await this.pd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}we(a){this.Rc=!0;this.Ed=a}qe(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}od(a){return!this.qe(a)}async Qa(a){return"cordova"===
this.v&&(a.startsWith("file:")||this.Ub&&this.od(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Fb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ie(a){const c=a.filename;switch(a.as){case "text":return await this.pe(c);case "buffer":return await this.Fb(c);default:throw Error("unsupported type");}}kd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async pe(a){a=
await this.kd(a);return await pa(a)}yc(){if(ra.length&&!(8<=y)){y++;var a=ra.shift();this.Be(a.filename,a.hf,a.af)}}Fb(a){return new Promise((c,d)=>{ra.push({filename:a,hf:e=>{y--;this.yc();c(e)},af:e=>{y--;this.yc();d(e)}});this.yc()})}async Be(a,c,d){try{const e=await this.kd(a),f=await qa(e);c(f)}catch(e){d(e)}}vd(a){if("entered-fullscreen"===a)b.Mb(!0),B(this.oa);else if("exited-fullscreen"===a)b.Mb(!1),B(this.oa);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.dd(a),
this.dd=null):"extension-message"===c?this.kb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Pe(a){this.Fa({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}Fa(a){this.wa()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.v&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Se(){window.moveTo=(a,c)=>
{this.Fa({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.Fa({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}He(){return this.wa()?new Promise(a=>{this.dd=a;this.Fa({type:"wrapper-init"})}):Promise.resolve()}async Ae(){const a=[];for(const [c,d]of Object.entries(this.sa))a.push(this.ze(c,d));await Promise.all(a)}async ze(a,c){if("object"===typeof c)this.sa[a]=new Blob([c.str],{type:c.type}),this.Xb[a]=c.str;else{let d=
await this.De(c);d||(d=this.Ce(c));this.sa[a]=d}}async De(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Ce(a){a=this.Qe(a);return this.ye(a.data,a.df)}Qe(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,
c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{df:a,data:d}}ye(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const E=self.ia;
function Ea(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const Fa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),F={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ga={dispatchUserScriptEvent:!0},Ha={dispatchRuntimeEvent:!0};
function Ia(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ja(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function G(b){b=URL.createObjectURL(b);try{return await Ja(b)}finally{URL.revokeObjectURL(b)}}
function Ka(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function La(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await G(b);var d=await Ka(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await G(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await G(b)}
function Na(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Oa=new Set(["input","textarea","datalist","select"]),Pa=new Set(["canvas","body","html"]);function I(b){b.target.tagName&&Pa.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Qa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await G(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await La(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ra=!1;document.addEventListener("pause",()=>Ra=!0);document.addEventListener("resume",()=>Ra=!1);function Ca(b){b.Dd=!0;b.Vc=b.o.qa();b.ub=b.o.ja()}function B(b){if(!b.$){var a=E.ib();a&&"any"!==b.ad&&Sa(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.qa(),innerHeight:b.ja()})}}async function Ta(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ua(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Va(b){return await self.C3_GetSvgImageSize(b.blob)}function Wa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Xa(b){self.setTimeout(()=>{b.Cd=!0},1E3);"cordova"===b.o.v?(document.addEventListener("pause",()=>Ya(b,!0)),document.addEventListener("resume",()=>Ya(b,!1))):document.addEventListener("visibilitychange",()=>Ya(b,"hidden"===document.visibilityState));b.ac=!("hidden"!==document.visibilityState&&!Ra);return{isSuspended:b.ac}}
function Za(b){b.yd||(b.yd=!0,window.addEventListener("deviceorientation",a=>{b.$||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},F)}),window.addEventListener("deviceorientationabsolute",a=>{b.$||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},F)}))}
function $a(b){b.xd||(b.xd=!0,window.addEventListener("devicemotion",a=>{if(!b.$){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},F)}}))}async function ab(b){await Ia(b.url)}
function bb(b,a){b.Fd=a.message;-1===b.Lc&&(b.Lc=setTimeout(()=>{b.Lc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Fd)},250))}function cb(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:E.ib(),innerWidth:b.qa(),innerHeight:b.ja()})}function Ya(b,a){b.ac!==a&&((b.ac=a)?b.o.xc():b.o.Gc(),l(b,"visibilitychange",{hidden:a}))}
function db(b,a,c){"Backspace"===c.key&&I(c);if(!b.$){var d=Fa.get(c.code)||c.code;n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},F)}}function eb(b,a,c,d){b.$||Ea(c)||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function gb(b){window!==window.top&&window.focus();hb(b.target)&&document.activeElement&&!hb(document.activeElement)&&document.activeElement.blur()}
function J(b,a,c){if(!b.$){var d=0;"mouse"===c.pointerType&&(d=b.zb);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},F);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),eb(b,d,c,Ga),b.zb=c.buttons)}}
function ib(b,a,c){if(!b.$&&!Ea(c)){var d=b.zb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");n(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},F);b.zb=c.buttons;eb(b,c.type,c,Ga)}}
function K(b,a,c){if(!b.$)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];n(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
F)}}function jb(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function kb(b,a,c,d){const e=b.qa(),f=b.ja();b.cb=-1;e!=a||f!=c?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:E.ib()}):10>d&&lb(b,e,f,d+1)}
function lb(b,a,c,d){-1!==b.cb&&clearTimeout(b.cb);b.cb=setTimeout(()=>kb(b,a,c,d),48)}
function Sa(b){b=b.ad;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function hb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
E.Ba(class extends self.Ma{constructor(b){super(b,"runtime");this.Kd=!0;this.Dd=!1;this.cb=-1;this.ad="any";this.ac=this.xd=this.yd=!1;this.hc=document.createElement("div");this.hc.className="c3-screen-reader-text";this.hc.setAttribute("aria-live","polite");document.body.appendChild(this.hc);this.Ia=null;this.$=!1;this.Fd="";this.Lc=-1;this.Cd=!1;this.Vc=b.qa();this.ub=b.ja();this.da=this.Db=0;b.C("canvas","update-size",d=>{var e=this.o;e.Rc||(e=e.I,e.style.width=d.styleWidth+"px",e.style.height=
d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Kd&&(e.style.display="",this.Kd=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Ta(d));b.C("runtime","raster-svg-image",d=>Ua(d));b.C("runtime",
"get-svg-image-size",d=>Va(d));b.C("runtime","set-target-orientation",d=>{this.ad=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Wa(d));b.C("runtime","go-to-script",d=>Wa(d));b.C("runtime","before-start-ticking",()=>Xa(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ia||(this.Ia=document.createElement("div"),this.Ia.id="inspectOutline",document.body.appendChild(this.Ia));var e=this.Ia;e.style.display=
"";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ia&&(this.Ia.style.display="none")});b.C("runtime","enable-device-orientation",()=>Za(this));b.C("runtime","enable-device-motion",()=>$a(this));b.C("runtime","add-stylesheet",d=>ab(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>this.Cc(d));
b.C("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.hc.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.$=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.o.I.style.display="";this.o.we(d.duration)});b.C("runtime","export-to-video-progress",d=>bb(this,d));b.C("runtime","exported-to-video",d=>{window.$e({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.$e({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Na(e)||d.preventDefault()});const c=b.I;window.addEventListener("selectstart",I);window.addEventListener("gesturehold",I);c.addEventListener("selectstart",I);c.addEventListener("gesturehold",
I);window.addEventListener("touchstart",I,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",I,{passive:!1}),c.addEventListener("pointerdown",I)):c.addEventListener("touchstart",I);this.zb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Qa,{passive:!1});window.addEventListener("wheel",Qa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.$&&this.Dd){var d=this.qa();var e=this.ja();if(this.o.nd()){if(this.Cd){if(this.Vc===
d&&e<this.ub){this.Db=this.ub-e;jb(this,this.ub,this.Db);d=void 0;break a}0<this.Db&&(this.Db=0,jb(this,e,this.Db))}this.Vc=d;this.ub=e}l(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:E.ib()});this.o.tc()&&(-1!==this.cb&&clearTimeout(this.cb),kb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>B(this));window.addEventListener("webkitfullscreenchange",()=>B(this));window.addEventListener("mozfullscreenchange",()=>
B(this));window.addEventListener("fullscreenerror",d=>cb(this,d));window.addEventListener("webkitfullscreenerror",d=>cb(this,d));window.addEventListener("mozfullscreenerror",d=>cb(this,d));if(b.tc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Na(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});this.Wa=new Set;this.Zb=new WeakSet;this.xa=!1}gd(){window.addEventListener("focus",()=>{l(this,"window-focus",null,Ha)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}l(this,"window-blur",{parentHasFocus:a},Ha);this.zb=0});window.addEventListener("focusin",a=>{a=a.target;(Oa.has(a.tagName.toLowerCase())||Na(a))&&
l(this,"keyboard-blur",null,Ha)});window.addEventListener("keydown",a=>db(this,"keydown",a));window.addEventListener("keyup",a=>db(this,"keyup",a));window.addEventListener("dblclick",a=>eb(this,"dblclick",a,F));window.addEventListener("wheel",a=>{this.$||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},F)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{gb(a);J(this,"pointerdown",a)}),this.o.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{J(this,"pointermove",a)}):window.addEventListener("pointermove",a=>J(this,"pointermove",a)),window.addEventListener("pointerup",a=>J(this,"pointerup",a)),window.addEventListener("pointercancel",a=>J(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{gb(a);ib(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>ib(this,
"pointermove",a)),window.addEventListener("mouseup",a=>ib(this,"pointerup",a)),window.addEventListener("touchstart",a=>{gb(a);K(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>K(this,"pointermove",a)),window.addEventListener("touchend",a=>K(this,"pointerup",a)),window.addEventListener("touchcancel",a=>K(this,"pointercancel",a)));const b=()=>this.Fc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.o.re()&&!this.o.nd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{jb(this,this.ja(),navigator.virtualKeyboard.boundingRect.height)}))}qa(){return this.o.qa()}ja(){return this.o.ja()}Fc(){var b=[...this.Wa];this.Wa.clear();if(!this.xa)for(const a of b)(b=a.play())&&b.catch(()=>{this.Zb.has(a)||this.Wa.add(a)})}Ea(b){if("function"!==typeof b.play)throw Error("missing play function");
this.Zb.delete(b);let a;try{a=b.play()}catch(c){this.Wa.add(b);return}a&&a.catch(()=>{this.Zb.has(b)||this.Wa.add(b)})}Oa(b){this.Wa.delete(b);this.Zb.add(b)}Ib(b){this.xa=!!b}Cc(b){alert(b.message)}});"use strict";
async function Aa(b){if(b.Ue)throw Error("already initialised");b.Ue=!0;var a=b.za.zc(("playable-ad"===b.za.v?b.za.bb:"")+"dispatchworker.js");b.Jc=await b.za.oc(a,b.mb,{name:"DispatchWorker"});a=new MessageChannel;b.Qc=a.port1;b.Jc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Yc=await Da(b)}function Ba(b){return[b.Qc,b.Yc]}
async function Da(b){const a=b.Ld.length;var c=b.za.zc(("playable-ad"===b.za.v?b.za.bb:"")+"jobworker.js");c=await b.za.oc(c,b.mb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Jc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Ld.push(c);return e.port1}
self.ue=class{constructor(b){this.za=b;this.mb=b.ba;this.mb="preview"===b.v?this.mb+"workers/":this.mb+b.bb;this.We=Math.min(navigator.hardwareConcurrency||2,16);this.Jc=null;this.Ld=[];this.Yc=this.Qc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ia({jf:!0,kf:"workermain.js",eb:["scripts/c3runtime.js"],kc:[],ed:"",ff:"scripts/",lc:[],Zd:"html5"}));"use strict";
self.ia.Ba(class extends self.Ma{constructor(b){super(b,"mouse");r(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.o.I.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{l(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{l(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function mb(b,a){a=a.type;let c=!0;0===a?c=await nb():1===a&&(c=await ob());l(b,"permission-result",{type:a,result:c})}async function nb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function ob(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.ia.Ba(class extends self.Ma{constructor(b){super(b,"touch");p(this,"request-permission",a=>mb(this,a))}});"use strict";function L(b){b.stopPropagation()}function pb(b){13!==b.which&&27!==b.which&&b.stopPropagation()}
self.ia.Ba(class extends self.ld{constructor(b){super(b,"text-input");u(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}nc(b,a){let c;const d=a.type;"textarea"===d?(c=document.createElement("textarea"),c.style.resize="none"):(c=document.createElement("input"),c.type=d);c.style.position="absolute";c.autocomplete="off";c.addEventListener("pointerdown",L);c.addEventListener("pointermove",L);c.addEventListener("pointerrawupdate",L);c.addEventListener("pointerup",L);c.addEventListener("mousedown",
L);c.addEventListener("mouseup",L);c.addEventListener("keydown",pb);c.addEventListener("keyup",pb);c.addEventListener("click",e=>{e.stopPropagation();w(this,"click",b)});c.addEventListener("dblclick",e=>{e.stopPropagation();w(this,"dblclick",b)});c.addEventListener("input",()=>da(this,"change",b,{text:c.value}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.Jb(c,a);return c}Jb(b,a){b.value=a.text;b.placeholder=a.placeholder;b.title=a.title;b.disabled=!a.isEnabled;b.readOnly=a.isReadOnly;
b.spellcheck=a.spellCheck;a=a.maxLength;0>a?b.removeAttribute("maxlength"):b.setAttribute("maxlength",a)}});"use strict";function qb(b){b.replaceChildren?b.replaceChildren():b.innerHTML=""}
function M(b){b=Array.from(b.querySelectorAll("script:not([c3-executed])"));for(const c of b){b=c.parentNode;var a=b.replaceChild;const d=document.createElement("script");d.text=c.text;const e=c.attributes;for(let f=0,g=e.length;f<g;++f){const h=e[f];d.setAttribute(h.name,h.value)}d.setAttribute("c3-executed","");a.call(b,d,c)}}function N(b,a,c){return a?c?Array.from(b.querySelectorAll(a)):(b=b.querySelector(a))?[b]:[]:[b]}
function O(b){return b?{isOk:!0,html:b.innerHTML,text:b.textContent}:{isOk:!1}}
self.ia.Ba(class extends self.ld{constructor(b){super(b,"html-element");u(this,"set-content",(a,c)=>{{const e=c.str,f=c.type,g=c.selector;c=c["is-all"];try{const h=N(a,g,c);if(0===h.length)var d=O(null);else{for(const k of h)"html"===f?(k.innerHTML=e,M(k)):k.textContent=e;d=O(a)}}catch(h){console.warn("[HTML element] Failed to set content: ",h),d=O(null)}}return d});u(this,"insert-content",(a,c)=>{{const e=c.str,f=c.type,g=c["at-end"]?"beforeend":"afterbegin",h=c.selector;c=c["is-all"];try{const k=
N(a,h,c);if(0===k.length)var d=O(null);else{for(const m of k)"html"===f?(m.insertAdjacentHTML(g,e),M(m)):m.insertAdjacentText(g,e);d=O(a)}}catch(k){console.warn("[HTML element] Failed to insert content: ",k),d=O(null)}}return d});u(this,"remove-content",(a,c)=>{{const e=c["is-clear"],f=c.selector;c=c["is-all"];if(f)try{const g=N(a,f,c);if(0===g.length)var d=O(null);else{for(const h of g)e?qb(h):h.remove();d=O(a)}}catch(g){console.warn("[HTML element] Failed to remove content: ",g),d=O(null)}else qb(a),
d=O(a)}return d});u(this,"set-content-class",(a,c)=>{{const e=c.mode,f=c["class-array"],g=c.selector;c=c["is-all"];try{const h=N(a,g,c);if(0===h.length)var d=O(null);else{for(const k of h)for(const m of f)switch(e){case "add":k.classList.add(m);break;case "toggle":k.classList.toggle(m);break;case "remove":k.classList.remove(m)}d=O(a)}}catch(h){console.warn("[HTML element] Failed to set class: ",h),d=O(null)}}return d});u(this,"set-content-attribute",(a,c)=>{{const e=c.mode,f=c.attribute,g=c.value,
h=c.selector;c=c["is-all"];try{const k=N(a,h,c);if(0===k.length)var d=O(null);else{for(const m of k)switch(e){case "set":m.setAttribute(f,g);break;case "remove":m.removeAttribute(f)}d=O(a)}}catch(k){console.warn("[HTML element] Failed to set attribute: ",k),d=O(null)}}return d});u(this,"set-content-css-style",(a,c)=>{{const e=c.prop,f=c.value,g=c.selector;c=c["is-all"];try{const h=N(a,g,c);if(0===h.length)var d=O(null);else{for(const k of h)e.startsWith("--")?k.style.setProperty(e,f):k.style[e]=f;
d=O(a)}}catch(h){console.warn("[HTML element] Failed to set style: ",h),d=O(null)}}return d});u(this,"get-element-box",(a,c)=>{(a=(c=c.selector)?a.querySelector(c):a)?(a=a.getBoundingClientRect(),a={isOk:!0,left:a.left,top:a.top,right:a.right,bottom:a.bottom}):a={isOk:!1};return a});u(this,"insert-img-element",(a,c)=>{a:{const e=c.blobUrl;var d=c.width;const f=c.height,g=c.selector,h=c.insertAt;let k=a;if(g&&(k=a.querySelector(g),!k)){a={isOk:!1};break a}d=new Image(d,f);d.src=e;c.id&&(d.id=c.id);
c["class"]&&(d.className=c["class"]);0===h?k.prepend(d):1===h?k.append(d):k.replaceChildren?k.replaceChildren(d):(qb(k),k.append(d));a=O(a)}return a});u(this,"set-scroll-position",(a,c)=>{a:{const d=c.selector,e=c.direction;c=c.position;if(d&&(a=a.querySelector(d),!a)){c=void 0;break a}"left"===e?a.scrollLeft=c:a.scrollTop=c;c=void 0}return c})}nc(b,a){const c=document.createElement(a.tag);a["style-attribute"]&&c.setAttribute("style",a["style-attribute"]);c.style.position="absolute";var d=a["stop-input-events-mode"];
if(0<d){let e=null;1===d?e=f=>{f.target!==c&&f.stopPropagation()}:2===d&&(e=f=>f.stopPropagation());c.addEventListener("pointerdown",e);c.addEventListener("pointermove",e);c.addEventListener("pointerrawupdate",e);c.addEventListener("pointerup",e);c.addEventListener("mousedown",e);c.addEventListener("mouseup",e);c.addEventListener("dblclick",e)}a["allow-context-menu"]&&c.addEventListener("contextmenu",e=>e.stopPropagation());c.addEventListener("click",e=>{e=e.target;const f=[];for(;e;){f.push({targetId:"string"===
typeof e.id?e.id:"",targetClass:"string"===typeof e.className?e.className:""});if(e===c)break;e=e.parentNode}w(this,"click",b,{chain:f})});c.addEventListener("animationend",e=>{const f=e.target;w(this,"animationend",b,{targetId:"string"===typeof f.id?f.id:"",targetClass:"string"===typeof f.className?f.className:"",animationName:e.animationName})});a.id&&(c.id=a.id);a.className&&(c.className=a.className);a["css-color"]&&(c.style.color=a["css-color"]);a["css-background-color"]&&(c.style.backgroundColor=
a["css-background-color"]);a["allow-text-selection"]||(c.style.userSelect="none",c.style.webkitUserSelect="none");d=a.str;"html"===a.type?(c.innerHTML=d,M(c)):c.textContent=d;w(this,"initial-content",b,{html:c.innerHTML,text:c.textContent});return c}Jb(b,a){b.innerHTML=a.html;M(b)}});"use strict";const rb=180/Math.PI;
async function sb(b,a){if(a.isiOSCordova||a.isSafari)b.cc=!0;b.bd=a.timeScaleMode;b.Qd=["equalpower","HRTF","soundfield"][a.panningModel];b.Bd=["linear","inverse","exponential"][a.distanceModel];b.Rd=a.refDistance;b.Pd=a.maxDistance;b.Td=a.rolloffFactor;if(b.o.Rc)b.cc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.o.Ed)});else{var c={latencyHint:a.latencyHint};b.Wd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");tb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&tb(b);l(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Sa=b.g.createGain();b.Sa.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ea);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function ub(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,m=a.pos,q=a.panning,C=a.stereoPan;let z=a.off;0<z&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),z=z-a.performanceTime/1E3+a.contextTime):z=z-performance.now()/1E3+b.g.currentTime);b.Md=g.slice(0);vb(b,g);try{b.R=await wb(b,c,d,e,g,f);if(q){Q(b.R,!0);var t=b.R,D=q.innerAngle,ua=q.outerAngle,va=q.outerGain;if(t.sb){xb(t,q.x,q.y,q.z,q.angle);var H=self.fb.xe;t.ta[0]!==H(D)&&
(t.ta[0]=H(D),t.F.coneInnerAngle=H(D));t.ta[1]!==H(ua)&&(t.ta[1]=H(ua),t.F.coneOuterAngle=H(ua));t.ta[2]!==va&&(t.ta[2]=va,t.F.coneOuterGain=va)}q.hasOwnProperty("uid")&&(b.R.ra=q.uid)}else"number"===typeof C&&0!==C?(R(b.R,!0),yb(b.R,C)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,k,m,z)}catch(Lb){console.error("[Construct] Audio: error starting playback: ",Lb);return}finally{c=g.join(" ");d=b.Bb.get(c);if(!d)throw Error("expected pending tag");d.fd--;0===d.fd&&(d.resolve(),b.Bb.delete(c))}aa(b)}
async function zb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await Ab(b,c);for(const h of S(b,c))if(!h.Ua){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.La=d;h.Ta=g;h.Vd=a}T(b)}async function Bb(b,a){const c=a.tags;a=a.rate;await Ab(b,c);for(const d of S(b,c))d.na!==a&&(d.na=a,d.Ga())}async function Cb(b,a){const c=a.tags;a=a.pos;await Ab(b,c);for(const d of S(b,c))d.uc(a)}
async function Db(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await wb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function Eb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.la.indexOf(a),-1!==a&&b.la.splice(a,1)}
async function Fb(b,a){const c=a.type;var d=a.tags;const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.ee(b,...e);else if("delay"===c)d=new self.ce(b,...e);else if("convolution"===c){var g=d=new self.be(b,f.ka,...e),h=a.bufferType;g.zd=a.bufferOriginalUrl;g.Ad=h}else if("flanger"===c)d=new self.fe(b,...e);else if("phaser"===
c)d=new self.he(b,...e);else if("gain"===c)d=new self.ge(b,...e);else if("stereopan"===c)d=new self.je(b,...e);else if("tremolo"===c)d=new self.ke(b,...e);else if("ringmod"===c)d=new self.ie(b,...e);else if("distortion"===c)d=new self.de(b,...e);else if("compressor"===c)d=new self.ae(b,...e);else if("analyser"===c)d=new self.$d(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let m=g.ma.get(h);m||(m=[],g.ma.set(h,m));d.Jd=m.length;d.$c=h;m.push(d);Gb(g,h)}Hb(b)}
async function Ib(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ca()&&1===c||!e.Ca()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ma.values())for(const g of f)g.j();b.ma.clear();b.ic=a.timeScale;b.Mc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ea[e]=d[e];b.g.listener.setOrientation(...b.ea)}b.xa=a.isSilent;b.o.Ib(b.xa);b.Yb=a.masterVolume;b.Sa.gain.value=
b.Yb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>Fb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Jb(b,f,c)));T(b)}
async function Kb(b,a){try{const c=b.g.suspend(a.time);b.Id?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.o.kb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Mb(d)),b.Id=!0);await c}catch(c){Mb(c)}}
function tb(b){b.Sb||(b.Pc=!1,window.addEventListener("pointerup",b.Aa,!0),window.addEventListener("touchend",b.Aa,!0),window.addEventListener("click",b.Aa,!0),window.addEventListener("keydown",b.Aa,!0),b.Sb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.la)if(g.hb()===c)return await Nb(g),g;if(f)return null;if(e&&(b.cc||b.Hd)){f=0;for(let h=0,k=b.la.length;h<k;++h)g=b.la[h],b.la[f]=g,g.Ca()?g.j():++f;b.la.length=f}f="audio/webm; codecs=opus"===d&&!b.Wd;e&&f&&(b.Hd=!0);c=!e||b.cc||f?new self.ne(b,a,c,d,e,f):new self.le(b,a,c,d,e);b.la.push(c);await Nb(c);b.Od.has(a)||(l(b,"buffer-metadata",{originalUrl:a,duration:c.ha()}),b.Od.add(a));return c}
function Ob(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Pb(b,a){return(a=b.ma.get(a.toLowerCase()))?a[0].N():b.ga()}function Gb(b,a){a=a.toLowerCase();let c=b.ga();var d=b.ma.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ga()):e.U(d[f+1].N())}}for(const f of Qb(b,a))d=c,e=f.fa||f.F||f.G,e.disconnect(),e.connect(d);b.Ja&&b.Wc===a&&(b.Ja.disconnect(),b.Ja.connect(c))}
function*Qb(b,a){if(a)for(const c of b.H)Ob(0<c.pa.length?c.pa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Rb(b,a,c){return c?b.o.Te(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Sb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.pa;var c=a;for(const e of c){c=!1;for(const f of b)if(Ob(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function wb(b,a,c,d,e,f){for(const g of b.H)if(g.hb()===c&&(g.mc()||f))return g.pa=e,g;a=await P(b,a,c,d,f);e="html5"===a.Hc?new self.me(a.u,a,e):new self.oe(a.u,a,e);b.H.push(e);return e}
function vb(b,a){a=a.join(" ");let c=b.Bb.get(a);if(!c){let d=null;c={fd:0,promise:new Promise(e=>d=e),resolve:d};b.Bb.set(a,c)}c.fd++}function Ab(b,a){return(b=b.Bb.get((0===a.length?b.Md:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Ra.size)aa(b);else for(const a of b.H)if(!a.J&&!a.O()){aa(b);break}}function Tb(b,a,c,d){l(b,"trigger",{type:a,tags:c,aiid:d})}function Hb(b){b.Sc||(b.Sc=!0,Promise.resolve().then(()=>Ub(b)))}
function Ub(b){const a={};for(const [c,d]of b.ma)a[c]=d.map(e=>e.gb());l(b,"fxstate",{fxstate:a});b.Sc=!1}
async function Jb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,m=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await wb(b,d,e,f,h,g)}catch(C){console.error("[Construct] Audio: error loading audio state: ",C);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Ya[0]=f[0],b.Ya[1]=f[1],b.Ya[2]=f[2],f=d.orient,b.Xa[0]=f[0],b.Xa[1]=f[1],b.Xa[2]=f[2],e.setPosition(...b.Ya),e.setOrientation(...b.Xa),b.ta[0]=d.cia,b.ta[1]=d.coa,b.ta[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.ra=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),yb(b,d));c.Play(k,m,q,0);a.isPlaying||c.jb();c.Bc(a)}}}function Mb(b){console.error("[Audio] Offline rendering error: ",b)}
self.fb=class extends self.Ma{constructor(b){super(b,"audio");this.Sa=this.g=null;this.Sb=this.Pc=!1;this.Aa=()=>{if(!this.Pc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Sb&&(this.Pc=!0,window.removeEventListener("pointerup",this.Aa,!0),window.removeEventListener("touchend",this.Aa,!0),window.removeEventListener("click",this.Aa,!0),window.removeEventListener("keydown",
this.Aa,!0),this.Sb=!1)}};this.la=[];this.H=[];this.R=null;this.Md=[];this.Od=new Set;this.Nd=-1;this.Bb=new Map;this.Yb=1;this.xa=!1;this.bd=0;this.ic=1;this.Mc=0;this.Qd="HRTF";this.Bd="inverse";this.Rd=600;this.Pd=1E4;this.Td=1;this.aa=[0,0,0];this.ea=[0,0,-1,0,1,0];this.Hd=this.cc=!1;this.Wd=this.o.se();this.ma=new Map;this.Ra=new Set;this.Id=this.Sc=!1;this.Wc="";this.Ja=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ja&&this.Ja.disconnect();this.Wc=c.toLowerCase();this.Ja=this.g.createMediaStreamSource(a);
this.Ja.connect(Pb(this,this.Wc))};this.Qb=null;self.C3Audio_GetOutputStream=()=>{this.Qb||(this.Qb=this.g.createMediaStreamDestination(),this.Sa.connect(this.Qb));return this.Qb.stream};self.C3Audio_DOMInterface=this;r(this,[["create-audio-context",a=>sb(this,a)],["play",a=>ub(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Da()}],["stop-all",()=>{for(const a of this.H)a.Da()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.jb():d.Hb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>zb(this,a)],["set-master-volume",a=>{this.Yb=a.vol;this.Sa.gain.value=this.Yb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Vb(d,a)}],["set-silent",a=>{this.xa=a.isSilent;this.o.Ib(this.xa);for(const c of this.H)c.Nb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.vc(a)}],["set-playback-rate",a=>Bb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),yb(d,a)}],["seek",a=>Cb(this,a)],["preload",a=>Db(this,a)],["unload",a=>Eb(this,a)],["unload-all",()=>{for(const a of this.la)a.j();this.la.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.wc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>Fb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ma.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);Hb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ma.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ma.delete(a);Gb(this,a)}}],["tick",a=>{this.ic=a.timeScale;this.Mc=a.gameTime;this.Nd=a.tickCount;if(0!==this.bd)for(var c of this.H)c.Ga();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ea[0]!==
c[0]||this.ea[1]!==c[1]||this.ea[2]!==c[2]||this.ea[3]!==c[3]||this.ea[4]!==c[4]||this.ea[5]!==c[5])){for(let d=0;6>d;++d)this.ea[d]=c[d];this.g.listener.setOrientation(...this.ea)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.ra===a&&xb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Ib(this,a)],["offline-render-audio",a=>Kb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ga(){return this.Sa}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ga()}Gb(){return this.xa}Ea(b){this.o.Ea(b)}Oa(b){this.o.Oa(b)}Pa(){for(var b of this.Ra)b.Pa();
b=this.g.currentTime;for(var a of this.H)a.Pa(b);a=this.H.filter(c=>!c.J&&!c.O()).map(c=>c.gb());l(this,"state",{tickCount:this.Nd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ra].map(c=>({tag:c.$c,index:c.Jd,peak:c.Za,rms:c.Sd,binCount:c.l.frequencyBinCount,freqBins:c.Gd}))});0===a.length&&0===this.Ra.size&&this.Tb&&(this.o.Re(this.Xd),this.Tb=!1)}static xe(b){return b*rb}static md(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static ve(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.ia.Ba(self.fb);"use strict";function Nb(b){b.Wb||(b.Wb=b.Ac());return b.Wb}self.hd=class{constructor(b,a,c,d,e){this.u=b;this.Ye=a;this.Ka=c;this.T=d;this.Ve=e;this.Hc="";this.Wb=null}j(){this.Wb=this.u=null}Ac(){}V(){return this.u.V()}qc(){return this.Ye}hb(){return this.Ka}pc(){return this.T}Ca(){return this.Ve}ha(){}};"use strict";
self.le=class extends self.hd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Hc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.vb=this.wb=null;this.M.addEventListener("canplaythrough",()=>!0);this.Ab=this.V().createGain();this.yb=null;this.M.addEventListener("canplay",()=>{this.wb&&(this.wb(),this.vb=this.wb=null);!this.yb&&this.M&&(this.yb=this.V().createMediaElementSource(this.M),this.yb.connect(this.Ab))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ka}' error: `,f);this.vb&&(this.vb(f),this.vb=this.wb=null)})}j(){Sb(this.u,this);this.Ab.disconnect();this.Ab=null;this.yb.disconnect();this.yb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}Ac(){return new Promise((b,a)=>{this.wb=b;this.vb=a;this.M.src=this.Ka})}W(){return this.M}ha(){return this.M.duration}};"use strict";
async function Wb(b){if(b.Ha)return b.Ha;var a=b.u.o;if("cordova"===a.v&&a.od(b.Ka)&&a.Ub)b.Ha=await a.Fb(b.Ka);else{a=await fetch(b.Ka);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ha=await a.arrayBuffer()}}async function Xb(b){if(b.ka)return b.ka;b.ka=await Rb(b.u,b.Ha,b.Xe);b.Ha=null}
self.ne=class extends self.hd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Hc="webaudio";this.ka=this.Ha=null;this.Xe=!!f}j(){Sb(this.u,this);this.ka=this.Ha=null;super.j()}async Ac(){try{await Wb(this),await Xb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ka}': `,b)}}ha(){return this.ka?this.ka.duration:0}};"use strict";let Yb=0;
function Q(b,a){a=!!a;b.sb!==a&&(b.sb=a,b.sb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.Qd,b.F.distanceModel=b.u.Bd,b.F.refDistance=b.u.Rd,b.F.maxDistance=b.u.Pd,b.F.rolloffFactor=b.u.Td),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ga())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ga())))}
function R(b,a){a=!!a;b.Vb!==a&&(b.Vb=a,b.Vb?(Q(b,!1),b.fa=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.ga())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.ga())))}function yb(b,a){b.Vb&&b.Zc!==a&&(b.fa.pan.value=a,b.Zc=a)}function U(b,a){b.La=a;b.G.gain.cancelScheduledValues(0);b.Ta=-1;b.G.gain.value=b.rc()}function Vb(b,a){a=!!a;b.Ua!==a&&(b.Ua=a,b.Nb())}
function xb(b,a,c,d,e){if(b.sb){var f=b.Ya,g=b.Xa,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Tc?b.u.Mc:performance.now()/1E3}
self.jd=class{constructor(b,a,c){this.u=b;this.P=a;this.pa=c;this.Ob=Yb++;this.G=this.V().createGain();this.G.connect(this.ga());this.F=null;this.sb=!1;this.Ya=[0,0,0];this.Xa=[0,0,0];this.ta=[0,0,0];this.fa=null;this.Vb=!1;this.Zc=0;this.J=!0;this.Y=this.ua=this.K=!1;this.La=1;this.Ua=!1;this.na=1;b=this.u.bd;this.Tc=1===b&&!this.Ca()||2===b;this.Ta=this.ra=-1;this.Vd=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}ga(){return Pb(this.u,0<this.pa.length?this.pa[0]:"")}qc(){return this.P.qc()}hb(){return this.P.hb()}pc(){return this.P.pc()}Ca(){return this.P.Ca()}O(){}mc(){}IsPlaying(){return!this.J&&!this.K&&!this.O()}Na(){}ha(){return this.P.ha()}Play(){}Da(){}jb(){}Hb(){}Pa(b){-1!==this.Ta&&b>=this.Ta&&(this.Ta=-1,this.Vd&&this.Da(),Tb(this.u,"fade-ended",this.pa,this.Ob))}rc(){const b=this.La;return isFinite(b)?b:0}Gb(){return this.u.Gb()}Nb(){}vc(){}Ga(){}uc(){}wc(){}sc(){}gb(){var b=
this.Ob,a=this.pa,c=this.ha(),d=-1===this.Ta?this.La:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ya,orient:this.Xa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ra}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Na(),playbackRate:this.na,uid:this.ra,bufferOriginalUrl:this.qc(),bufferUrl:"",bufferType:this.pc(),isMusic:this.Ca(),isLooping:this.Y,isMuted:this.Ua,resumePosition:this.sc(),pan:f,stereoPan:this.fa?
this.Zc:null}}Bc(b){var a=b.playbackRate;this.na!==a&&(this.na=a,this.Ga());Vb(this,b.isMuted)}};"use strict";
self.me=class extends self.jd{constructor(b,a,c){super(b,a,c);this.P.Ab.connect(this.G);this.P.onended=()=>this.Dc()}j(){this.Da();this.P.Ab.disconnect();super.j()}W(){return this.P.W()}Dc(){this.J=!0;this.ra=-1;Tb(this.u,"ended",this.pa,this.Ob)}O(){return this.W().ended}mc(){return this.J?!0:this.O()}Na(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ha()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.hb()}' to position '${c}': `,e)}this.u.Ea(d);this.K=this.J=!1;this.Y=b;this.na=1}Da(){const b=this.W();b.paused||b.pause();this.u.Oa(b);this.J=!0;this.K=!1;this.ra=-1}jb(){if(!(this.K||this.J||this.O())){var b=this.W();b.paused||b.pause();this.u.Oa(b);this.K=!0}}Hb(){!this.K||this.J||this.O()||(this.u.Ea(this.W()),this.K=!1)}Nb(){this.W().muted=this.Ua||this.Gb()}vc(b){b=!!b;this.Y!==b&&(this.Y=
b,this.W().loop=b)}Ga(){let b=this.na;this.Tc&&(b*=this.u.ic);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}uc(b){if(!this.J&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}sc(){return this.Na()}wc(b){b?this.IsPlaying()?(this.W().pause(),this.ua=!0):this.ua=!1:this.ua&&(this.u.Ea(this.W()),this.ua=!1)}};"use strict";
function W(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.lb=null}
self.oe=class extends self.jd{constructor(b,a,c){super(b,a,c);this.s=null;this.$b=d=>this.Dc(d);this.Oc=!0;this.lb=null;this.S=this.bc=this.dc=0;this.Xc=1}j(){this.Da();W(this);this.$b=null;super.j()}Dc(b){this.K||this.ua||b.target!==this.lb||(this.J=this.Oc=!0,this.ra=-1,W(this),Tb(this.u,"ended",this.pa,this.Ob))}O(){return!this.J&&this.s&&this.s.loop||this.K?!1:this.Oc}mc(){return!this.s||this.J?!0:this.O()}Na(){let b;b=this.K?this.S:this.bc+(V(this)-this.dc)*this.na;this.Y||(b=Math.min(b,this.ha()));
return b}Play(b,a,c,d){this.Xc=1;U(this,a);W(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ka;this.s.connect(this.G);this.lb=this.s;this.s.onended=this.$b;this.s.loop=b;this.s.start(d,c);this.K=this.J=this.Oc=!1;this.Y=b;this.na=1;this.dc=V(this);this.bc=c}Da(){if(this.s)try{this.s.stop(0)}catch(b){}this.J=!0;this.K=!1;this.ra=-1}jb(){this.K||this.J||this.O()||(this.S=this.Na(),this.Y&&(this.S%=this.ha()),this.K=!0,this.s.stop(0))}Hb(){!this.K||this.J||this.O()||(W(this),this.s=
this.V().createBufferSource(),this.s.buffer=this.P.ka,this.s.connect(this.G),this.lb=this.s,this.s.onended=this.$b,this.s.loop=this.Y,U(this,this.La),this.Ga(),this.s.start(0,this.S),this.dc=V(this),this.bc=this.S,this.K=!1)}rc(){return super.rc()*this.Xc}Nb(){this.Xc=this.Ua||this.Gb()?0:1;U(this,this.La)}vc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ga(){let b=this.na;this.Tc&&(b*=this.u.ic);this.s&&(this.s.playbackRate.value=b)}uc(b){this.J||this.O()||(this.K?this.S=b:(this.jb(),this.S=
b,this.Hb()))}sc(){return this.S}wc(b){b?this.IsPlaying()?(this.ua=!0,this.S=this.Na(),this.Y&&(this.S%=this.ha()),this.s.stop(0)):this.ua=!1:this.ua&&(W(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ka,this.s.connect(this.G),this.lb=this.s,this.s.onended=this.$b,this.s.loop=this.Y,U(this,this.La),this.Ga(),this.s.start(0,this.S),this.dc=V(this),this.bc=this.S,this.ua=!1)}Bc(b){super.Bc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.u=b;this.g=b.V();this.Jd=-1;this.T=this.$c="";this.m=null}j(){this.g=null}N(){}U(){}gb(){return{type:this.T,tag:this.$c,params:this.m}}}
self.ee=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.A=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}j(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.ce=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.xb=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.pb=X(this);this.pb.gain.value=c;this.A.connect(this.xb);this.A.connect(this.h);this.xb.connect(this.i);this.xb.connect(this.X);this.X.connect(this.pb);this.pb.connect(this.xb)}j(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.xb.disconnect();
this.X.disconnect();this.pb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.fb.md;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.pb.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.be=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.Ad=this.zd="";this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.ob=this.g.createConvolver();this.ob.normalize=c;this.ob.buffer=a;this.A.connect(this.ob);this.A.connect(this.h);this.ob.connect(this.i)}j(){this.A.disconnect();this.ob.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}gb(){const b=super.gb();b.bufferOriginalUrl=this.zd;b.bufferUrl="";b.bufferType=this.Ad;return b}};
self.fe=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.A=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.rb=X(this);this.rb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.L=X(this);this.L.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.rb);this.rb.connect(this.X);this.B.connect(this.L);
this.L.connect(this.X.delayTime);this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.X.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.rb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.B.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.rb.gain,a/100,c,d)}}};
self.he=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.A=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=X(this);this.L.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.B.connect(this.L);this.L.connect(this.D.frequency);
this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.D.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.B.frequency,a,c,d)}}};self.ge=class extends Z{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.fb.md;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.je=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.ke=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=X(this);this.L.gain.value=c/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.ie=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.A=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Cb=X(this);this.Cb.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.Cb.gain);this.B.start(0);this.A.connect(this.Cb);this.A.connect(this.h);this.Cb.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.Cb.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.de=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.A=X(this);this.fc=X(this);this.ec=X(this);b=d;.01>b&&(b=.01);this.fc.gain.value=b;this.ec.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.jc=this.g.createWaveShaper();this.Ic=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Ic[32768+e]=f,this.Ic[32768-
e-1]=-f;this.jc.curve=this.Ic;this.A.connect(this.fc);this.A.connect(this.h);this.fc.connect(this.jc);this.jc.connect(this.ec);this.ec.connect(this.i)}j(){this.A.disconnect();this.fc.disconnect();this.jc.disconnect();this.ec.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.ae=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.$d=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Gd=new Float32Array(this.l.frequencyBinCount);this.Ud=new Uint8Array(a);this.Sd=this.Za=0;b=this.u;b.Ra.add(this);T(b)}j(){this.u.Ra.delete(this);this.l.disconnect();super.j()}Pa(){this.l.getFloatFrequencyData(this.Gd);this.l.getByteTimeDomainData(this.Ud);const b=this.l.fftSize;let a=this.Za=0;for(var c=0;c<b;++c){let d=(this.Ud[c]-
128)/128;0>d&&(d=-d);this.Za<d&&(this.Za=d);a+=d*d}c=self.fb.ve;this.Za=c(this.Za);this.Sd=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";function Zb(){}function $b(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>l(b,"sw-message",a.data))}
function ac(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.ia.Ba(class extends self.Ma{constructor(b){super(b,"browser");this.v="";r(this,[["get-initial-state",a=>{this.v=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
$b(this)],["alert",a=>this.Cc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Ec(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>ac(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||this.o.wa()?window.open(c,"_blank"):this.qf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.o.wa()||"macos-wkwebview"===this.v)self.ia.Mb(!0),this.o.Fa({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===
a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(Zb)}}],["exit-fullscreen",()=>{if(this.o.wa()||"macos-wkwebview"===this.v)self.ia.Mb(!1),this.o.Fa({type:"set-fullscreen",
fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Zb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=
document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}]]);window.addEventListener("online",
()=>{l(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{l(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{l(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{l(this,"backbutton")})}Cc(b){alert(b.message)}Ec(b){b=b.isFocus;if("nwjs"===this.v){const a="nwjs"===this.v?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});
